README.md, instance/config.cfg.local
Less tech, more KB. Also— as with libris/xl_vagrant_up#3 —this is a breaking change with respect to successful OAuthorization via Libris Login.
=> Fix comment about misuse of .tech TLD from @niklasl, step 2

viewer/v2client/src/components/inspector/search-window.vue, viewer/v2client/src/utils/vocab.js
Fix duplicate keys in type dropdown tree by using a parentChainString as key
=> Fix duplicate keys in type dropdown tree by using a parentChainString as key

viewer/v2client/src/components/inspector/entity-adder.vue
Type chooser select now looks more like other input fields and doesn't take up ridiculous amount of space.
=> Change style of type chooser select menu

viewer/v2client/src/components/Inspector.vue, viewer/v2client/src/components/create/creation-card.vue, viewer/v2client/src/components/inspector/entity-adder.vue, viewer/v2client/src/components/inspector/entity-form.vue, viewer/v2client/src/components/inspector/field-adder.vue, viewer/v2client/src/components/inspector/field.vue, viewer/v2client/src/components/inspector/item-enumeration.vue, viewer/v2client/src/components/inspector/item-local.vue, viewer/v2client/src/components/inspector/item-sibling.vue, viewer/v2client/src/components/inspector/item-vocab.vue, viewer/v2client/src/components/inspector/reverse-relations.vue, viewer/v2client/src/components/inspector/search-window.vue, viewer/v2client/src/components/inspector/toolbar.vue, viewer/v2client/src/components/search/result-controls.vue, viewer/v2client/src/components/search/search-form.vue, viewer/v2client/src/components/shared/tooltip-component.vue, viewer/v2client/src/main.js, viewer/v2client/src/store/store.js, viewer/v2client/src/utils/display.js, viewer/v2client/src/utils/record.js, viewer/v2client/src/utils/string.js, viewer/v2client/src/utils/vocab.js
* More consistency when handling terms and translating to compact uri:s.
* Remove all use of the vocabPfx parameter and setting. This is now taken from the context file instead.
=> Cleanup and more consistency in vocab utility

viewer/v2client/src/components/Inspector.vue, viewer/v2client/src/resources/json/i18n.json, viewer/v2client/src/store/store.js
* Removed old status property `dirty`
* Correctly reset `unsavedChanges` and `isNew`
* Add a missing translation
* Use `unsavedChanges` bool when unloading window (not just when router is changing)
=> Fix unsavedChanges warning flow

viewer/v2client/src/components/inspector/entity-adder.vue, viewer/v2client/src/components/inspector/field-adder.vue, viewer/v2client/src/components/inspector/field.vue, viewer/v2client/src/components/inspector/item-boolean.vue, viewer/v2client/src/components/inspector/item-local.vue, viewer/v2client/src/components/inspector/item-sibling.vue, viewer/v2client/src/components/inspector/item-value.vue, viewer/v2client/src/components/inspector/item-vocab.vue, viewer/v2client/src/components/mixins/item-mixin.vue, viewer/v2client/src/store/store.js, viewer/v2client/src/utils/record.js
* Works can now be properly created as siblings instead of ordinary local entitites.
* Changed updateInspectorData so that it can recieve an array of data mutations (as one "change").
=> Work as sibling + composing of several form-changes at once

viewer/v2client/src/components/Inspector.vue, viewer/v2client/src/components/inspector/entity-form.vue, viewer/v2client/src/components/inspector/item-local.vue, viewer/v2client/src/components/inspector/item-sibling.vue, viewer/v2client/src/components/mixins/form-mixin.vue, viewer/v2client/src/store/store.js, viewer/v2client/src/utils/display.js, viewer/v2client/src/utils/vocab.js
* Moved a lot of form-functionality into `form-mixin`, so that it works the same between `entity-form`, `item-sibling` and `item-local`.
* Make `DisplayUtil.getProperties` respect `fresnel:super` and `fresnel:extends`.
* Add `DisplayUtil.getLensById`.
* Fixed so that `subClassChain` always contains curie:s.
Other changes:
* Renamed `specialProperties` to `hiddenProperties`.
* Added flushing of `changeHistory` on document load.
* Disallow `abstract`, `unstable` and `shorthand` properties from being added. (LXL-1097)
=> Sort all forms according to display

viewer/v2client/src/components/search/result-list.vue, viewer/v2client/src/utils/record.js
* Make `RecordUtil.prepareDuplicateFor()` replace work id reference properly
* Use `RecordUtil.prepareDuplicateFor()` instead of `RecordUtil.getImportObject()` when building import items.
* Removed unused `RecordUtil.getImportObject()`
* Removed unused `RecordUtil.insertWorkIntoLocal()`
(Fixes LXL-1347)
=> Fix work reference id in imports

viewer/v2client/src/components/Inspector.vue, viewer/v2client/src/components/inspector/toolbar.vue, viewer/v2client/src/store/store.js
* Move cancel event into inspector.
* Add `originalData` property and actions to store.
* Added `onPostLoaded()` where we flush the history and put the loaded data into `originalData`.
=> Make cancel restore original state of post

viewer/v2client/src/components/inspector/entity-adder.vue
* When adding object, set value to object instead of setting value to object in array.
* switched out `convertToPrefix` to `getCompactUri` function, for consistency.
=> Fix non-repeatable being forced to arrays

viewer/__init__.py
This is needed since Flask treats all slashes as path separators and
unescapes them.
=> Escape double slash in path (except for 'https?://')

viewer/v2client/src/utils/display.js
Chip for `TitlePart` expects `partName` and `partNumber`. It only has `partName`.
If `partName` is missing it would return
`{Missing http://www.w3.org/2000/01/rdf-schema#Literal}`
or (if we used the compact version, which we don't ;) )
`{Missing Literal}`
If `partName` is missing it will return `{Missing partName}`
The old code didn't care if it was a literal or not. And we only handled missing entities. We will still handle entities this way:
If the range isn't a literal, we will try to say what the type of the expected entity is. This makes it return:
`{Missing Title}`
instead of
`{Missing hasTitle}`
Which is a bit more informative.
=> Make Chips/Cards show missing property instead of range if range is a literal

CHANGELOG.md, viewer/v2client/src/components/inspector/entity-adder.vue, viewer/v2client/src/components/inspector/search-window.vue, viewer/v2client/src/utils/display.js
Moved all the reset functionality into one method.
* Removed `searchOpen` property (was unused)
* Removed `chooseLocalType` property (was unused)
* Removed `closeSearch` method (use `hide`)
* Removed `openSearch` method (use `show`)
* Added `resetSearch` method (called in `show`)
Also:
* Removed some scattered code from old pagination
=> Fixed entity-adder not resetting previous search when adding from the list

viewer/v2client/src/components/inspector/entity-adder.vue, viewer/v2client/src/components/inspector/item-local.vue
Target issue [LXL-1558](https://jira.kb.se/browse/LXL-1558)
* To create highlight, inspector's `lastAdded` property is now also set when a local entity is added
* Using the index to match `item-local.vue`'s  `getPath` property seems to be the best option since they can be identical and have no other unique identifiers... 🤔
i.e `${this.path}[${currentValue.length -1}]` === `${this.parentPath}[${this.index}]`
=> Highlight when adding local entity

viewer/v2client/src/components/search/remote-databases.vue, viewer/v2client/src/models/user.js
Targets [LXL-1344](https://jira.kb.se/browse/LXL-1344)
* Logged in user's selected remote databases are stored in new settings property `defaultDatabases`.
* `defaultDatabases` is set to `OCLC` by default.
* For non-logged in users nothing is stored or selected by default (maybe a later todo?)
=> save user's remote databases

viewer/v2client/src/resources/json/structuredValueTemplates.json, viewer/v2client/src/utils/record.js
When marc-default is added to 866 in MarcFrame the indicators become obsolete and need to be removed from the templates. This Update removes them and adds instead fields for cataloguersNote and publicNote.
=> Update 866 in item template and snippet

viewer/v2client/src/components/inspector/field.vue
`Position: sticky` on the field labels caused help popups to break:
The fix for that caused the chip popup to break:
This fixes both 🙂
=> Fix chip hover z-index issue

viewer/v2client/src/main.js
[LXL-1579](https://jira.kb.se/browse/LXL-1579) Added an exception for the '/login' route maybe causing the blank page after login. Instead it redirects to root.
=> lastPath /login redirect to root

viewer/v2client/src/components/create/creation-card.vue
Create new view: Prevents user from creating a new post of type 'välj typ' when tabbing to the select menu and pressing enter.
Keyboard navigation is now working as it should, i.e tabbing -> space (opens select) -> up or down arrows -> enter.
=> Post of type 'välj typ' bug

viewer/v2client/src/less/main.less
[LXL-1892](https://jira.kb.se/browse/LXL-1892) Sidepanel and page scrollbars are on top of each other in IE, blocking one of them from being used. Seems to be a common problem with a common [fix](https://stackoverflow.com/questions/17045132/scrollbar-overlay-in-ie10-how-do-you-stop-that).
=> IE scrollbar overlap fix

viewer/v2client/src/App.vue, viewer/v2client/src/components/Inspector.vue, viewer/v2client/src/components/inspector/entity-adder.vue, viewer/v2client/src/components/inspector/field-adder.vue, viewer/v2client/src/components/inspector/marc-preview.vue, viewer/v2client/src/components/inspector/search-window.vue, viewer/v2client/src/components/search/remote-databases.vue, viewer/v2client/src/components/shared/panel-component.vue
Hopefully solves portal issues:
* Added the [multiple flag](https://linusborg.github.io/portal-vue/#/guide?id=showing-content-from-multiple-portals-in-one-target) allowing multiple portals to render in the same portal-target
* Also added [v-if condition](https://linusborg.github.io/portal-vue/#/guide?id=conditional-rendering-with-v-if) to avoid unnecessary rendering of portals
* Removed `origin` prop. Instead all panels close before opening the new panel.
=> Portal bug fix

viewer/client/static/resources/json/keybindings.json, viewer/v2client/src/components/inspector/field-adder.vue, viewer/v2client/src/components/search/entity-search-list.vue
If we decide to only go with tabbing through side panels: 
This removes the old keybindings including its `selectNext` functions etc 
+ fixes console reference errors
+ fixes unexpected behaviour such as panel closing (caused by old keybindings colliding)
+ Field adder emits a lot less events
=> Remove unused keybinding logic

viewer/v2client/src/components/inspector/toolbar.vue, viewer/v2client/src/components/search/result-list-item.vue
Fix for Firefox funny flexbox fehaviour
Also fixes tiny Firefox issue [LXL-1896](https://jira.kb.se/browse/LXL-1896) as a bonus
=> Firefox fixes

viewer/v2client/src/components/create/creation-card.vue
Change click area on create-new-cards to be only on button instead of whole item.
Fixes [LXL-1906](https://jira.kb.se/browse/LXL-1906)
=> Change click area on create-new-cards

viewer/v2client/src/App.vue, viewer/v2client/src/components/Inspector.vue, viewer/v2client/src/main.js, viewer/v2client/src/store/store.js
Main loading indicator (like for "Loading application" and "Loading document") is now moved out of the 
router view-element so that it always appears on top of everything. This solves a situation where the loading indicator would show "below the fold" and confusing the user.
When you need to use the loading indicator you can use
"pushLoadingIndicator" and "removeLoadingIndicator" in the store. It takes a string as argument (the string you want to be displayed. The indicator component will try to translate the string, so use english labels in the code.
=> Move main loading indicator

viewer/v2client/src/components/inspector/entity-header.vue, viewer/v2client/src/components/inspector/item-local.vue, viewer/v2client/src/components/inspector/item-sibling.vue, viewer/v2client/src/components/inspector/search-window.vue, viewer/v2client/src/components/search/panel-search-item.vue, viewer/v2client/src/components/search/result-list-item.vue, viewer/v2client/src/components/shared/card-component.vue, viewer/v2client/src/components/shared/entity-summary.vue, viewer/v2client/src/components/shared/panel-component.vue
Issue [LXL-1970](https://jira.kb.se/browse/LXL-1970), prevent entity-summary from having too much content, filling up the entire sidebar for example.
* Removed old unused `lines` prop, added `valueDisplayLimit` prop. This can be used to limit the number of values rendered on each property. For example `valueDisplayLimit=1` turns "Language: swedish, italian, norwegian" into "Language: swedish (+2)". This means different instances of entity-summary can show different amounts of data. Feel free to change the values I set for them.
* max-height on container and other css-fixes
=> Restrict entity-summary 

viewer/v2client/src/components/search/result-controls.vue
Fix missing 'limit' param in remote search (caused "too many hits" message every time)
[LXL-2007](https://jira.kb.se/browse/LXL-2007)
=> Fix missing 'limit' param in remote search

viewer/v2client/src/components/shared/filter-select.vue
Trying another way of simulating click since `new MouseEvent` is not supported in IE.
=> Filter-select IE fix

viewer/v2client/src/components/inspector/item-local.vue, viewer/v2client/src/components/inspector/item-sibling.vue, viewer/v2client/src/less/_variables.less
[LXL-1573](https://jira.kb.se/browse/LXL-1573)
* Refactored this functionality, v-binding classes directly to `isEmpty` prop making it more reactive
* This fixes previously non-working case described in issue above
=> Inactive arrow refactor

viewer/v2client/src/components/inspector/entity-adder.vue, viewer/v2client/src/components/inspector/field.vue, viewer/v2client/src/components/inspector/item-entity.vue, viewer/v2client/src/components/inspector/item-local.vue, viewer/v2client/src/components/inspector/item-sibling.vue, viewer/v2client/src/components/inspector/item-value.vue, viewer/v2client/src/components/inspector/toolbar.vue, viewer/v2client/src/components/inspector/type-select.vue, viewer/v2client/src/main.js, viewer/v2client/src/utils/layout.js
[LXL-1987](https://jira.kb.se/browse/LXL-1987): Move the select menu that lets you choose what type of property to add. Today it's absolute positioned on top of entity adder. We want to make it a placeholder where the new item will be placed.
Doing this with dynamically named portals do send the right select menu to the right place. This, in turn requires some extra functionality:
* We want to autofocus it, i.e need to know when it's mounted -> refactored it into own component `<type-select>`
* Possible long distance from (+) button to menu -> implemented autoscroll 
* New solution works badly with clickaway -> added 'remove' button instead. Remove is not available when the field is empty.
=> Move type select with portal

viewer/v2client/src/components/inspector/entity-header.vue
I think we should throttle scroll events. Scrolling a medium expanded post fires 100-300 function calls. With throttling (interval of 300ms) this is reduced to 10-30.
Entity header is somewhat less responsive, but should benefit overall performance :)
=> Throttle scroll events

viewer/v2client/src/components/inspector/toolbar.vue
[LXL-1894](https://jira.kb.se/browse/LXL-1894).
This probably has to do with Edge limiting the length of href URL:s, a long standing issue with data URI:s, see [here](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4282810/)
Implemented Microsoft's recommendation to create a [URL from a blob](https://textslashplain.com/2018/08/06/script-generated-download-files/) instead, although I can't compare the output in local env - just empty files. Thoughts are welcome 🙂
=> Download compiled Marc in Edge

viewer/v2client/src/components/Create.vue
* Pipe "files" through `prepareDuplicateFor` function so that IDs and similar are cleaned
In other words it will now take the same path into the application as all other templates.
You can test this by downloading an existing JSON-LD file and creating a new post from it with "from file". Before this, it would include the IDs and the old descriptionCreator, now it cleans this and sets TEMPID as it should.
Run `getJsonOutput()` in console to see the raw data in the app.
If you check this result against the same operation on DEV, you should get different results.
=> Fix "from file" so that it removes and modifies fields that should not be copied

viewer/v2client/src/components/inspector/entity-adder.vue
Fixes [LXL-1980](https://jira.kb.se/browse/LXL-1980)
The code was acting under the impression that there would never be more than one "instanceOf" per document. When adding a new value to more than of these, they would be mirrored to each other.
This caused updates in one of the values to be mirrored (or cloned) to the other one.
=> Fix bug regarding multiple siblings

viewer/v2client/src/components/inspector/entity-adder.vue, viewer/v2client/src/components/shared/tooltip-component.vue, viewer/v2client/src/less/_variables.less
A fix so that new item highlighting works in case described in [LXL-1964](https://jira.kb.se/browse/LXL-1964). As a bonus, adder (+) focus also works.
Was caused by an index value always being appended to the path, even if it was a single (empty) object, resulting in a path like `somePath[isNaN]`. Fix does a check to prevent this.
=> Highlight local entity fix

viewer/v2client/src/components/inspector/item-local.vue, viewer/v2client/src/components/inspector/item-sibling.vue, viewer/v2client/src/components/inspector/toolbar.vue, viewer/v2client/src/components/shared/round-button.vue, viewer/v2client/src/less/button-links-chip.less, viewer/v2client/src/less/form.less, viewer/v2client/src/less/main.less
This PR wishes to restore some minor design stuff that has broken during recent development etc:
* Restore disabled look of buttons in sidepanel
* Restore disabled look of undo button in toolbar
* Disable blue outline on focus (since we apply our own .user-is-tabbing outline)
* Make .user-is-tabbing outline show in in Explorer & Edge
* Consistent tabbing outline for our custom checkbox & icons in form
=> Minor design restoration

viewer/v2client/src/components/search/search-form.vue
[LXL-2071](https://jira.kb.se/browse/LXL-2071) - Can't reset facet filters on new search.
I think the most straightforward solution (currently) is to disregard the facet filters on new search and only look for the checkbox filters. Since the search query remains in the box, a new search would be an equivalent to having a "clear filters" button. I also think this is the expected behavior, as opposed to the facets still restricting the search. Please correct me if i'm wrong :)
=> Clear facets on new search

viewer/v2client/src/components/inspector/field.vue, viewer/v2client/src/components/inspector/item-entity.vue, viewer/v2client/src/components/inspector/item-local.vue, viewer/v2client/src/components/inspector/item-sibling.vue, viewer/v2client/src/components/inspector/item-value.vue, viewer/v2client/src/less/button-links-chip.less
[LXL-2053](https://jira.kb.se/browse/LXL-2053)
Today a newly added item always resets the `inspector.status.lastAdded` after 1 sec. This can screw up the match of some other component that has been added in the meantime, resulting in jittery highlight & unreliable button focus.
Fix is to add another check of `lastAdded` inside `setTimeout`.
Also removed some duplicate code.
=> Inconsistent adder focus fix

viewer/v2client/src/components/inspector/entity-adder.vue
A late buggfix for [this](https://github.com/libris/lxlviewer/pull/251) PR, preventing autofocus of a disabled adder-icon instead of the type select.
=> Added contitional ref

viewer/v2client/src/components/inspector/field.vue
Paste button was missing from inline (or nested) fields.
=> Add paste button in inline fields

viewer/v2client/src/components/inspector/entity-adder.vue, viewer/v2client/src/components/inspector/item-local.vue, viewer/v2client/src/components/inspector/item-sibling.vue
Adding to [LXL-2101](https://jira.kb.se/browse/LXL-2101)
Render a disabled icon instead of nothing when linking could be performed but entity is empty.
=> Link empty entity fix

viewer/dataaccess.py, viewer/v2client/src/store/store.js
This replaces publication.date, since that field tends to include
additional information.
=> Use publication.year in facets

viewer/vue-client/src/components/inspector/item-local.vue, viewer/vue-client/src/components/inspector/item-sibling.vue, viewer/vue-client/src/store.js
- Removed baseclass `Identity` from extractable classes, this removes `Concept`, `Agent`, `Work` from extraction
- Add `Agent` and `Work` to extractable classes.
- Add `/data` to apiPath when making extraction calls.
=> Fix path for extractions and block Concept chain from extraction

viewer/vue-client/src/components/inspector/item-local.vue, viewer/vue-client/src/components/inspector/search-window.vue, viewer/vue-client/src/components/shared/panel-component.vue
[LXL-2240](https://jira.kb.se/browse/LXL-2240) - A feature that seems to come across as a bug (i.e empty entities cannot be extracted, therefore disabling link icon)
Proposing the following to tackle this instead: Don't render the extract-and-link box in sidepanel if the local entity is empty. But still allowing to search-and-replace.
=> Re-enable link icon

viewer/vue-client/src/components/inspector/modal-pagination.vue
Should probably be rewritten going forward.
It's kind of confusing that it loops over the `numberOfPages` in this way.
=> Fix pagination having too many pages (off by 1!)

viewer/vue-client/src/main.js
Small fix I had laying around in a stash.
Prohibits pagetitle from becoming "null" when page is loading or similar.
=> Fix null pagetitle

viewer/vue-client/src/components/inspector/item-sibling.vue
Classic mistake, forgot to make the same changes in `item-sibling` as in `item-local` 😳
=> Re-enable link icon (addition!)

viewer/vue-client/src/components/shared/panel-component.vue
`'close-modals' !== ['close-modals']`
Panel should now close with esc again.
=> Fix panel esc bug

viewer/vue-client/src/components/inspector/field.vue
[LXL-2050](https://jira.kb.se/browse/LXL-2050) - appears in Edge v.41 and back. I think this should fix it.
=> Fix Edge helpbubbles bug

viewer/vue-client/src/App.vue, viewer/vue-client/src/components/search/facet-group.vue, viewer/vue-client/src/components/search/remote-databases.vue, viewer/vue-client/src/components/search/search-form.vue, viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/resources/json/propertymappings.json, viewer/vue-client/src/views/Find.vue
According to [LXL-2300](https://jira.kb.se/browse/LXL-2300)
I ended up rewriting most of the `search-form` component - it can now search only one prop at a time, but should have a more user friendly UI (according to design in ticket). The component also recognizes a performed search, populating select menu, text input and select boxes with the current values.
**Bonus features:**
* 'libris' and 'remote' now share the same v-bound input, so queries are immediately reflected in both places. Means remote also gets a 'clear' btn.
* remote: cursor automatically jumps to sidebar/search field when opened/closed.
=> Refactor/redesign search-form

viewer/vue-client/src/views/Inspector.vue
Same workaround has been used for `Download Compiled Marc` before. This is for the "download json" and "download json (incl unsaved changes)".
We can probably spin this branch on dev2 to check it.
=> Add workaround for IE11 when downloading Blob

viewer/vue-client/src/components/inspector/item-local.vue, viewer/vue-client/src/components/inspector/item-sibling.vue
[LXL-2370](https://jira.kb.se/browse/LXL-2370)
Adds this conditional on `expand-item` & `collapse-item` events: 
`if (this.getPath.startsWith(this.inspector.status.focus) || (this.getPath.startsWith('work') && this.inspector.status.focus === 'mainEntity')) `
=> Expand only focused fields

viewer/vue-client/src/components/layout/navbar.vue, viewer/vue-client/src/components/search/search-form.vue, viewer/vue-client/src/components/shared/tab-menu.vue
Adds a link option to `tab-menu `component. If true, will render a `<router-link>` to supplied path instead of emitting an event. Perks: user sees where tab leads & can open in new tab.
Implemented this in main navbar & search-form.
=> Tab router link

viewer/vue-client/src/router.js, viewer/vue-client/src/views/DirectoryCare.vue
Use a default route instead of pushing route if no tool param
=> Fix holdings not being standard view if directory care clicked twice

viewer/vue-client/src/components/care/holding-mover.vue, viewer/vue-client/src/components/care/post-picker.vue, viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/views/DirectoryCare.vue
...instead of local spinners. More consistent with how it's done in Inspector etc.
Also expanding & focusing the sender dropdown on mount. Saves a click!
=> Use global loadingIndicator

viewer/vue-client/src/components/care/post-picker.vue
Filter instances using properly calculated headers (using `getItemSummary` and `getFormattedEntries`).
These are stored in a separate computed `headers` array to avoid the operation being done at every keystroke. It is then filtered by the search phrase and matched with the real data object...
=> Fix filteredInstances

viewer/vue-client/src/components/care/holding-list.vue, viewer/vue-client/src/components/care/post-picker.vue
Post-picker now watches `userCare` and if something is selected that's no longer present there, unselects it.
also...
+ Remove custom checkbox because it can't handle the scroll...
+ check presence of input to avoid referenceError
+ Properly center holding actions
=> Unselect gone

viewer/vue-client/src/components/care/post-picker.vue, viewer/vue-client/src/components/shared/tag-switch.vue, viewer/vue-client/src/store.js, viewer/vue-client/src/views/DirectoryCare.vue, viewer/vue-client/src/views/Inspector.vue
use `DisplayUtil.getItemLabel` to save entity's title in userCare along with its id. We then display it in case of removed/not found as a service to the user.
The object saved to `localStorage.userStorage.[hash].list` will now look like:
```
"id": {
"tags":["Directory care"],
"label":"title"
}
```
in store `userCare` this will convert to
```
[
{"@id":"id", 
"label":"title"}, ...
]
```
**Flush ye flagged items before testing, or all will fail!**
=> Add title to userStorage

viewer/vue-client/src/components/care/holding-list.vue, viewer/vue-client/src/components/care/holding-mover.vue, viewer/vue-client/src/components/care/post-picker.vue
In collab with @mattiasbolin, this includes following changes:
* Absolute positioned post-picker dropdown to create a more dropdown-y feel
* Don't open dropdown on mount, to make the need for selection more clear
* Align picker heights + holding container take up space, but not visible when no selection.
* Should now look ok and function across all widths. On small screen we hide the reciever holding list!
=> Absolute dropdown etc

viewer/vue-client/src/components/care/holding-list.vue
Flush `directoryCare.holdingsMoved` before moving. If already populated, `holdingsMoved` & `progress` arrays won't match in length & modal won't open.
=> Reset holdingsMoved

viewer/vue-client/src/resources/json/structuredValueTemplates.json
Geographic entity can contain either prefLabel (reverts to bib
651) or just label (reverts to bib 653 ind2=5).
=> Remove snippet for Geographic

viewer/vue-client/src/components/mixins/lens-mixin.vue
[LXL-2426](https://jira.kb.se/browse/LXL-2426)
Modifies the `getItemLabel` function so that it, if an element is an array, returns it as a comma separated string to be displayed as collapsed text:
More readable + prevents layout havoc as described in issue.
=> Space separate collapsedText

viewer/vue-client/src/components/search/result-controls.vue, viewer/vue-client/src/resources/json/i18n.json
[LXL-2349](https://jira.kb.se/browse/LXL-2349)
Result-control `filters` now tries very hard to find a translatable label, either by straight up translating the `value` prop, or (in the case of languages for example), look in the facet data for a `labelByLang` or `prefLabelByLang` key.
Also translated some stuff in component markup, it should look ok in english now too...
=> Translate filters in result-control 

viewer/vue-client/src/components/search/result-controls.vue, viewer/vue-client/src/components/search/search-form.vue, viewer/vue-client/src/components/search/sort.vue, viewer/vue-client/src/models/user.js, viewer/vue-client/src/resources/json/i18n.json
Reworked `search-controls` component according to design in [ticket](https://jira.kb.se/browse/LXL-2432) including:
* Display active facets as removable filter badges
* New copy / search info
Also 
* Made type checkboxes + search bar query + searchtype dropdown reactive to route changes to always reflect the actual search (when using the back-button for example) - necessary since we no longer print out the searchphrase in search-controls info.
**U may need to restart Vagrant to include an API fix that fixes facet 'up'-links**
**UPDATE:**
Now also includes [LXL-2453](https://jira.kb.se/browse/LXL-2453) since it's practically an extension of the code above. The current search param (Free text, ISBN, Main title etc) is now stored in user settings and reused on a clean search. 
The 'active' …
=> LXL-2432 Removable filter

viewer/vue-client/src/components/inspector/breadcrumb.vue, viewer/vue-client/src/components/search/search-result.vue, viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/store.js, viewer/vue-client/src/views/Find.vue, viewer/vue-client/src/views/Inspector.vue
This PR suggests a new approach to breadcrumbs, to fix the following problems:
* Fetching of excessive data in search results
* Breadcrumb links not corresponding with result list (when using custom sort for example), ie [LXL-2351](https://jira.kb.se/browse/LXL-2351)
* Breadcrumb links not showing at all (when searching by mainTitle for example)
* Breadcrumb component throwing errors
**What it does:**
Instead of doing a costly parallell search, fetching and saving _all_ results into vuex, this merely re-uses existing search result data as a starting point. When navigating from the `Find` to the `Inspector` view, we pass it along in the vue router `meta`-field together with the offset and position on current page. When this is not sufficient (on the last post of a page clicking "next", for …
=> LXL-2351 - Fix breadcrumbs

viewer/vue-client/src/components/search/search-form.vue, viewer/vue-client/src/components/search/sort.vue, viewer/vue-client/src/models/user.js
Saves the last used sort option in `user.settings.sort` to use as default on next search.
=> LXL-2417 Save sorting preference

viewer/vue-client/src/main.js, viewer/vue-client/src/store.js, viewer/vue-client/src/views/Help.vue
Example:
We're on the section "Att använda verktyget" in the help docs.
Before page title was:
`Hjälp | Libris katalogisering`
Now it will be:
`Att använda verktyget - Hjälp | Libris katalogisering`
=> Add help section to page title

viewer/vue-client/src/views/Inspector.vue
Sometimes embellish actions triggers multiple `inspector.data` changes (`change` events on dropdowns for example). The timeout prevents the second event from cancelling the highlight triggered by the first.
Example: 'Datorspel' template.
=> Embellish highlight fix

viewer/vue-client/src/components/shared/entity-summary.vue
[LXL-2505](https://jira.kb.se/browse/LXL-2505) - Entity summary breaks in preview mode (in sidepanel when using the link tool)
**Example:**
Id: n60000q0107s08v
Instans av verk -> text -> har del -> multimedia -> länk-ikon
**Cause:** 
`EntitySummary-id` (where u can copy the ID) tries to extract the `@id` - but there is none since the post doesn't exist (yet, it's a preview) - and breaks.
**Fix:**
Don't render this element if `idAsFnurgel()` doesn't return a proper value.
=> LXL-2505 Broken summary fix

viewer/vue-client/src/resources/json/combinedTemplates.json, viewer/vue-client/src/resources/json/structuredValueTemplates.json
Remove faulty lists in templates and snippets for entitites in ProvisionActivity like Agent, Place, etc. Which means only one label per entity.
=> Remove labels as lists in snippets and templates

viewer/__init__.py
Preparing some endpoints for us to try out when rebuilding the front page.
These changes does not affect the UI in any way.
* Added two flask-paths for proxying get requests for:
* Libris news (KB-news with keyword Libris)
* Matomo active user count (only anonymous data)
=> Add proxies for libris news and for matomo data

viewer/vue-client/src/components/inspector/toolbar.vue, viewer/vue-client/src/views/Inspector.vue
* In addition to checking `mainEntity.heldBy`, check in hasComponent if the active sigel is found there to calculate permission of editing the holding
* If `mainEntity.heldBy` is missing when starting edit, we will add the active sigel automatically.
Extra:
* Switched out components directly setting `inspector.status.editing` and made them use the post-control event system instead (which calls the `startEditing` and `stopEditing` functions).
* Renamed computed property `libraryUrl` to `activeSigelId`
=> LXL-2540 - Support checking permissions on heldBy in hasComponent

viewer/vue-client/src/resources/json/copy.json
Instead of going through
`youtube.com`
we will embed it through 
`youtube-nocookie.com`
=> Change embedded youtube video to go through GDPR-compliant domain

viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/store.js, viewer/vue-client/src/utils/display.js
Some of the translation uses the application settings instead of the user settings for the language parameter.
Syncing these would solve some of the things not being internationalized.
**In particular this concerns the** `...byLang` **properties in display chips/cards**
=> Sync application language with user language

viewer/vue-client/src/components/search/search-form.vue, viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/store.js
* Adds sorting options for Work (hasTitle.mainTitle = same as for instance)
* Adds sorting options for Concept (prefLabel) (note: lots of concepts lack this property, so they will come after the sorted ones).
Bonus:
* Fixed so that the preferred sort order will reset to default if the specific type doesn't allow that sort order, instead of just trying to sort by it and failing (and showing empty input field).
=> LXL-2770 Sort options for Work and Concept

viewer/vue-client/src/components/care/holding-list.vue, viewer/vue-client/src/components/inspector/breadcrumb.vue, viewer/vue-client/src/components/inspector/entity-adder.vue, viewer/vue-client/src/components/inspector/relations-list.vue, viewer/vue-client/src/components/inspector/search-window.vue, viewer/vue-client/src/components/shared/preview-card.vue, viewer/vue-client/src/components/shared/tag-switch.vue, viewer/vue-client/src/models/user.js, viewer/vue-client/src/utils/http.js, viewer/vue-client/src/views/DirectoryCare.vue, viewer/vue-client/src/views/Find.vue
Bonus:
* When tagging for Directory Care we will tag the record id (instead of mainEntity like before).
* When fetching the list for Directory Care, use the lens-param to only fetch cards instead of fetching the record and then extracting the mainEntity.
=> Fetch jsonld everywhere instead of json

viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/resources/json/propertymappings.json
Added:
* You can use form to search for `hasTitle.mainTitle` for type `Work`.
* You can use form to search for `prefLabel` for type `Concept`.
=> LXL-2771 Add more options for search form

viewer/__init__.py
Handle it the same way as backend.
An alternative would have been to configure apache to strip `-gzip` from the header or to not add it in the first place.
=> Handle Etag with -gzip

viewer/vue-client/src/components/inspector/item-local.vue, viewer/vue-client/src/components/inspector/item-sibling.vue, viewer/vue-client/src/components/mixins/item-mixin.vue, viewer/vue-client/src/store.js
Also:
* Move general code into mixin
* Lock derivedFrom property in app-settings (so it can't be deleted/edited in GUI)
=> Apply derivedFrom when extracting entities

viewer/vue-client/package.json, viewer/vue-client/src/utils/display.js, viewer/vue-client/src/utils/vocab.js
It used in many places. 
Fix: Precompute all "byLang" keys (e.g. 'prefLabel' -> 'prefLabelByLang') when loading context.
Speeds up search results list a lot.
Cuts loading time of "Kalle Anka & C:o" (https://libris-stg.kb.se/katalogisering/l3wsrw5x0wwzqlh) with 25% on my machine.
=> Speed up getValueByLang

viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/utils/display.js
Example:
A language is missing "code". Instead of returning:
`{Missing code}` (or `{Kod saknas}`)
it will return:
`{Language without code}` (or `{Språk utan kod}`)
Should make it clearer what object is missing the property in question.
=> Labels: Replace "{property} missing" with "{type} without {property}"

viewer/vue-client/src/store.js
No ticket
Lock generationDate and generationProcess properties in adminmetadata.
=> Add lock to generationDate and generationProcess in record

viewer/vue-client/src/components/shared/preview-card.vue, viewer/vue-client/src/utils/record.js
[LXL-2864](https://jira.kb.se/browse/LXL-2864)
Translates id.kb.se links correctly for the items still not being translated correctly. Also fixed some cards not fetching card data due to the #it being kept in recordId.
* shouldFetch flag does now checks `this.recordId` in addition to `this.focusData['@id']`.
* `getRecordId` now strips `#id` from the id.
=> Fix that some preview-cards are not fetching data correctly

viewer/vue-client/src/views/Inspector.vue
Change text for button and confirm message to reflect the record type being deleted
[LXL-2781](https://jira.kb.se/browse/LXL-2781)
Confusion whether item or post was being removed.
=> Add record type to string translations in delete dialog

viewer/vue-client/package.json, viewer/vue-client/yarn.lock
#383  Description
Bump Combokeys to newest version which includes our pull request.
[LXL-1893](https://jira.kb.se/browse/LXL-1893)
Firefox key-shortcut for alt+plus not working on Windows
Points to a tar.gz in combokeys Github-repo.
=> bump combokeys version

viewer/__init__.py
This broke downloading raw data by saving from Chrome, which apparently
doesn't send any Accept header on save request.
(Also using `curl -H'Accept:' -v https://libris-dev.kb.se/zg858p49460nsps/data.jsonld` triggers this.)
=> Don't expect 'Accept' header to always be present

viewer/vue-client/src/components/inspector/item-error.vue
Changes the items where we can't render a proper component on an object. Instead of just showing a JSON-string we will now show it as a table.
See http://localhost:8080/katalogisering/7k64qptb958dhb8s for an example of a post where this type is shown.
None
* Added some css for the table and font
* Switched out the json string in template to a loop over the item into a table.
=> Change item-error to be a table of key/values instead of just json string

viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/views/Inspector.vue
Replaced "record"/"post" with a more general term "resource"/"resurs"
=> terminology: replace "record" with "resource" in error page statuses

viewer/vue-client/src/components/search/panel-search-item.vue
Fallback in case reverseLinks are not returned at all.
none
check if reverseLinks is not undefined
=> Reverselinks fallback

viewer/vue-client/src/components/search/link-card.vue, viewer/vue-client/src/resources/json/copy.json
[LXL-2887](https://jira.kb.se/browse/LXL-2887)
Even though we use the youtube-nocookie variant, youtube still saves some small cookies.
Add a confirmation box before autoplaying the video if the video has a youtube-url.
=> Add confirmation to play video from youtube

viewer/vue-client/src/views/Inspector.vue
Stumbled upon this translation string, that should be in English.
=> corrected translation string

viewer/vue-client/src/utils/display.js
Original behavior.
i.e. https://libris-qa.kb.se/katalogisering/1rznbwb534c3znk5 should not display altLabel in card if user language setting is "sv."
=> Only translate if language in settings is present in item

viewer/vue-client/src/components/inspector/reverse-relations.vue
For now, show reverseLinks for type Instance
[LXL-2929](https://jira.kb.se/browse/LXL-2929)
Performance improvement (less calls to server)
Checking if mainEntity has reverseLinks and recordType is Instance, then show the amount
If false, do the o-query as usual
=> show reverse links amount on instance

viewer/vue-client/src/components/search/result-controls.vue
noOfPages returning wrong number of pages in some cases.
Ex: 
40 hits / 20 page limit returning pageCount of 3.
[LXL-3034](https://jira.kb.se/browse/LXL-3034)
Corrected the noOfPages calculation.
=> corrected noOfPages count

viewer/vue-client/src/components/create/creation-card.vue, viewer/vue-client/src/components/inspector/entity-adder.vue, viewer/vue-client/src/components/inspector/item-type.vue, viewer/vue-client/src/components/inspector/search-window.vue, viewer/vue-client/src/components/shared/filter-select.vue, viewer/vue-client/src/utils/display.js, viewer/vue-client/src/utils/vocab.js
[LXL-2821](https://jira.kb.se/browse/LXL-2821)
Sorts the type-select in the users language instead of just english.
* When accumulating sub-classes of a term, sort the list of subclasses before returning them.
* Renamed utility function `getFormattedSelectOption` to `getLabelWithTreeDepth`
=> [LXL-2821] Sort in user language

viewer/vue-client/src/views/Help.vue
A11y fix, help navigation should be accessible by keyboard. 
[LXL-2984](https://jira.kb.se/browse/LXL-2984)
Removed click event on li-element, added router-link
=> Help navigation as links

viewer/vue-client/package.json, viewer/vue-client/src/components/layout/search-bar.vue, viewer/vue-client/src/store.js, viewer/vue-client/vue.config.js, viewer/vue-client/yarn.lock
To clarify what version is run on different environments, this change will make the version-indicator in the header show the tag if on a tag, and the (short) commit hash if not on a tag.
None
* Added package git-describe
* Changed the info shown in the header
=> Show tags/hashes in version indicator

viewer/vue-client/src/utils/vocab.js
None
Fixes the sorting crashing when there is no label on the term being sorted.
* Allow it to check prefLabel as well as label (was only label before)
* Check for existance of label in sort, otherwise sort at end
=> Fix sorting issue with terms without labels

viewer/vue-client/src/components/inspector/entity-adder.vue, viewer/vue-client/src/components/inspector/item-local.vue, viewer/vue-client/src/components/mixins/form-mixin.vue
[LXL-3071](https://jira.kb.se/browse/LXL-3071)
Fixes a problem where the type changer component wouldn't be shown in local entities.
- Changed the condition for when to show the type changer (`item-type`)
- Changed the condition for when a local entity is considered "empty", allowed it to take the above condition in consideration (ie if the type changer is shown, count @type as a field, if not then don't).
- Fixed so that siblings are never added in the gui, only tolerated.
=> LXL-3071 - Fix type changer not appearing where expected

viewer/templates/marcframeview.html
https://jira.kb.se/browse/LXL-3084
Handles fields mapped to null in marcframe view template. Template would throw on these resulting in HTTP 500.
example marcframe.json
```
"Multimedia": {
"[18] [19] [20] [21]": null,
``` 
Also hides some more instances of "TODO" in the marcframe view.
=> Handle null mappings in marcframe view

viewer/vue-client/src/components/inspector/toolbar.vue, viewer/vue-client/src/main.js, viewer/vue-client/src/store.js, viewer/vue-client/src/views/Create.vue
Allow authors of templates to set `status: draft` on templates which will hide them from use in UI.
[LXL-3113](https://jira.kb.se/browse/LXL-3113)
- Added filtering of `status`  property on templates.
- Moved the import of template json to store.
=> [LXL-3113] Filter templates with "draft" status, move template storage into store

viewer/vue-client/src/utils/uriminter.js
Frontend encoded uris does not match backend encoded uris, ie. parantheses () not being encoded to %28 %29 with the standard javascript method encodeURIComponent.
This fixes this problem.
[LXL-3066](https://jira.kb.se/browse/LXL-3066)
Encode following special chars: [!'()*] 
Added a wrapper function that encodes additional special characters.
=> encode additional characters in order to sync with backend encoded uris

viewer/vue-client/src/components/inspector/toolbar.vue, viewer/vue-client/src/resources/json/i18n.json
Also see #625 
[LXL-3113](https://jira.kb.se/browse/LXL-3113)
The enrichment list from inside a post was empty every time.
* Corrected the path of where to look for templates.
* Added item to show if the list is empty.
=> Fix templates looking in the wrong path for enrichment

viewer/vue-client/src/components/inspector/item-entity.vue
When navigating with keyboard and linking keyboard focus is lost.
Need to set focus on last added chip.
[LXL-3005](https://jira.kb.se/browse/LXL-3005)
Focusing on last added chip, but only after side panel being closed.
Added a variable to trigger newly added animation class.
=> [LXL-3005] when linking, add focus to last added chip

viewer/vue-client/src/utils/uriminter.js, viewer/vue-client/src/views/Inspector.vue
[LXL-2832](https://jira.kb.se/browse/LXL-2832)
Fixes toolbar not appearing when concepts are missing inScheme.
* Added sanity checks to uriminter and some toolbar computed properties.
=> LXL-2832 Fix toolbar not showing on concepts without inScheme

viewer/vue-client/src/resources/json/copy.json
[LXL-3147](https://jira.kb.se/browse/LXL-3147)
* Changes the link (not the video) to go to the playlist instead of the first video.
* Embedded video is unchanged.
=> LXL-3147 Change youtube playlist link to actually go to the playlist

viewer/vue-client/src/components/shared/preview-card.vue
[LXL-2960](https://jira.kb.se/browse/LXL-2960)
PreviewCard showing wrong card. This can happen when focusData is changed after the full data had already been fetched. If the array of entities is changed, vue sometimes confused which entity is which. This ensures that when the focusData is changed, it is reflected in the fetchedData and fullData.
Added a watcher on focusData which resets the fetchedData to null, triggering a new fetch if it is needed.
=> 2960 Fix PreviewCard not showing correct card

viewer/vue-client/src/App.vue, viewer/vue-client/src/components/inspector/toolbar.vue, viewer/vue-client/src/resources/json/combinedTemplates.json, viewer/vue-client/src/resources/json/display.json, viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/store.js, viewer/vue-client/src/utils/record.js, viewer/vue-client/src/views/Inspector.vue
Adds a meny item on instances (which are not already Electronic) to create a "Digital Reproduction" version of the same instance.
[LXL-3126](https://jira.kb.se/browse/LXL-3126)
* Added menu item to toolbar
* Added translations
* Added utility `getDigitalReproductionObject` in `RecordUtil`
* Added loading indicators for toolbar operations `duplicateItem` and `createDigitalReproduction`.
* Added `v-show` conditional for `router-view`.
=> 3126 Digital Reproduction flow

viewer/vue-client/src/utils/record.js
[LXL-3208](https://jira.kb.se/browse/LXL-3208)
Solves visual bug where @reverse nodes are being included in copies of a post (ie copy, enrichment etc).
Remove @reverse nodes in prepareDuplicateFor method.
=> Delete @reverse nodes in prepareDuplicateFor method

viewer/vue-client/src/utils/record.js
Should merge into a hotfix branch if hotfix, else develop
[LXL-3231](https://jira.kb.se/browse/LXL-3231)
- Add undefined check before accessing @id on instanceOf value
=> Make "Create digital reproduction" not crash when instanceOf is missing @id

viewer/__init__.py
Requests to `/<id>` without `Accept:` header would return HTTP 500.
`curl 'http://kblocalhost.kb.se:5000/n0xpcvb8l93wbdhq' -H 'Accept:'`
before:
`< HTTP/1.0 500 INTERNAL SERVER ERROR`
after:
`< HTTP/1.0 406 NOT ACCEPTABLE`
=> Fix HTTP 500 on missing Accept header

viewer/vue-client/src/components/inspector/entity-form.vue, viewer/vue-client/src/components/inspector/field.vue, viewer/vue-client/src/components/mixins/form-mixin.vue, viewer/vue-client/src/components/search/search-form.vue, viewer/vue-client/src/main.js, viewer/vue-client/src/resources/json/displayGroups.json, viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/utils/display.js
[LXL-3211](https://jira.kb.se/browse/LXL-3211)
Makes it possible to alter `displayGroups.json` to tell reverse properties if they should be placed into the regular form instead of the section with "resources that link to this resource".
* Split up reverse-list depending on the `displayGroups.json`
* Hide "resources that link here" if the list is empty.
* Added icon and lock state for the reverse properties that are placed in the form.
=> [WIP] LXL-3211 - Support for putting some reverse-properties in the regular form

viewer/vue-client/src/components/inspector/entity-adder.vue
Fix search containing hyphen in side panel
example: Lill-arm should find Lill-armenien
Make the condition matching "operator" handle hyphen correctly, i.e do not match inside words.
e.g. match "-armenien" but not "lill-armenien"
=> Fix side panel entity search for words containing hyphen

viewer/vue-client/src/components/inspector/toolbar.vue
A Part of toolbar menu is not accessible with a submenu expanded.
[LXL-3282](https://jira.kb.se/browse/LXL-3282)
Fixes the bug by making the menu scrollable.
Added scroll and various max-height values depending on viewport height.
=> adjust toolbar menu height  to viewport height, add scroll

viewer/vue-client/src/components/inspector/toolbar.vue
Marc preview should be disabled when viewing Work
[LXL-3234](https://jira.kb.se/browse/LXL-3234)
Disables the marc preview button in toolbar menu when recordType is Work
=> disable marc preview when recordType is Work

viewer/vue-client/src/views/Inspector.vue
[LXL-3306](https://jira.kb.se/browse/LXL-3306)
Fixes linked works being overwritten by local works from the template.
Check for existance of link before applying local work from template.
=> LXL-3306 - Check for existance of a linked work before writing from the template

viewer/vue-client/src/components/inspector/reverse-relations.vue
enable reverseLinks.totalItems  for Work and Concept
Agent still uses o-query.
[LXL-3025](https://jira.kb.se/browse/LXL-3035)
use reverseLinks number in search results instead of o-query
use o-query for Work to reflect reverseLinks.totalItems
=> LXL-3035 - use reverseLinks

viewer/vue-client/src/components/inspector/item-local.vue, viewer/vue-client/src/components/inspector/item-sibling.vue
[LXL-3331](https://jira.kb.se/browse/LXL-3331)
Fixes the problem where property adders wouldn't be shown.
Removes an inaccurate condition for property adders
=> LXL-3331 - Remove incorrect condition on property adders

viewer/vue-client/src/views/Create.vue
[LXL-3335](https://jira.kb.se/browse/LXL-3335)
Base creation card should not be visible on create new Work page
added excludeBase property
=> excludeBase for Work

viewer/__init__.py, viewer/dataaccess.py
Make `@reverse` properties visible on id.kb.se
They will be shown as the acual relation, e.g. `@reverse/broader` will be displayed as narrower. 
Both in the html and data views. (Is this good or bad?)
[LXL-3291](https://jira.kb.se/browse/LXL-3291)
Make the python packend use `_applyInverseOf` when fetching data from backend. (https://github.com/libris/librisxl/pull/722)
=> Make reverse properties visible on id.kb.se

viewer/vue-client/src/components/inspector/entity-adder.vue
New resource does not render as chip until post is saved.
Caused by a ``null`` value being added to the ``currentValue`` array in ``addLinkedItem``.
[LXL-3356](https://jira.kb.se/browse/LXL-3356)
Added a null check to prevent a null value being added to the ``currentValue`` array.
=> LXL-3356-Newly added linked resource does not render as chip until post is saved.

viewer/vue-client/src/components/inspector/reverse-relations.vue
When showing contributions for an agent, both instance and work documents should be displayed.
In the bottom-right corner of the card and in the corresponding right-panel search.
[LXL-3305](https://jira.kb.se/browse/LXL-3305)
=> Search both contribution and instanceOf.contribution for agents

viewer/vue-client/src/components/search/facet-group.vue, viewer/vue-client/src/components/shared/entity-summary.vue, viewer/vue-client/src/components/shared/type-icon.vue, viewer/vue-client/src/resources/json/displayGroups.json, viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/utils/display.js
[LXL-3249](https://jira.kb.se/browse/LXL-3249)
Adds icons to Work-types. Also adds a basetype label (ie Work, Instance, Agent etc) in addition to their specific types (Electronic, Text, Person etc).
* Added `type-icon` component. Derived from the `encoding-level-icon`-component.
* Disabled getting type labels from display-utility and getting them in a specific way for the `entity-summary`-component instead. Getting them from display was always kind of a hack anyway.
=> LXL-3249 - Distinguish Work cards

viewer/vue-client/src/components/shared/modal-component.vue
Firefox v. > 76
Weird flickering when hovering buttons in detailed enrichment view.
[LXL-3354](https://jira.kb.se/browse/LXL-3354)
Removed ``overflow: hidden`` from ``modalComponent-container``.
Added ``overflow-x`` to  ``modalComponent-body`` instead.
It seems like this fix stops the flickering.
=> LXL-3354-bug fix, weird flickering in Firefox

serve.py
I tested this by generating the same warning in `serve.py` and it was filtered correctly.
=> Filter out warnings from rdfxml 'Assertions on rdflib.term.BNode...'

viewer/vue-client/src/components/search/facet.vue, viewer/vue-client/src/components/search/result-controls.vue, viewer/vue-client/src/store.js
Need to display proper labels for the newly added contribution facet
[LXL-3226](https://jira.kb.se/browse/LXL-3226)
Display correct labels for contribution facet
Added functionality to fetch label if object in a facet is Agent
Reordered facets
=> LXL-3226 - get labels for contribution facets

viewer/vue-client/src/components/mixins/item-mixin.vue
?
Copying a TEMPID into `derivedFrom` could potentially cause a lot of problems.
Check if the ID is TEMPID before copying it into `derivedFrom`
=> Don't copy ID into derivedFrom if ID is TEMPID

viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/views/Find.vue
Queries with leading wildcards need special handling in backend/ES. These queries might fail, e.g. `*foo "` fails because of unbalanced quotation marks. This change shows a specific error message in this case.
Side panel search is not changed. It shows "No results" on invalid queries.
[LXL-3364](https://jira.kb.se/browse/LXL-3364)
=> Handle HTTP 400 in Find, i.e. invalid queries.

viewer/__init__.py
[LXL-3435](https://jira.kb.se/browse/LXL-3435)
Error messages are no longer dropped when jetty response is mapped to flask response. 
See commit.
=> Include error message in CRUD api response

.gitignore, viewer/vue-client/src/components/inspector/entity-adder.vue, viewer/vue-client/src/components/inspector/param-select.vue, viewer/vue-client/src/components/inspector/search-window.vue, viewer/vue-client/src/components/search/result-controls.vue, viewer/vue-client/src/components/search/search-form.vue, viewer/vue-client/src/components/shared/filter-select.vue, viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/resources/json/propertymappings.json, viewer/vue-client/src/utils/http.js
Add a "field selection dropdown" to the right panel search. (Free text, Preferred label, ...)
Add a new option "Label" in the search "field selection dropdown" for Concept
The new option searches `prefLabel`, `altLabel`, `hasvariant.prefLabel`.
[LXL-3364](https://jira.kb.se/browse/LXL-3364)
[LXL-2586](https://jira.kb.se/browse/LXL-2586)
* Make it possible for a "property mapping" to specify multiple fields to be searched.
* Never display "up-link" for fields from the original query (only facets)
* Add option "Label" for Concept
* When clicking "Create/link" on a local entity, the type filter in the search panel has the same type as the local entity selected
* Right panel: Add a "field selection dropdown".
* Right panel: Don't wait 500ms to search after dropdown change (only wait after …
=> Add field dropdown to right panel search. Add search option 'Label'.

viewer/vue-client/src/utils/uriminter.js
All string properties are now trimmed by backend on save but it is frontend that mints id.kb.se URIs from e.g. prefLabel.
Make sure to not create URIs with leading or trailing `%20` in the last path component by trimming the user-supplied string.
[LXL-2551](https://jira.kb.se/browse/LXL-2551)
=> Fix: Don't mint main entity URIs with trailing spaces

viewer/vue-client/src/components/inspector/item-local.vue, viewer/vue-client/src/components/inspector/item-sibling.vue, viewer/vue-client/src/components/inspector/search-window.vue
Clicking "link" on an empty entity would result in an error which leads to
* the search input is not focused
* the correct type is not selected in the search pane
```
TypeError: this.itemInfo is null
--
resetSearch search-window.vue:301
show search-window.vue:274
```
[this is because item-info is set to null if item only contains `@type`](https://github.com/libris/lxlviewer/blob/b74fab2a55f0d5260240d2e2880212f9f9a6200d/viewer/vue-client/src/utils/data.js#L59)
[LXL-3447](https://jira.kb.se/browse/LXL-3447)
=> Fix type selected and input focus when linking empty item

viewer/vue-client/src/components/layout/global-msg.vue
dev/qa/stg indicator ("global-msg-corner") overlaps and blocks tool menu on narrow screens.
Move it to lower right corner instead of lower left.
=> Fix dev/qa/stg indicator blocking tool menu

viewer/vue-client/.editorconfig, viewer/vue-client/src/components/inspector/field.vue, viewer/vue-client/src/components/mixins/item-mixin.vue
Fixes "the document is missing a reference" error when a document is linking to itself.
* Fix error (datatype should be `entity` not `sibling`)
* Fix chip and link when link points to self (`item-mixin.vue`)
Example (record.inDataset): 
https://libris-dev.kb.se/katalogisering/nrb9xjzsq0rkbtnb
=> Fix error when document contains link to itself

viewer/vue-client/src/resources/json/combinedTemplates.json, viewer/vue-client/src/views/Inspector.vue
[LXL-3398](https://jira.kb.se/browse/LXL-3398)
Slightly faster workflow when breaking out works
- Add cataloguersNote to record in Work template
- If editing a Work with recordStatus marc:New, add an empty cataloguersNote property if one doesn't already exist (similar to the already existing `checkForMissingHeldBy()`)
=> Add cataloguersNote to template, and automatically when editing a new Work

viewer/vue-client/src/components/inspector/item-type.vue, viewer/vue-client/src/components/inspector/relations-list.vue, viewer/vue-client/src/components/inspector/reverse-relations.vue, viewer/vue-client/src/components/mixins/facet-mixin.vue, viewer/vue-client/src/components/search/facet.vue, viewer/vue-client/src/store.js, viewer/vue-client/src/utils/http.js
* Show all reverse links ("Used in"/"Används i") for all types. (except Item and Instance, still only holdings).
* Add a dropdown for filtering reverse links list by relation or type (using facets generated by backend).
Depends on: https://github.com/libris/librisxl/pull/854
[LXL-3105](https://jira.kb.se/browse/LXL-3105), [LXL-2355](https://jira.kb.se/browse/LXL-2355)
All relations were not visible before, e.g. only "contribution.agent" but not "subject" for Agents.
Make the reverse relations result list a little more navigable. It would be nice to be able to sort it but that requires a generic alphabetical sort that we don't have at the moment. (Sorting now requires knowledge of which type(s) the list contains.)
* Other changes
* Remove 1 second delay when we already have the reverse …
=> Always show all reverse links in card. Add filters for side panel reverse links view.

viewer/vue-client/src/components/inspector/relations-list.vue, viewer/vue-client/src/store.js
In the reverse relations panel, group "intereresting" facets and put them first in the dropdown
e.g.
```
<optgroup label="Relation">
<option>Medverkan eller primär medverkan (5k)</option>
<option>Ämne (2k)</option>
<option disabled="disabled">────────────────────</option>
<option>Supplement till/Medverkan och funktion/Agent (1)</option>
</optgroup>
```
instead of 
```
<optgroup label="Relation">
<option>Medverkan eller primär medverkan (5k)</option>
<option>Supplement till/Medverkan och funktion/Agent (1)</option>
<option>Ämne (2k)</option>
</optgroup>
```
[LXL-3105](https://jira.kb.se/browse/LXL-3105)
For entities with many incoming links: solves the issue where the most commonly used relations drown in the list of rare relations.
=> Group "interesting" facets in reverse relations filter

viewer/vue-client/src/components/inspector/entity-adder.vue, viewer/vue-client/src/components/inspector/field.vue, viewer/vue-client/src/components/inspector/item-entity.vue, viewer/vue-client/src/components/inspector/item-local.vue, viewer/vue-client/src/components/inspector/item-numeric.vue, viewer/vue-client/src/components/inspector/item-shelf-control-number.vue, viewer/vue-client/src/components/inspector/toolbar.vue, viewer/vue-client/src/components/mixins/item-mixin.vue, viewer/vue-client/src/components/mixins/lens-mixin.vue, viewer/vue-client/src/components/shared/entity-summary.vue, viewer/vue-client/src/components/shared/summary-node.vue, viewer/vue-client/src/models/user.js, viewer/vue-client/src/resources/json/combinedTemplates.json, viewer/vue-client/src/resources/json/displayGroups.json, viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/store.js, viewer/vue-client/src/utils/display.js, viewer/vue-client/src/utils/record.js, viewer/vue-client/src/utils/shelfmark.js, viewer/vue-client/src/utils/vocab.js, viewer/vue-client/src/views/Create.vue, viewer/vue-client/src/views/Inspector.vue
Add support for linked shelfMark with automatic generation of shelfControlNumber.
[LXL-3465](https://jira.kb.se/browse/LXL-3465)
* Allow linking for classes with category `distinct` (`https://id.kb.se/vocab/distinct`)
* Generate `shelfControlNumber` for each `Item` on save if it has a linked `shelfMark` with `nextShelfControlNumber`.
* Add a custom component `shelfControlNumber` which displays the option to generate it if applicable.
* Add template for ShelfMarkSequence (class name may change) in the new template section "Other".
* Limit entity-adder search to active ShelfMarks owned by current sigel
TODO:
* Restrict input `nextShelfControlNumber` to number. (restrict all `xsd:integer`)
* Disallow creating local entities for classes with category `distinct`
=> Linked shelfMark and automatic shelfControlNumber

viewer/vue-client/src/components/inspector/item-entity.vue, viewer/vue-client/src/components/inspector/item-grouped.vue, viewer/vue-client/src/components/inspector/item-local.vue, viewer/vue-client/src/components/inspector/item-sibling.vue, viewer/vue-client/src/store.js
* Add `defaultExpandedProperties` to settings. These properties/fields while be expanded from the start when opening a form.
* Add some default expanded properties
* `hasComponent`
* `@reverse/reproductionOf`
* `@reverse/supplementTo`
e.g. newly generated `hasComponent.shelfControlNumber` not being visible when saving an `Item`
=> Add settings.defaultExpandedProperties

viewer/vue-client/src/components/inspector/relations-list.vue
itemOf in card is useless if viewing incoming links for an Instance (since itemOf it will be the same Instance).
It is useful if viewing incoming links for other types.
=> Don't hide itemOf in relation side panel unless viewing Instance

viewer/vue-client/src/utils/shelfmark.js
Make sure to not try to write embellish data when bumping ShelfMarkSequence.nextShelfControlNumber (e.g. when Library data is loaded).
=> Fix: handle embellished ShelfMarkSequence

viewer/vue-client/src/resources/json/combinedTemplates.json
`identifiedBy` became an object instead of an array with one object which
backend chokes on for this specific property when creating a new doc (HTTP 500).
=> Fix not possible to save digital reproduction with single identifiedBy

viewer/vue-client/src/store.js
e.g. old links in templates that are now `sameAs`
=> Handle sameAs in fetchMissingLinkedToQuoted

viewer/vue-client/src/App.vue, viewer/vue-client/src/components/search/result-controls.vue, viewer/vue-client/src/resources/json/i18n.json
[LXL-2357](https://jira.kb.se/browse/LXL-2357)
Adds a button to add and remove `@reverse.heldBy.@id` filter
- Added button to result-controls
- Fixed focus-state for divs
- Added translations
=> LXL-2357 Add button to filter by heldBy for active sigel

viewer/vue-client/src/components/search/sort.vue, viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/store.js
[LXL-3508](https://jira.kb.se/browse/LXL-3508)
Previously it wasn't possible to sort results with agents or mixed types alphabetically. This was solved in the backend with two new fields, `_sortKeyByLang.sv` and `_sortKeyByLang.en`, that try to be approximately the same as what would be shown in the header in the UI. This simply makes use of these new fields when sorting.
* Concept, Common: use `_sortKeyByLang` instead of `prefLabel` 
* Agent, Other: add `_sortKeyByLang` (A-Z) sort option
`query` in `store.json` is `_sortKeyByLang`, but what actually needs to be sent to the server is `_sortKeyByLang.<lang>`, which depends on the user setting. Right now `user.settings.language` is simply appended in `sort.vue`, with a default of 'sv' if language isn't set. There might very well be a better …
=> Use _sortKeyByLang as sort option in Agent/Concept/All

viewer/vue-client/src/components/search/result-controls.vue
Get label for selected facet ("filter badge") from `mappings` instead of `stats`.
Depends on https://github.com/libris/librisxl/pull/894
=> Take filter badge label from mapping instead of stats

viewer/vue-client/src/components/search/result-controls.vue, viewer/vue-client/src/components/search/sort.vue, viewer/vue-client/src/components/shared/entity-summary.vue, viewer/vue-client/src/store.js, viewer/vue-client/src/utils/vocab.js
Make it possible to edit docs with mainEntity `@type` that is not a subclass of Item/Instance/Work/Agent/Concept. 
We probably want to rework some getRecordType use later.
[LXL-3531](https://jira.kb.se/browse/LXL-3531)
Used to get an exception on e.g. DataCatalog
Main change is in `getRecordType` in vocab.js. The others are just to make it work everywhere.
* `getRecordType` returns the type passed instead of 'Other' if not found among base classes.
* In top of cards: Only show "Unspecified" (e.g. "Unspecified, Work") for Work and Instance  
* Remove sort options for  "Other", use "Common".
=> Don't choke on types outside known class hierarchies

viewer/vue-client/src/components/inspector/entity-adder.vue, viewer/vue-client/src/components/inspector/modal-pagination.vue, viewer/vue-client/src/components/inspector/relations-list.vue, viewer/vue-client/src/components/inspector/search-window.vue, viewer/vue-client/src/components/mixins/sidesearch-mixin.vue, viewer/vue-client/src/components/search/result-controls.vue
Search result pagination links for first, prev, next and last are generated by backend but lxlviewer creates the numbered pages between first and last. Elasticsearch has a maximum number of results that can be accessed (now configured to 100k). This number is included in the search response as `maxItems`. Consider it when generating page links. 
i.e. don't show a link for page 5001 if `maxItems` is 100 000 and `_limit` is 20
[LXL-3588](https://jira.kb.se/browse/LXL-3588)
=> Search: respect maxItems when generating pagination links

viewer/vue-client/src/resources/json/combinedTemplates.json
Add ISNI as identifier type in template, remove typeNote "isni".
See https://github.com/libris/librisxl/pull/930
=> Add ISNI type in auth templates instead of typeNote

viewer/vue-client/src/utils/display.js
Group digits in ISNI and ORCID 
For example display "ISNI 0000 0001 2279 6052" instead of "ISNI 0000000122796052".
Only where `getItemLabel` is used e.g. in cards and non-expanded item-local. (see screenshot in [LXL-586](https://jira.kb.se/browse/LXL-586))
Backend normalizes them to the form without spaces. Search handles both forms.
There is no way to specify this type of formatting with fresnel so let's hardcode it.
[LXL-2422](https://jira.kb.se/browse/LXL-NNNN), [LXL-586](https://jira.kb.se/browse/LXL-586)
Makes ISNI and ORCID more readable.
=> Format ISNI and ORCID (nnnn nnnn nnnn nnnn)

viewer/__init__.py, viewer/templates/search.html
None (afaik), this was just a quick pre-sprint fix.
Currently the `_offset` form value for the _current_ search is included when performing a _new_ search, so if you're on page two of something, e.g.,
https://id.kb.se/find?q=*&_limit=200&inScheme.@id=https://id.kb.se/term/sao&inScheme.@id=https://id.kb.se/term/barn&inScheme.@id=https://id.kb.se/term/saogf&inScheme.@id=https://id.kb.se/marc&inScheme.@id=https://id.kb.se/term/gmgpc/swe&inScheme.@id=https://id.kb.se/term/barngf&inScheme.@id=https://id.kb.se/term/rda&_offset=200
...and then search for say "marsvin", the resulting page will say "Visar 201-6 av 6 träffar" and not actually show any results.
Similarly, if you're on [this](https://id.kb.se/find?_limit=200&inScheme.%40id=https%3A%2F%2Fid.kb.se%2Fterm%2Fsao&inScheme.%40id=https%3A%2F …
=> Don't set _offset for new searches

viewer/vue-client/src/components/search/sort.vue, viewer/vue-client/src/components/shared/notification.vue, viewer/vue-client/src/views/Inspector.vue
Give the user a chance to log in again if the session has expired when trying to save.
This is done by including a login link in the error message.
The link opens in an new tab, so the user has to login there and then come back to the editor tab. 
Basic solution. It would probably be nicer to stash the edited doc and do the login flow in the same tab.
[LXL-2865](https://jira.kb.se/browse/LXL-2865)
- Add `sticky` mode to notifications. No timeout, only closes on click.
- Add links to notifications.
- Include login link in error notification for 401 on save
=> Display link to login if login expired while editing

viewer/vue-client/src/components/usersettings/select-sigel.vue
[LXL-3552](https://jira.kb.se/browse/LXL-3552)
In the sigel selector, sigels were not in alphabetical order.
Sigels are now in alphabetical order (the displayed label - "Library name - SIGEL" - is used for sorting).
=> Sort sigels in sigel select alphabetically

viewer/vue-client/src/resources/json/baseTemplates.json, viewer/vue-client/src/resources/json/combinedTemplates.json
[LXL-2649](https://jira.kb.se/browse/LXL-2469)
Removes bibliography as b-nodes in favor of empty set for linking.
=> Remove bibliography b-nodes from templates

viewer/vue-client/src/components/care/holding-list.vue
Now that we have library names available, sorting the holding list in directory care on `@id` (library URI) gives the wrong order.
It should be sorted on what is displayed in the card heading (library name).
[LXL-3617](https://jira.kb.se/browse/LXL-3617)
=> Sort directory care holding list by card heading, not id/sigel

viewer/vue-client/src/utils/record.js
Data is leaking between different invocations of "Create digital reproduction".
Steps to reproduce:
* Click on "Create digital reproduction" on an instance with `responsibilityStatement`
* Click on "Create digital reproduction" on an instance without `responsibilityStatement`
* `responsibilityStatement` from the first instance will appear in the reproduction
[LXL-3480](https://jira.kb.se/browse/LXL-3480)
=> Fix ghost data in 'create digital reproduction'

viewer/vue-client/src/utils/display.js
- Extended lens should be looked up via `@id`
- Same inheritance behavior when mocking display
- Remove duplicate lens inheritance code
Lenses specified in `fresnel:extends` should be looked up via `@id`, not by splitting the `@id` string into lens group and key.
The old code crashes on this display file ("SummaryType-chips" != "marc:SummaryType-chips").
```
"chips": {
"@id": "chips",
"@type": "fresnel:Group",
"lenses": {
...
"marc:SummaryType": {
"@id": "SummaryType-chips",
"@type": "fresnel:Lens",
"classLensDomain": "marc:SummaryType",
"showProperties": [ "label" ]
},
...
"cards": {
"@id": "cards",
"@type": "fresnel:Group",
"lenses": {
...
"marc:SummaryType": {
"@id": "SummaryType-cards",
"@type": "fresnel:Lens",
"fresnel:extends": {"@id": "SummaryType-chips"},
"showProperties": [ …
```
=> Fix lens inheritance

viewer/vue-client/src/components/inspector/entity-adder.vue
Fix regresion:
ShelfMarkSequences that are inactive and owned by other libraries are
visible in the list when linking shelfMark. Because search parameters
are never set.
[LXL-3628](https://jira.kb.se/browse/LXL-3628)
=> Fix bad shelfMarkSequences visible when linking

viewer/vue-client/src/components/usersettings/select-sigel.vue
Fix sigel not visible in selector for very long library names
See screenshot of fix in issue.
[LXL-3633](https://jira.kb.se/browse/LXL-3633)
Do ellipsis on library name ("friendly_name") instead of on whole label.
Still the same max length, 50 chars.
=> Fix sigel not visible in selector for long library names

vue-client/src/resources/json/combinedTemplates.json, vue-client/src/utils/record.js
Change "create digital reproduction" maneuver to use the new simplified form for digital reproductions.
TODO: extract and link work
[LXL-3673](https://jira.kb.se/browse/LXL-3673), [LXL-LXL-2807](https://jira.kb.se/browse/LXL-LXL-2807)
* Update template
* Only copy title from physical
=> Update 'create digital reproduction' to new practice

vue-client/src/components/inspector/reverse-relations.vue
It should be "used in"
[LXL-3792](https://jira.kb.se/browse/LXL-3792)
Item card show number of items linking to linked instance. 
It should show number of links to item (even though there will rarely be any)
=> Fix reverse relation button showing # items for item

vue-client/src/components/inspector/create-item-button.vue, vue-client/vue.config.js
[LXL-3863](https://jira.kb.se/browse/LXL-3863)
The sigel "No" would accidentally be translated to "Nej", because e.g. "No" and "has holding" were passed individually to the translation method, which then looked up and found "No" in the i18n file.
Don't pass the sigel to the translation method. Also covers translation of aria-label (in this case it passes label to rounded-button, which then runs the label through translatePhrase; but since we now pre-translate the string, translatePhrase (actually StringUtil.getUiPhraseByLang) doesn't find it in i18n.json and so returns it untouched. Seemed like the least messy solution)
=> Don't accidentally translate sigel; fix lint error

lxljs/display.js, vue-client/src/components/inspector/field.vue
* Sort properties correctly in for
* Type coercion in JSON-LD context (`langCodeFull` -> `code`+`ISO-639-3` should be placed where `code` is)
* e.g. language containers `prefLabelByLang`
* `alternateProperties`
* Show label of type for fields with type coercion (`langCodeFull` -> `ISO-639-3` instead of "Code")
=> Display type coeced properties correctly

vue-client/src/components/inspector/item-local.vue, vue-client/src/components/inspector/item-sibling.vue
Affected "Add property" and "Create/link" panels.
[LXL-3775](https://jira.kb.se/browse/LXL-3775)
=> Fix side panel still open after user saved/cancelled editing

vue-client/src/components/inspector/entity-form.vue, vue-client/src/components/inspector/field.vue, vue-client/src/components/inspector/item-entity.vue, vue-client/src/components/inspector/item-grouped.vue
For example instanceOf, translationOf
Including reverse integral properties, e.g. `@reverse/instanceOf`
The cards could be sorted in a better way, for example publication.year
for instances of a work. Define that mechanism later.
[LXL-3864](https://jira.kb.se/browse/LXL-3864)
- Makes instances of a work distinguishable by displaying them as cards instead of chips.
- Makes e.g. reproductions nicer by displaying the integral `reproductionOf` as a card
- Separate the concept of "distinguished" (i.e. displaying the work as a separate section) from being displayed as a card
- Display all "integral" properties as cards
- Auto-expand all cards
- Maybe fields should decide themselves if they should be cards instead of passing it from entity-form?
=> Display integral properties as cards inside form

nuxt-app/layouts/error.vue, nuxt-app/resources/json/i18n.json
[LXL-3887](https://jira.kb.se/browse/LXL-3887)
Error pages (e.g. 500) should not expose internal details to visitors and shouldn't use technical jargon.
Clear headings (e.g. "There is a problem with the service" rather than "500"), possibility to have additional (and translatable) information, proper <title> (e.g. "Page not found | id.kb.se" rather than "id.kb.se").
=> Make error pages more user-friendly

vue-client/src/resources/json/i18n.json, vue-client/src/views/Inspector.vue
[LXL-2078](https://jira.kb.se/browse/LXL-2078)
"Something went wrong" is not a useful error when trying to save a holding that already exists for the current sigel.
Adds a human-friendly error message if status 409 is encountered when saving.
=> Better error message when holding already exists

nuxt-app/modules/vocab-cache.js, nuxt-app/nuxt.config.js, nuxt-app/store/index.js
Only fetch vocab resources once in nuxt-app and not for every (server-side rendered) request.
A further improvement would to refactor VocabUtil so that more of the preprocessing that is now done in e.g. SET_VOCAB_PROPERTIES could be done when fetching vocab.
=> Cache vocab resources in nuxt-app

lxljs/vocab.js, nuxt-app/components/EntityNode.vue, nuxt-app/modules/vocab-cache.js, nuxt-app/resources/json/rdfTranslations.json, nuxt-app/store/index.js
Done by preprocessing the vocab data upon initial fetch.
Needs more testing:
=> Show subclasses and -properties in the vocab view

vue-client/src/components/inspector/entity-adder.vue, vue-client/src/components/inspector/field.vue, vue-client/src/store.js, vue-client/src/views/Inspector.vue
In language tagging side panel:
* Prepopulate search field with label of language of resource
* (for now instanceOf.language)
* If search field is modified, prepopulate with same value next time
=> Prepopulate language tagging side panel

nuxt-app/nuxt.config.js
- [ x] I have run unit tests. `yarn test`
Noticed a regression currently present on id-dev.kb.se (after moving all source to src/).
Console log says: "[Error] env.XL_SITE_CONFIG not defined (fix for development: copy .env.in to .env)"
By pointing out location of .env the problem seems to be fixed.
=> fix .env file location

nuxt-app/nuxt.config.js, nuxt-app/src/components/EntityTable.vue, nuxt-app/src/components/NavMenu.vue, nuxt-app/src/components/Navbar.vue, nuxt-app/src/components/SearchBar.vue, nuxt-app/src/layouts/default.vue, nuxt-app/src/layouts/libris.vue, nuxt-app/src/mixins/lxl.js, nuxt-app/src/modules/vocab-cache.js, nuxt-app/src/pages/_.vue, nuxt-app/src/pages/doc/_article.vue, nuxt-app/src/pages/find/index.vue, nuxt-app/src/pages/index.vue, nuxt-app/src/plugins/env.js, nuxt-app/src/plugins/envInjects.js, nuxt-app/src/plugins/filters.js, nuxt-app/src/store/index.js
- [x ] I have run the unit tests. `yarn test`
*DEPENDS ON:* https://github.com/libris/devops/pull/154
[LXL-3956](https://jira.kb.se/browse/LXL-3956)
Moved build-time state from env.js. Instead inject functions and make use of publicRuntimeConfig, which can be retrieved in different ways depending of the context.
=> Make it possible to inject env variables at runtime

vue-client/src/components/inspector/version-history.vue
Makes sure no duplicate data is displayed in history view when e.g. one genre is added and others already exists.
[LXL-3991](https://jira.kb.se/browse/LXL-3991)
=> Check for conflicting ids before adding to path object in version-history

vue-client/src/components/inspector/field.vue, vue-client/src/components/inspector/item-bylang.vue, vue-client/src/components/inspector/item-local.vue, vue-client/src/components/inspector/language-entry.vue, vue-client/src/components/mixins/language-mixin.vue
Newly added text input fields should be focused.
Still not working:
- highlighting
[LXL-4076](https://jira.kb.se/browse/LXL-4076)
Input fields for properties that can be language tagged did not get their focus set.
Works in the same way as all other item-foo controls
=> Fix set focus for newly added lang-tagged fields

vue-client/public/index.html
VUE_APP_VERSION contains the git tag, set via vue.config.js and injected in dist/index.html at build time. The index file has no cache set by the server, but we use this pattern since most of the built files have similar (albeit hash-based) cache-busting URL:s.
Risk of using browser-cached and stale runtime config.
Add GET-parameter with app version (ignored by apache but considered as a different URL by browsers).
=> Cache bust runtimeConfig.js using app version

vue-client/src/components/inspector/version-history.vue
[LXL-4079](https://jira.kb.se/browse/LXL-4079)
The back button in the history view navigates the user back to the previous page visited. This is a problem when going to the history view by directly specifying the path with `/history`.
The back-button always leads back to the record to which the history is associated.
=> Back button -> navigate to record

vue-client/src/components/layout/footer.vue, vue-client/src/resources/json/copy.json, vue-client/src/views/LandingPage.vue
It is not possible to embed the whole playlist on KB Play, only individual videos. So I removed that part from the card.
Landing page is now one row with three cards and one row with one card of the same size.
I have not ripped out all the youtube embedding code in `link-card.vue`
[LXL-4096](https://jira.kb.se/browse/LXL-4096)
=> Change instruction video links from youtube to KB Play

vue-client/src/components/inspector/field.vue, vue-client/src/components/inspector/item-local.vue, vue-client/src/components/inspector/language-entry.vue, vue-client/src/components/inspector/version-history.vue, vue-client/src/components/mixins/item-mixin.vue, vue-client/src/utils/history.js, vue-client/tests/unit/HistoryUtil.spec.js
Using the improved diffs from backend, simplify the diff display code.
Depends on https://github.com/libris/librisxl/pull/1235
[LXL-4065](https://jira.kb.se/browse/LXL-4065)
Version history is displayed correctly.
* Move calculation of display data and diff paths to a plain js file
* Add unit tests
* Fix path handling, e.g. remove the new `myPath`
=> Fix version history

lxljs/vocab.js, nuxt-app/src/components/EntityTable.vue, nuxt-app/src/components/PropertyRow.vue, nuxt-app/src/resources/json/rdfTranslations.json
[LXL-3723](https://jira.kb.se/browse/LXL-LXL-3723),
Shows properties on classes which references the class using the following: `domain`, `domainIncludes`, `range` and `rangeIncludes`.
This pull request replaces [#867](https://github.com/libris/lxlviewer/pull/867) (which has been reverted).
- We now populate the class objects in one place (`preprocessVocab`) and add the properties inside `@reverse` instead of directly on the class. This prevents code duplication and also solves the issue with duplicate subClasses.
- We now skip the conversion of `vocabClasses` and `vocabProperties` to Maps (to reduce the scope of the PR).
- Sorting of property values are also added.
=> Feature/lxl 3723 show domain and range includes (using @reverse)

vue-client/src/components/inspector/search-window.vue
[LXL-4161](https://jira.kb.se/browse/LXL-4161)
Removes placeholder (e.g. `{Primär medverkan utan agent}` or `{PrimaryContribution without agent}`) from work search string.
- Remove placeholder from work search string
- Trim search string
- Find and replace phrase in all languages found in `availableUserSettings`
=> Feature/lxl-4161 Remove placeholder from work search string

vue-client/src/components/inspector/search-window.vue
[LXL-4161](https://jira.kb.se/browse/LXL-4161)
Escapes regex variables to prevent blow ups (e.g. if they contain unbalanced parens).
- Escape regex variable
=> Feature/lxl-4161 Escape regex variable

lxljs/display.js
[LXL-4055](https://jira.kb.se/browse/LXL-4055)
Removes the leftover transliteration separator if `transliteratedKeys` is empty.
- Only show separator if there are transliterations
- Change the transliteration separator character as the previous character could be rendered differently on different devices.
=> Fix/lxl-4055 Only show separator if there are transliterations

vue-client/src/components/inspector/field.vue, vue-client/src/components/inspector/item-bylang.vue, vue-client/src/components/inspector/language-entry.vue
[LXL-4078](https://jira.kb.se/browse/LXL-4078)
Text areas with more than one line of text don't properly resize when starting to edit a property that is not expanded. 
Listen to changes of isExpanded in language-entry.vue
=> Fix-autosize-of-textarea-for-language-taggable-properties

vue-client/src/components/inspector/item-bylang.vue
[LXL-4074](https://jira.kb.se/browse/LXL-4074)
Fixes a bug where unstyled empty labels show up when saving records with empty language taggable fields, as described in [LXL-4074](https://jira.kb.se/browse/LXL-4074). 
* Don't save to inspector.data, while editing, if field content is empty. 
* Added extra isLocked-check so that nothing can be saved be mistake when the user is out of edit mode. This possibly solves some of the issues described in the comments of [LXL-4074](https://jira.kb.se/browse/LXL-4074) --- however, I was unable to reproduce those issues locally.
=> Don't save empty fields to inspector.data

vue-client/src/components/shared/summary-node.vue
[LXL-4162](https://jira.kb.se/browse/LXL-4162)
Show type on linked items and replace colon with bullet character
- Show type on linked items and replace colon with bullet
=> Feature/lxl-4162 Show type on linked items and replace colon with bullet

vue-client/src/components/shared/entity-summary.vue
Fixes occasional multiple expand errors when hammering clicks on a summary element
[LXL-4176](https://jira.kb.se/browse/LXL-4176)
Sometimes multiple expand icons could appear when hammering clicks on a summary element.
See screenshot of problem: 
- Set `handle-overflow` to false on nested summary nodes.
- Change order of event modifiers (see note on https://v2.vuejs.org/v2/guide/events.html#Event-Modifiers).
=> Prevent occasional multiple expand arrows

nuxt-app/src/pages/marcframe.vue, nuxt-app/src/pages/marcframe/index.vue
Get marcframe.json (expanded) from system and not from github.
Depends on https://github.com/libris/devops/commit/69675957dfc60a5cdc1bed5ec00e3360067b6efe
[LXL-4103](https://jira.kb.se/browse/LXL-4103)
Marcframe view was broken for auth and hold.
=> Fix marcframe display for auth och hold

nuxt-app/src/layouts/error.vue, nuxt-app/src/resources/json/i18n.json
[LXL-4250](https://jira.kb.se/browse/LXL-4250)
Previously the formal page of a deleted resource would have the correct HTTP status code but show the generic error "There is a problem with the service. Try again later." (example: https://libris.kb.se/tz4ttnm0251wshd#it). This adds a special case for 410 Gone (like in the cataloging client).
=> Fix 410 Gone message on id.kb.se

vue-client/src/components/inspector/item-bylang.vue
[LXL-4080](https://jira.kb.se/browse/LXL-4080), [LXL-4074](https://jira.kb.se/browse/LXL-4074)
The bug in [LXL-4080](https://jira.kb.se/browse/LXL-4080) where the input in a field jumps back again after being cut (if the resulting input is `""`). 
Don't exclude empty input when syncing inspector.data in item-bylang.vue.
=> Don't exclude empty input when syncing inspector.data

vue-client/src/utils/record.js
Parts of the MARC preview were sometimes missing in unsaved records. 
Because MARC conversion was done on the record + "quoted" which was sometimes incomplete
instead of on a freshly embellished copy of the record.
(I'm not sure this is still a problem since we fetch all links in templates to quoted nowadays.)
Embellish is already performed on the server side so no need to send quoted/embellished data. 
Embellish on the server side failed when passed already embellished data.
TODO: make backend embellish or at least MARC `/_convert` handle embellished data.
[LXL-2476](https://jira.kb.se/browse/LXL-2476)
Only send the record being edited to `/_convert`.
=> Fix MARC preview for unsaved records

vue-client/src/components/shared/summary-node.vue
[LXL-4162](https://jira.kb.se/browse/LXL-4162)
Duplicate of closed PR #888, now with `develop` as base instead of `1.32.0`.
Show type of linked item in single/full view. Reads the type from `focusData` instead of `item`
- Show type of linked item in single/full view
Single view:
List view:
=> Lxl 4162 show type on linked item in single view

vue-client/src/utils/uriminter.js
[LXL-3643](https://jira.kb.se/browse/LXL-3643)
The UI will handle most values as arrays as often as it can, but limiting them to a length of 1 if the property only takes one value. `uriminter` wasn't able to handle this before this change.
* Make uriminter able to handle relations being in arrays
=> lxl 3643 inScheme as array

lxljs/display.js
[LXL-4265](https://jira.kb.se/browse/LXL-4265)
When showing linked vocabulary terms, the label available in the vocab data is not used, and a generic "leaf from URI" fallback is used.
Use vocab term object in  `getDisplayObject` if available. Otherwise show full URI (to clearly show that no label for the term is available).
=> Use vocab term object for display if available

vue-client/src/components/mixins/sidesearch-mixin.vue
[LXL-2513](https://jira.kb.se/browse/LXL-2513)
Rewrites comma-separated typeArray as multiple urlSearchParam keys.
- Rewrite typeArray param as multiple keys
=> Rewrite typeArray param as multiple keys

vue-client/src/components/mixins/sidesearch-mixin.vue
[LXL-2513](https://jira.kb.se/browse/LXL-2513)
Uses the append method from the `URLSearchParams` interface for  `this.currentSearchParam.mappings` and `this.currentSearchParam.searchProps`. This allows multiple keys of the same type and replicates the functionality of the old [buildQueryString](https://github.com/libris/lxlviewer/blob/460884c8cb867e357718b15632233974ce31ee0c/vue-client/src/utils/http.js#L4-L19)-method.
Related PRs: #893 (where the `URLSearchParams` interface was introduced) and #899.
- Append search props and mappings into URLSearchParams
=> Append searchProps and mappings into URLSearchParams

vue-client/src/store.js
[LXL-4190](https://jira.kb.se/browse/LXL-4190)
Fixes undo history when extracting items.
The `changeHistory` state currently relies on implicit changes on the values of an item, this causes problems when waiting with extracting items until save as there shouldn't be any changes other than updating the id (which doesn't exist yet as it hasn't been extracted yet)...
So we need a work-around: the `changeList` payload is replaced with a constant (`EXTRACT_ON_SAVE`) indicating that the item should be extracted on save – this constant acts as an opt-out for the normal `changeList` functionality (it skips setting the inspector data with new values).
When cancelling an extraction the related `changeHistory` item is removed (even if it isn't the latest change).
- Fix undo history when extracting …
=> Fix undo history when extracting items

vue-client/src/components/mixins/sidesearch-mixin.vue
Falsy options were coerced to the string `false`, resulting in a truthy value. In vue3 `null` or `undefined` should be used to explictly remove an attribute. See https://v3-migration.vuejs.org/breaking-changes/attribute-coercion.html#coercing-false-to-false-instead-of-removing-the-attribute
[LXL-4339](https://jira.kb.se/browse/LXL-4339)
Fix creation of local entities
Fix creation of local entities by using `null` instead of `false` inside the `selectOptions` method inside `sidesearch-mixin.vue`
=> Fix creation of local entities

vue-client/src/components/inspector/item-entity.vue, vue-client/src/components/inspector/language-entry.vue, vue-client/src/components/inspector/version-history-changesets.vue, vue-client/src/components/shared/summary-node.vue, vue-client/src/main.js
[LXL-4340](https://jira.kb.se/browse/LXL-4340)
Fix chip hover bug
Uses Menu component from `floating-vue` instead of Dropdown. See https://floating-vue.starpad.dev/guide/component#hover-menu
=> Fix chip hover bug

vue-client/src/components/inspector/item-bylang.vue, vue-client/src/components/inspector/item-local.vue, vue-client/src/components/inspector/language-entry.vue, vue-client/src/components/search/search-form.vue, vue-client/src/store.js
[LXL-4341](https://jira.kb.se/browse/LXL-4341)
Fixar bugg där ett fält man tagit bort dyker upp igen. Beskrivning finns i ticket.
Anledningen till buggen (som uppstod efter vue3-migreringen av någon anledning) är att 
watchern för `fieldOtherValue` i item-bylang triggas efter borttagningen. Denna sätter igång en kedja anrop (`updateviewform()` -> `entries` -> `update()` -> `updateInspectorData`) som slutar med att det gamla värdet skrivs tillbaks igen. Nu uppdaterar vi enbart om det nya värdet skiljer sig från det gamla (precis som i watchern för `fieldValue`).
övriga ändringar:
* Kolla att `$refs.fieldAdder` finns (det gör den inte) innan vi gör saker med den, förhindrar `referenceError`
* `update:modelValue` --> `update:model-value` (vue 3 gillar kebab-case på events)
* linting
=> LXL-4341: Fix remove item bug

vue-client/src/components/inspector/entity-adder.vue, vue-client/src/components/inspector/field.vue, vue-client/src/components/inspector/item-local.vue, vue-client/src/components/inspector/item-next-shelf-control-number.vue, vue-client/src/components/inspector/item-numeric.vue, vue-client/src/components/inspector/item-sibling.vue, vue-client/src/components/inspector/item-value.vue
[LXL-4383](https://jira.kb.se/browse/LXL-4383)
Weird bug that causes some input fields (`item-value`) to revert to their previous value on mouseleave.
reproduce:
* create new --> 'agent' --> 'person'
* put the cursor in 'födelsedatum' and type something. Move the cursor to 'dödsdatum'. The text then disappears and re-appears after 1 sec.
Moving the cursor from the field causes the component to update (in Vue 2, it did not apparently) resetting to the prop value. But since the update function has a 1s debouncer, the current text has not yet been synced back from the store, causing the old value to be displayed for a short while.
the `@mouseover`/ `@mouseleave` in `field` is what causes the update in (some of!) the components. This is used for the `showActionButton` functionality that has …
=> LXL-4383: item-value update bug

vue-client/src/store.js
[LXL-4297](https://jira.kb.se/browse/LXL-4297)
Copies `marc:nonfilingChars` to extracted `hasTitle` if present in main entity.
- Copy marc:nonfilingChars when extracting
=> Copy marc:nonfilingChars when extracting

vue-client/src/router.js, vue-client/src/views/Login.vue
[LXL-4384](https://jira.kb.se/browse/LXL-4384)
User being redirected to startpage (/) instead of last path after login.
The place where we save the `lastPath` was embedded in a condition where the `to` path had to `requireAuth` (/user, /create etc). This makes no sense to me, and I'm curious how this worked in the past.
Now we do separate checks; if the user is not authed we save the last path, and if they're headed for a protected route we send them to login/expired. Also, after login, we route them back to the full path (incl params for search results), not only the path.
=> LXL-4384: Fix login lastPath

vue-client/src/components/inspector/item-local.vue
Ensures the highlight is removed when undoing extraction actions (sometimes the blue highlight could be stuck which could confuse the user if the item will be extracted or not).
- Ensure highlight is removed when undoing extraction
=> Ensure highlight is removed when undoing extraction

vue-client/src/components/inspector/entity-adder.vue, vue-client/src/components/inspector/search-window.vue, vue-client/src/components/mixins/sidesearch-mixin.vue
[LXL-4404](https://jira.kb.se/browse/LXL-4404)
Inactive ShelfMarkSequences and ShelfMarkSequences owned by other libraries showing up when linking shelfMark.
The inactive ones should also have been blocked from linking by the client because they are `replacedBy` the new ones. But  `replacedBy` is not indexed (not in card for `ShelfMarkSequence`).
Moved the check to where params are built now.
b9705205 was the breaking change. `getSearchPhrase` is not called anymore
=> Fix inactive ShelfMarkSequences showing up in entity adder

vue-client/src/utils/data.js
When opening a document we try to lookup all links not in quoted / embellish data.
This is useful when opening a template where we don't have the definitions for the linked things in the template loaded.
However, we shouldn't try to lookup URIs outside libris.kb.se / id.kb.se.
Only `fetchMissingLinkedToQuoted` for links within system.
`fetchMissingLinkedToQuoted` trying to lookup things outside libris.kb.se / id.kb.se
=> Only fetchMissingLinkedToQuoted for links within system

vue-client/src/components/inspector/entity-adder.vue
[LXL-4419](https://jira.kb.se/browse/LXL-4419)
See commit message.
Add check for repeatability of property key when linking things.
=> Fix relinking of work turns instanceOf to an array

vue-client/src/components/inspector/item-error.vue
[LXL-4421](https://jira.kb.se/browse/LXL-4421)
Fixes issue causing Vue to slow down or crash due to `Maximum recursive updates exceeded in component` while in debug mode. The `item-error.vue` component automatically dispatched unwanted `setValidation` actions in debug mode, resulting in a loop as the actions triggered new errors.
The code removed is five years old so the issue shouldn't be related to the Vue3 migration (but maybe Vue2 has a different escape hatch for recursive loops? 🤷)
- Remove loop causing item-error to dispatch new errors
=> LXL-4421: Remove loop causing item-error to dispatch new errors

vue-client/src/components/inspector/field.vue
[LXL-4422](https://jira.kb.se/browse/LXL-4422)
- Fixes as bug where newly input text was removed (after a short delay) when adding a new field.
Remove unspecified parameter/property on initialization of item-value.vue, item-shelf-control-number.vue and item-next-shelf-control-number.vue. The parameter is already specified as a computed in the components, not a property.
=> Fix LXL-4422 bug

lxl-web/.vscode/extensions.json, lxl-web/.vscode/lxl-web.code-workspace, lxl-web/.vscode/settings.json
Add VS Code workspace for lxl-web allowing worskpace specfic settings
- Add VS Code workspace for lxl-web 
- Add workspace specific quality-of-life settings
=> Add VS Code workspace for lxl-web with included settings

lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.server.ts, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/search/+page.server.ts, lxl-web/src/routes/(app)/[[lang=lang]]/search/+page.svelte
Removes redundant page type annotations (e.g. `PageData` and `PageServerLoad` which no longer are needed. See https://svelte.dev/blog/zero-config-type-safety
- Remove redundant page type annotations
=> Remove redundant page type annotations

lxl-web/src/app.d.ts, lxl-web/src/app.html, lxl-web/src/hooks.server.ts, lxl-web/src/lib/components/LangPicker.svelte, lxl-web/src/lib/components/Search.svelte, lxl-web/src/lib/i18n/index.ts, lxl-web/src/lib/i18n/interpolate.test.ts, lxl-web/src/lib/i18n/interpolate.ts, lxl-web/src/lib/i18n/locales.ts, lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/routes/(app)/+layout.ts, lxl-web/src/routes/(app)/[[lang=lang]]/+layout.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/search/+page.server.ts, lxl-web/src/routes/(app)/[[lang=lang]]/search/+page.svelte, lxl-web/svelte.config.js
[LXL-4362](https://jira.kb.se/browse/LXL-4362)
A modest proposal on how we could approach the i18n issue. Svelte has [no official solution](https://github.com/sveltejs/kit/issues/553), and after looking at a number of libs, many seem [too large](https://github.com/opral/monorepo/tree/main/inlang), [hacky](https://github.com/kaisermann/svelte-i18n) or [abandoned](https://github.com/ivanhofer/typesafe-i18n). 
I then found [this example](https://poly-i18n.vercel.app/en/kitbook) that felt like a good approach and decided to try it out. It's basically a function that loads the needed translations and returns a translator function from the layout. It supports nested translation files and basic string interpolation (`hello {name} how are you`) and can easily be extended to support our exact …
=> Add basic i18n support

lxl-web/lxl-web.code-workspace
After moving the workspace file we also need to change the relative path from parent dir to current
(we vant `lxl-web` and `lxljs`, not `lxlviewer` and `lxljs`).
=> Change path in VS Code workspace file

vue-client/src/components/mixins/form-mixin.vue
When viewing a `Work` record, linked `Instance`s appear in random order. Sort them on publication year, descending.
[LXL-4432](https://jira.kb.se/browse/LXL-4432)
For now, just hardcode the relation (`@reverse.instanceOf`) and sort key.
We might want to solve this in a more general way later. e.g. a table view based on card properties with sorting on any column.
=> Sort Work hasInstance on publication.year

lxl-web/src/app.css, lxl-web/src/lib/components/DecoratedData.svelte, lxl-web/src/lib/utils/resourceData.ts, lxl-web/src/routes/(app)/[[lang=lang]]/find/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/find/FacetGroup.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/find/FacetSidebar.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/find/SeachMapping.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/find/SearchCard.svelte
[LWS-23](https://jira.kb.se/browse/LWS-23)
* Displays data from the search result somewhat more readable
* Each search result `item` is passed to new component `SearchCard` that formats it for this specific use case:
* prints the top-level `_label`
* adds top-level `_style` classes (applied to the entire group)
* adds a wrapper element to each prop entry to keep them grouped
* property sorting with grid `template-areas`
=> Search cards

vue-client/src/views/Inspector.vue
It is obsolete as long as we don't enable automatic `ChangeObservation`s
[LXL-4454](https://jira.kb.se/browse/LXL-4454)
=> Don't add an empty change note in adminmetadata

vue-client/src/router.js
Fixes a bug where the CXZ message search results turns empty when clicking Directory Care / Katalogvård. 
See more in [LXL-4444](https://jira.kb.se/browse/LXL-4444).
=> Don't drop query part when navigating within CXZ message view

lxl-web/src/lib/types/API.ts, lxl-web/src/routes/(app)/[[lang=lang]]/find/+page.server.ts, lxl-web/src/routes/(app)/[[lang=lang]]/find/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/find/FacetSidebar.svelte
[LWS-56](https://jira.kb.se/browse/LWS-56)
* Adds a `select` element with 3 options (for now, more will be added) that sort the current search result
* Display the number of `totalItems` / no hits
Extra:
* Added very basic error handling to `find/page.server` (I noticed that 'hacking' the `_sort` param caused the app to crash since we never check if the fetch was successful before trying to run xl methods on the response)
* Only show the filter panel if there are hits
=> Result sorting

lxl-web/src/lib/components/DecoratedData.svelte, lxl-web/src/lib/utils/addDefaultSearchParams.test.ts, lxl-web/src/lib/utils/addDefaultSearchParams.ts, lxl-web/src/lib/utils/http.test.ts, lxl-web/src/lib/utils/http.ts, lxl-web/src/routes/(app)/[[lang=lang]]/find/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/find/FacetGroup.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/find/Pagination.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/find/SearchCard.svelte
[LWS-24](https://jira.kb.se/browse/LWS-24)
* Adds a component that allows the user to paginate the search result
* The pagination includes outer (conditionally displayed prev/next, first/last) navigations and an inner sequence of pages (currently 2) in relation to the current page.
* We want to reset the `_offset` on new search (?), so the `addDefaultSearchParam` condition is reversed; reset if it exists, else omit it (defaulting to 0)
* Renamed http util `relativize` -> `relativizeUrl` and extended it to accept relative url:s - removing its opening slash to keep the /lang/ href. Applied to pagination as well as facets.
* Added and updated tests
=> Search result pagination

lxl-web/src/lib/components/DecoratedData.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/find/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/find/SeachMapping.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/find/SearchCard.svelte
Use the new `block` and `showLabels` props on searchcards and mappings to reduce code and make everything look normal again.
=> Use new decorated functionality on seach cards & mapping

lxl-web/src/hooks.server.ts, lxl-web/src/lib/assets/json/display-web.json, lxl-web/src/lib/utils/xl.ts
[LWS-59](https://jira.kb.se/browse/LWS-59)
Breaks out lxl-web lens and formatting into a local file for easier management
To be tested together with https://github.com/libris/definitions/pull/473
* Create display-web.json
* Merge contents with display on load
* Fix so that app doesn't break if display-web is empty, for example
=> Break out web stuff from display

lxl-web/src/colors.css, lxl-web/src/lib/actions/resourcePopover/index.ts, lxl-web/src/lib/assets/json/display-web.json, lxl-web/src/lib/components/DecoratedData.svelte, lxl-web/src/lib/utils/display.types.ts, lxl-web/src/lib/utils/xl.ts, lxl-web/src/routes/(app)/[[lang=lang]]/SiteHeader.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/find/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/find/SeachMapping.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/find/SearchCard.svelte, lxl-web/tailwind.config.js
[LWS-22](https://jira.kb.se/browse/LWS-22)
Iteration of search card given the design:
(minus year, checkbox, description, right side buttons)
* Created a new `web-card` lens that exclude many of the base card properties
* Rework the `SearchCard` component to support alternate renderings (`hasInstance`)
* New `truncate` option to `DecoratedData` that renders the first item and indicates the remainder (+ x). Not happy to grow it further, other suggestions how to achieve this are welcome :)
* New option to pass `data` directly to popover instead of fetching with id. Used here to show the remainder data (+ x) on hover. 
* Updated styles (typography variants)
=> Rework search card w. new lens

lxl-web/src/lib/assets/json/display-web.json, lxl-web/src/routes/(app)/[[lang=lang]]/find/SearchCard.svelte
[LWS-58](https://jira.kb.se/browse/LWS-58)
Displays instanceOf.publication.year (from-to) on search card (using the `jmespath` package to dig out the years).
Maybe these kinds of operations should be done in the backend, but i'm not entirely sure how to align it with the current data structure there 🤔 
Testing: search for 'sommar' against qa displays a few hits with their publication years indexed.
=> Publication year on search card

lxl-web/src/colors.css, lxl-web/src/lib/components/Search.svelte, lxl-web/src/lib/utils/addDefaultSearchParams.ts, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.server.ts, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/SearchMapping.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/search.ts, lxl-web/tailwind.config.js
[LWS-40](https://jira.kb.se/browse/LWS-40)
Uses the new `_q` parameter allowing advanced search queries.
* Use `_q` instead of `q` when searching
* Update `DisplayMappings` (search.ts) and `SearchMappings` (component) to support this.
TODO (maybe not now):
* ~~Build a nicer mapping interface~~
* Search for work by default (atm you need to ask for `type:work`)
* Hide certain params from the input field (you probably don't always want `type:work` there)
* Add labels for all properties in search mapping. Now displaying the `@id` in the absence of `labelByLang`.
* [uri #it ending issue](https://github.com/libris/librisxl/pull/1391) to be solved in FE?
=> Use _q parameter

lxl-web/src/lib/components/Modal.svelte, lxl-web/src/lib/components/ResourceImage.svelte, lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/lib/utils/getSortedSearchParams.ts, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.server.ts, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/[fnurgel=fnurgel]/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/[fnurgel=fnurgel]/InstancesList.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/[fnurgel=fnurgel]/utils.ts
[LWS-63](https://jira.kb.se/browse/LWS-63)
- Adds support for a holdings modal (showing where the resource can be found) on the resource page.
- Add holdings modal on resource page
- Add ResourceImage component to prevent code duplication
=> LWS-63: Add holdings on resource page

lxl-web/src/lib/components/Search.svelte
Search field being populated with stuff user never typed (ex * language:"https://id.kb.se/language/swe") when you use filters.
Easiest possible solution: display `_i` in search field if it exists, else use `_q`.
My suggestion is we use this as a starting point to investigate the limitations/need for an `_x=advanced` state etc.
Known quirks: 
* search for` yearPublished>2010` 
*  query remains as `_i` is still not present (the search query is not synced back from the api response - maybe is should, but that would result in re-fetching of data)
* use a filter on the side or paginate
* The query now disappears, i.e "becomes mapping pills" because `_i` now exists.
=> Display _i in search field

lxl-web/src/lib/assets/json/display-web.json, lxl-web/src/lib/components/DecoratedData.svelte, lxl-web/src/lib/utils/getAtPath.ts, lxl-web/src/lib/utils/xl.ts, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.server.ts
[LWS-65](https://jira.kb.se/browse/LWS-65)
Basic full text / related content links.
We probably want something nicer but this makes them clickable.
Doesn't handle display of license/copyright etc. (`usageAndAccessPolicy` etc)
Compare https://libris.kb.se/bib/18035875
* Display `MediaObject` and `Document` in `associatedMedia` and `isPrimaryTopicOf` as links
* `marc:publicNote` is used as link label
* `associatedMedia` ~= full text/image/etc so is diaplyed in a larger font
* A new style "ext-link" opens links a new tab
* A links from all instances are copied to the detail page overview (Work)
TODO
* "Open in new tab"/"external" icon on links
* Some descriptive text on full links. "Se hela bilden" etc?
* Clicking on image should go to full text/image?
=> Add basic full text links

lxl-web/src/lib/components/DecoratedData.svelte, lxl-web/src/lib/components/Search.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.server.ts, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/SearchMapping.svelte, lxl-web/vite.config.ts
* Enables user to see/edit their advanced search query by toggling the `_q` / `_i` params in search field.
* Use fetch `reddirect: manual` option to intercept api redirects. Then redirect to the same url in the frontend (in order to get the correct `_i`/`_q` combination).
* Display an edit button next to the search mapping pills _when `_i` and `_q` differ_ (i.e there is an active filter/advanced search query that can be shown in the input field). This felt like a clearer way to express this functionality than to have a 'simple/advanced search' toggle. 
**test with dev api**
~~backend fixes needed for this to work:~~
*  ~~`_x` param accepted and returned from the api (or this state will always be reset in the redirect operation)~~
*  ~~double url encoding fixed (or the url `searchParams` …
=> Feature/ i param 2

lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.svelte
Add more sort options to search component.
[LWS-113](https://jira.kb.se/browse/LWS-113)
* Add sort options
* Translate sort options
* Handle sorting of different types correctly. For example the publication year option only works on Works.
* Actual publication year data includes lots of 0000 and 9999. They now come first for oldest and newest, respectively. They should be filtered out by backend.
=> Add more sort options

lxl-web/src/lib/utils/isFnurgel.test.ts, lxl-web/src/lib/utils/isFnurgel.ts, lxl-web/src/params/fnurgel.ts, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.server.ts, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/[fnurgel=fnurgel]/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/[fnurgel=fnurgel]/utils.ts
[LWS-63](https://jira.kb.se/browse/LWS-63)
Fixes the list of unique holders (e.g. libraries) by instance type.
The `+layout.server.ts` file has started growing so it would be preferable to separate it into different `+page.server.ts` files again for the different routes. We also need to fix the missing Typescript types for the resource pages...
- Add isFnurgel util method
- Fix unique holders by type
- Add count in holder list title
=> LWS-63: Fix holders by type

lxl-web/src/routes/(app)/[[lang=lang]]/(find)/SearchMapping.svelte
[LWS-125](https://jira.kb.se/browse/LWS-125)
Hiding the wildcard pills throughout, which has the desired effect on the resource pages. In the search results, it is now possible to completely clear the pills.
=> LWS-125: Hide wildcard pills

lxl-web/src/lib/constants/pageTitle.ts, lxl-web/src/lib/utils/getPageTitle.test.ts, lxl-web/src/lib/utils/getPageTitle.ts, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.server.ts, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/[fnurgel=fnurgel]/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/find/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/+layout.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/+page.svelte
[LWS-122](https://jira.kb.se/browse/LWS-122)
Adds titles on pages; which are shown in the browsers title bar or a page's tab.
A separator (` | `) and suffix (`Libris`) is added when using the `getPageTitle` helper method.
- Add page titles
=> Add page titles

lxl-web/src/lib/components/Modal.svelte, lxl-web/src/lib/contexts/modal.ts, lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/FacetGroup.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/Filters.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/SearchMapping.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/search.ts, lxl-web/tailwind.config.js
[LWS-123](https://jira.kb.se/browse/LWS-123)
Adds support for showing and selecting filters on smaller screens.
TODO:
- Shallow routing / usage of `pushState` so back navigation closes the modal after opening it. This however opens a can of worms regarding what should happen when multiple filters are applied before closing the modal. We need to discuss this before implementing it.
- Horizontal scrolling of selected filters? The selected filters should probably not be wrapped as the screen real estate is really limited on mobiles. Figma sketches to discuss around would be good here.
- A _"Show X results"_ button (placed at the bottom of the modal?)
- Better no-js fallback styling (with added close button using an anchor link).
- The `+layout.svelte` has grown quite alot lately so we should …
=> LWS-123: responsive filters

lxl-web/src/lib/components/DecoratedData.svelte, lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/SearchCard.svelte
[LWS-154](https://kbse.atlassian.net/browse/LWS-154)
Search cards for smaller screens
Did not exhaust myself in reworking this, since I have a feeling search cards will be redesigned again sometime soon. But at least it looks ok now in mobile imo. 
* Under `sm`: Removed 'language' field, no 'pill' styling, tighter gaps; as in design
* I am however allowing contributor & years to have one row each (then line-clamped), I don't think it's possible to fit the card body into one single row.
* Fixed the empty 'ghost' bubbles that appear on cards (instances but no years)
* Added translations
=> LWS-119: Responsive search card

lxl-web/src/lib/components/ResourceImage.svelte, lxl-web/src/lib/utils/auxd.ts, lxl-web/src/lib/utils/auxd.types.ts, lxl-web/src/lib/utils/http.ts, lxl-web/src/lib/utils/xl.ts, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.server.ts, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/SearchCard.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/[fnurgel=fnurgel]/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/[fnurgel=fnurgel]/InstancesList.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/search.ts
Use thumbnails (128, 256px wide) in search results and on resource page.
[LWS-72](https://jira.kb.se/browse/LWS-72)
* Use thumbnail images
* Data structure `Image` for passing around image information (can be extended with license information etc.)
* Pass image to use to `ResourceImage` instead of it digging it out from the page data.
* Let `ResourceImage` take multiple images but only display one so far.
* lazy load instance thumbnails
TODO
* Use `ResourceImage` in `SearchCard`?
=> Use thumbnails

lxl-web/src/routes/(app)/[[lang=lang]]/(find)/SearchMapping.svelte
Using `inline` instead of `inline-block` for the labels seems to remove the weird filter pill space in Firefox. Can anyone confirm?
=> Fix filter pill space in Firefox

lxl-web/src/lib/components/DecoratedData.svelte, lxl-web/src/lib/components/Modal.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/[fnurgel=fnurgel]/+page.svelte, lxl-web/tests/resource.spec.ts
[LWS-171](https://kbse.atlassian.net/browse/LWS-171)
Fixes the visiblity of decorated data labels when navigating (I accidentally introduced the bug in https://github.com/libris/lxlviewer/commit/999dc779c859fe99a9712d108d5f531cfed707d1 when fixing duplicate content when closing modals). 
I have now added tests for both cases to catch eventual similar regressions in the future.
- Use data as value in key block
- Add tests
- Add workaround to remove duplicate content when closing modals
=> LWS-171: Fix label visibility

lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.server.ts, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/FacetGroup.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/Pagination.svelte
[LWS-131](https://kbse.atlassian.net/browse/LWS-131)
Bugs:
* Fix 'page 2'-bug (description of how to reproduce in comment in ticket). Caused by mutation of `$page.url.searchParams` 😱 
* Take `maxItems` into consideration (limit pagination at 10 000 when `totalItems` exceeds it).
Improvements:
* Rewrite links in search.ts _with_ lang param (no need to make extra call `relativizeUrl`).
* `sequenceSize` now more accurately decides now many pages should be displayed in pagination (aside from prev, first, last, next). Increasing from 2 to 3 because why not?
* Localizing the page numbers for readability.
=> LWS-131: Pagination bugfix/improvements

lxl-web/src/lib/assets/json/display-web.json, lxl-web/src/lib/components/DecoratedData.svelte
[LWS-141](https://kbse.atlassian.net/browse/LWS-141)
Add icon to external links. Suggested form:
We could do this in a more general way by e.g. supporting icons in `fresnel:contentLast` etc, by mapping an icon name to a general Svelte component (icon) in a similar way as in` getTypeIcon.ts`  but not sure if it is worth it? 
* Popover: "Opens in new tab" ???
=> Add external link icon and make text smaller

lxl-web/src/routes/(app)/[[lang=lang]]/(find)/FacetGroup.svelte
[LWS-138](https://kbse.atlassian.net/browse/LWS-138)
Applied some additional styling to the content in the filter panel.
* Slightly more highlighted and repositioned totalItems for better readability (?)
* More visible toggle btn
Still doesn't look at all readable some cases, but if truncation isn't an option, we really should give the panel (back) some more width.
=> LWS-138: styling tweaks to filters

lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/SearchCard.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/[fnurgel=fnurgel]/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/SiteHeader.svelte, lxl-web/tailwind.config.js
[LWS-178](https://kbse.atlassian.net/browse/LWS-178)
Removes padding around search cards on mobile breakpoints (so they stretch to the edges of the screen)
- Remove padding around search cards on mobile breakpoints
=> LWS-178: Remove padding around search cards on mobile breakpoints

vue-client/src/components/inspector/reverse-relations.vue
Currently if you visit e.g. https://libris.kb.se/katalogisering/search/libris?q=*&_limit=20&%40type=Instance&_sort= the cat client will do 41 `/find` searches. 20 of them are of the type "does my current sigel have holdings for this instance?". These are performed even if you're not logged in, i.e., even if there is no active sigel (`myHoldingQuery['heldBy.@id']` will then be `https://libris.kb.se/library/`). Which is just meaningless and wasteful. So let's only do that search if logged in :)
(So this reduces the number of searches from 41 to 20; additionally, if https://github.com/libris/librisxl/pull/1439 is merged, we can do some furter adjustments and go from 20 to 1)
=> Don't check holdings for sigel if there's no active sigel

lxl-web/src/lib/components/Search.svelte
Unreported
Recreate in QA:
* Visit a resource page with related items: https://beta.libris-qa.kb.se/42gkn33n1g72f46
* Navigate to page 2 (`_o` now appears in url)
* Reload the page
* Perform a new search using the top search bar
* The new search result still (secretly) uses the `_o` param, heavily impacting the results.
delete _o from params to be included on new search.
=> Bugfix lingering _o param on new search

lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.server.ts, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/search.ts
Separate related resource on relation type (predicate) on the resource page.
Display each relation type as a tab.
Not super happy with the wording
`<resource>` förekommer som `<predicate label>`
Depends on https://github.com/libris/librisxl/pull/1438
[LWS-164](https://jira.kb.se/browse/LWS-164)
* Split `getSearchResult()` into `getSearchResult()` and  `getRelated()` because it was getting super gnarly. Svelte Redirects cannot be used inside streaming responses. Might have to redo this when we add free text filtering to that list.
* Getting related resources requires two search API round trips when entering a resource page. One to get the list of predicates and one for selecting the first one. The API could be extended to allow e.g. `_p=0` to automatically select the first available `_p`
* …
=> Display related resources in tabs on resource page

lxl-web/src/routes/(app)/[[lang=lang]]/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/SiteFooter.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/frontpage.en.md, lxl-web/src/routes/(app)/[[lang=lang]]/frontpage.sv.md
* Frontpage content as frontpage.[lang].md.
* Correct link to FAQ on frontpage and in footer.
=> Frontpage content as .md

lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.svelte
[LWS-168](https://kbse.atlassian.net/browse/LWS-168)
* Align the sorting to the right
* Consistent select appearance across browsers
* modify label: 'Sort by' --> 'Sort'
* Adjust padding for the toolbar
=> LWS-168: Align sort right

vue-client/src/components/inspector/reverse-relations.vue
Since https://github.com/libris/librisxl/pull/1439 we store the total number of incoming links per type in each ES document. This vue-client change uses that data (if present), avoiding unnecessary requests. Backwards-compatible with older indices.
For a typical cataloguing client search result page this reduces the number of `/find` requests by 20.
=> Use totalItemsByRelation when possible

lxl-web/src/lib/components/ResourceImage.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/[fnurgel=fnurgel]/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/[fnurgel=fnurgel]/InstancesList.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/[fnurgel=fnurgel]/InstancesListContent.svelte, lxl-web/tailwind.config.js
[LWS-180](https://kbse.atlassian.net/browse/LWS-180)
Improve responsiveness of instance list images.
* Extracted the template columns of the instance list into a tailwind class used on both header & content. On small screens the content gets a single column.
* Make the image inherit the value of `object-position` instead of always centering it. Allowing us to set it left for the instance list & center for the resource img.
=> LWS-180: Responsive instance list img

lxl-web/src/lib/assets/json/display-web.json, lxl-web/src/lib/components/DecoratedData.svelte
[LWS-194](https://kbse.atlassian.net/browse/LWS-194)
The implementation for showing an icon after external links was severely shoehorned into the decorated data logic, with hard coded types etc to make it work. A fix for LWS-194 conforming to this implementation would require even more special handling, and felt strained.
This is an attempt at a more simple solution, that should work for properties regardless of their current presentation/style. 
It looks like this:
Inspired by top bar at https://iconify.design/docs/usage/svg/unplugin/:
Could maybe be fine tuned with a slight vertical raise?
=> Alternative to external link icon

lxl-web/src/lib/components/find/Pagination.svelte, lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/lib/types/search.ts, lxl-web/src/lib/utils/search.ts, lxl-web/src/routes/(app)/[[lang=lang]]/help/en.md, lxl-web/src/routes/(app)/[[lang=lang]]/help/sv.md, lxl-web/tailwind.config.js, lxl-web/tests/find.spec.ts
[LWS-131](https://kbse.atlassian.net/browse/LWS-131)
Paginating the relation search does not work in some cases.
Because: simply appending `_offset` to the link causes a new double-fetch (introduced with the predicate tabs) that ultimately uses the predicate `view` to get the data. That link excludes any applied `_offset`, fetching the first 10 hits again.
By using a backend-made link as template for all pagination links, we avoid the problem (and double fetch) since they include the `_p` param.
* Fix pagination links
* Tweak pagination template
* Mobile look tweaks
=> LWS-313: Yet another pagination bugfix

lxl-web/src/lib/components/find/SearchCard.svelte
[LWS-195](https://kbse.atlassian.net/browse/LWS-195)
Make `card-header-extra` text in search card selectable.
- Make card-header-extra text selectable
=> Make card-header-extra text selectable

lxl-web/src/lib/components/Search.svelte, lxl-web/src/lib/components/find/FacetRange.svelte, lxl-web/src/lib/components/find/SearchRelated.svelte, lxl-web/src/lib/components/find/SearchResult.svelte, lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.server.ts
[LWS-143](https://kbse.atlassian.net/browse/LWS-143)
Adds a search input in the toolbar section for the related search result
* Added component `SearchRelated` that searches in the context of the current `_o` and `_p`.
* Zero results for the related search is no longer hidden, as it can now happen as a result of an active search.
* Some modifications to 'main search' to stay independent of related search.
Limits/todos:
* Searching completely clears any existing filters, due to frontends inability to modify `_q` param in a safe way. If we need to keep the filters, maybe template links (such as in year range) could be a solution.
* Layout/placement of the search bar for different widths is debatable (lack of design in Figma).
=> LWS-143: Related hits search

lxl-web/src/lib/components/find/SearchMapping.svelte, lxl-web/src/lib/types/search.ts, lxl-web/src/lib/utils/search.ts, lxl-web/src/routes/(app)/[[lang=lang]]/help/en.md, lxl-web/src/routes/(app)/[[lang=lang]]/help/sv.md
[LWS-145](https://kbse.atlassian.net/browse/LWS-145)
Remove free text label and add quotes instead 
- Remove freetext label and add quotes instead
=> LWS-145: Remove freetext label and add quotes instead

lxl-web/src/lib/components/Modal.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/help/en.md, lxl-web/src/routes/(app)/[[lang=lang]]/help/sv.md, lxl-web/tests/resource.spec.ts
[LWS-211](https://kbse.atlassian.net/browse/LWS-211)
Adds support for closing initially opened holdings modals
- Add support for closing initially opened holdings modals
- Add test
=> LWS-211: Fix support for closing initially opened holdings modals

lxl-web/src/lib/utils/addDefaultSearchParams.test.ts, lxl-web/src/lib/utils/addDefaultSearchParams.ts, lxl-web/src/lib/utils/http.test.ts, lxl-web/src/routes/(app)/[[lang=lang]]/help/en.md, lxl-web/src/routes/(app)/[[lang=lang]]/help/sv.md, lxl-web/tests/error.spec.ts, lxl-web/tests/find.spec.ts, lxl-web/tests/index.spec.ts
[LWS-213](https://kbse.atlassian.net/browse/LWS-213)
Changes the default limit of results from 10 to 20.
This should be customizable when we have added user settings (see: [LWS-93](https://kbse.atlassian.net/browse/LWS-93))
- Change the default limit of results to 20.
=> LWS-213: Change default limit of results to 20

lxl-web/svelte.config.js
See https://kbse.atlassian.net/browse/LWS-215
Protects against XSS (among other things). https://kit.svelte.dev/docs/configuration#csp
Svelte automatically adds/sets nonces:
```
~ curl -I http://localhost:5173/
HTTP/1.1 200 OK
...
content-security-policy: default-src 'self'; img-src 'self' kb.se *.kb.se data:; script-src 'self' https://analytics.kb.se 'nonce-KS7ArPuN4IbXFqoAts03vg=='; style-src 'self' 'unsafe-inline'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'
```
I don't like style-src's `unsafe-inline`, but Svelte adds it automatically anyway; perhaps it can't (at this point) work without it. There's an open issue: https://github.com/sveltejs/kit/issues/11747
I set style-src explicitly in `svelte.config.js` because otherwise, for some reason, `unsafe-inline` is _not_ …
=> Add Content-Security-Policy to Svelte config

lxl-web/package-lock.json, lxl-web/package.json, lxl-web/src/ambient.d.ts, lxl-web/src/lib/components/find/SearchResult.svelte, lxl-web/src/nprogress.css, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.server.ts, lxl-web/src/routes/+layout.svelte
Adds a loading indicator
[LWS-209](https://kbse.atlassian.net/browse/LWS-209)
No indication of anything happening when for example searching.
* Added a progress bar (rather than a spinner) using the [nProgress](https://www.npmjs.com/package/nprogress) package. It runs on every navigation but i've added a small delay to avoid showing it on instant navigations. This can of course be tweaked further.
* With this in place, I tried removing the streaming of search results on resource pages. This would otherwise require a _second_ spinner to replace the 'loading' text. I think this works well - with the indicator in place, it's quite satisfying to get the whole page at once.
* Made some minor related adjustments to the `load` function on the resource page. The `getRelated()` / `await …
=> LWS-209: Add spinner

vue-client/src/components/search/search-form.vue, vue-client/src/components/search/search-result.vue, vue-client/src/resources/json/i18n.json
Display spelling suggestions from search API in main search screen.
[LWS-87](https://jira.kb.se/browse/LWS-87)
=> Display spelling suggestions in cataloging client

vue-client/src/components/inspector/toolbar.vue
Do a simple hardcoded check for dataset URI prefixes for now. Until we have decided on an how to specify this in backend. See for example EntityContainers for Concepts.
[LXL-4254](https://jira.kb.se/browse/LXL-4254)
Prevents accidental editing of language, library and other definitions from externally defined datasets.
There is still no access control mechanism for these in backend. This does not guard against malicious changes.
=> Block id.kb.se and libris.kb.se datasets from being edited

lxl-web/src/lib/components/ResourceImage.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.svelte
[LWS-219](https://kbse.atlassian.net/browse/LWS-219)
Weird placement of resource images in Safari. (Not just mobile, this is desktop Safari:)
* Clearly, Safari doesn't respect the `max-height` of an element with `display:table` (introduced with the `figcaption` stuff). Using only `height` works - it doesn't seem to break anything else...
* Setting `w-full` on the image container allows the image to align to the page left margin on md+ screens. This seems to be desired since it has `justify-center md:justify-start`.
=> LWS-219: Fix resource image placement on Safari

lxl-web/src/lib/components/find/SearchMapping.svelte, lxl-web/src/lib/utils/search.ts
[LWS-201](https://kbse.atlassian.net/browse/LWS-201)
[LWS-203](https://kbse.atlassian.net/browse/LWS-203)
* Firefox chip gap
* Missing labels for ISBN & ISSN
Giving up on trying to fix both lowercase labels & weird Firefox pill gap with pure CSS, we now do it "for real" in the FE-backend.
In the process I discovered that the label is sometimes found in `property.label` (duh!) which we never check before falling back on the `@id`. This fixes both examples (ISBN and ISSN) in LWS-203. Don't know if you've seen more cases @poacherone?
=> LWS-201/203: Fix pill labels

vue-client/src/components/search/search-form.vue
[LXL-4457](https://kbse.atlassian.net/browse/LXL-4457)
Keeps sort options when doing new searches from the search result page.
This works by reusing old sort query param for new searches. Note that this doesn't involve the local storage functionality (which currently only works if the user is signed in), so the last selected sort option isn't persisted if an unauthenticated user navigates to the start page and enters a new search query. 
- Use _sort value from route as preferred sort
- Check if sort value from route query param is available for active search type
=> LXL-4457: Keep sort options when doing new searches

vue-client/src/components/inspector/reverse-relations.vue
Was broken by the early return in c4434a0.
We can always find the holdings in `@reverse/itemOf` for each Instance in the search result. 
So remove the code that does an additional query for the holding.
[LXL-4541](https://kbse.atlassian.net/browse/LXL-4541)
=> Fix display of user's own holding in hitlist

vue-client/src/components/care/create-message.vue, vue-client/src/components/inspector/language-entry.vue
[LXL-4485](https://kbse.atlassian.net/browse/LXL-4485)
Pre-fill cxz comment with sigel & current date for better orientation when listing messages.
Add the template text to `language-entry` textarea on init if conditions are met: It's an empty `comment` whose mainEntity type is subclass of `AdministrativeAction`.
=> LXL-4485: Add date & sigel to cxz message comment

lxljs/display.js, vue-client/src/components/inspector/field.vue, vue-client/src/components/inspector/toolbar.vue
[LXL-4539](https://kbse.atlassian.net/browse/LXL-4539)
* Result list breaking when a hit has multiple `@type`s (locally - in production showing empty boxes:)
* [local](http://localhost:8080/katalogisering/search/libris?q=*&@type=Concept&_limit=20&_sort=_sortKeyByLang.sv&_spell=true&and-inScheme.@id=https://id.kb.se/marc&_offset=0)
[dev](https://libris-dev.kb.se/katalogisering/search/libris?q=*&@type=Concept&_limit=20&_sort=_sortKeyByLang.sv&_spell=true&and-inScheme.@id=https://id.kb.se/marc&_offset=0)
* Inspector breaking when `mainEntity` has multiple `@type`s (locally, in production some information is just missing)
[local](http://localhost:8080/katalogisering/9h0hfnvdc4crddn5)
[dev](https://libris-dev.kb.se/katalogisering/9h0hfnvdc4crddn5)
* In the result list, the culprit is the …
=> LXL-4539: handle multiple types

lxl-web/src/lib/assets/json/display-web.json, lxl-web/src/lib/components/find/FacetGroup.svelte, lxl-web/src/lib/types/holdings.ts, lxl-web/src/lib/utils/holdings.ts, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.server.ts, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/HoldingStatus.svelte
[LWS-225](https://kbse.atlassian.net/browse/LWS-225)
Display additional (distinguishing) library information in the holdings panel.
This could really be as easy as printing the `qualifier` alongside the name. But I tried a more cumbersome approach 😆 
To stay consistent with how we do it elsewhere (libraries in the facets, for example) we now display decorated data here.
* `lensAndFormat` the libraries inside the functions that prepare data for the holdings panel: `holdingsByInstanceId` and `holdersByType`. 
* Break out new util method `getHoldingsByType` in /utils. 
* New types and some checks to get rid of ts-warnings in `/fnurgel/page.svelte`. 
* The decorated labels are ellipsed, but displayed multi-line when opened. 
* We now also use `DecoratedData` component in facets instead of …
=> LWS-225: improve display of libraries in holdings panel

vue-client/src/components/shared/entity-summary.vue, vue-client/src/components/shared/id-pill.vue
Fix fnurgel being displayed in card top corner instead of id.kb.se URI.
This affected search results and popup cards for links.
QA
PROD
Also: 
* Fix id-pill overflow on long URI:s (in the same way as before it was extracted to a component)
* Naming things: displayed id is not always a fnurgel
[LXL-4545](https://kbse.atlassian.net/browse/LXL-4545)
=> Fix fnurgel being displayed in id-pill instead of id.kb.se URI

lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/lib/types/holdings.ts, lxl-web/src/lib/utils/holdings.ts, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.svelte
[LWS-210](https://kbse.atlassian.net/browse/LWS-210)
Adds an input to find libraries in the holdings list. 
Works/looks very similar to the search in the facet panel, with some differences:
* The search string is used to create a filtered list, rather than sent to the individual components. This felt like a cleaner way to do it + we can display 'no hits'. Trade-of is components are unmounted/mounted on search, meaning we have to perform the api call again if re-displayed, re-expanded.
* The search is matched anywhere in the string (`indexOf`) to allow searching for sigel, for example.
* ATM the search string remains in the input if panel is closed and re-opened. Don't know if that's good or bad?
* Add the rendered (searchable) string to `DecoratedHolder` obj
* Add reactive variables …
=> LWS-210: Filter libraries

lxl-web/src/lib/assets/json/display-web.json, lxl-web/src/lib/components/DecoratedData.svelte
[LWS-227](https://kbse.atlassian.net/browse/LWS-227)
See discussion in https://github.com/libris/lxlviewer/pull/1093 
Extend the possibilites to style the decorated data using formatters.
* DecoratedData now applies classes from the current "level" not only for data-types, but for data-properties, `contentBefore` and `contentAfter`.
* Some changes to the displayfile to reflect this
For example:
```
"Role-format": {
"@id": "Role-format",
"@type": "fresnel:Format",
"fresnel:classFormatDomain": ["Role"],
"fresnel:resourceStyle": ["definition"]
},
"Contribution-role-format": {
"@id": "Contribution-role-format",
"@type": "fresnel:Format",
"fresnel:classFormatDomain": ["Contribution"],
"fresnel:propertyFormatDomain": ["role"],
"fresnel:propertyStyle": ["secondary", "small"], …
```
=> LWS-227: Extend formatter styling possibilites

lxl-web/src/lib/components/find/SearchRelated.svelte, lxl-web/src/lib/components/find/SearchResult.svelte, lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/lib/types/search.ts, lxl-web/src/lib/utils/addDefaultSearchParams.test.ts, lxl-web/src/lib/utils/addDefaultSearchParams.ts, lxl-web/src/lib/utils/search.ts, lxl-web/tests/index.spec.ts
[LWS-218](https://kbse.atlassian.net/browse/LWS-218)
Displays spelling suggestions next to the search result. (It's an array, but I've never seen more than one?) 
Printing the `label` instead of the `labelHtml` since ESLint discourages the use of `{@html}`.
Also, as by suggestion from @johanbissemattsson, rewriting the link to `spell=false` to prevent getting _another_ suggestion after accepting the first one.
We need to observe if the functionality is at all useful with 'related search' on resource pages. You often get suggestions that result in zero hits there (I guess it doesn't take into account the implicit o-filter...)
* Display spelling suggestion
* Add type `SpellingSuggestion`
* Make `SearchRelated` update `_i` param on navigation
* Relation search layout adjustments
* Fix …
=> LWS-218: Display spelling suggestions

lxl-web/src/lib/components/DecoratedData.svelte
Checking that the `_label` is a string to prevent printing `[object object]`, currently displaying in the `role` popovers.
example [before](https://beta.libris-dev.kb.se/ztt50fk21529dw1p) / [after](http://localhost:5173/ztt50fk21529dw1p)
---
A bit more in-depth...
Data looking like:
```
"domain": {
"@id": "https://id.kb.se/vocab/Work"
},
"_label": {
"@id": "http://www.w3.org/2000/01/rdf-schema#domain",
"labelByLang": {
"en": "Domain",
"sv": "Förekommer på"
}
}
```
`_label` not being flattened to "Förekommer på", is that a bug? In the next recursion, `domain` content is hidden, since it contains an `@id`.
In any which case, I think the string check makes sense...
=> Fix [object object] for popovers

lxl-web/src/colors.css, lxl-web/src/lib/actions/popover/Popover.svelte, lxl-web/src/lib/actions/popover/index.ts, lxl-web/src/lib/assets/json/display-web.json, lxl-web/src/lib/components/ResourceImage.svelte, lxl-web/src/lib/components/find/FacetGroup.svelte, lxl-web/src/lib/components/find/Filters.svelte, lxl-web/src/lib/constants/facets.ts, lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/lib/types/search.ts, lxl-web/src/lib/utils/search.ts, lxl-web/tailwind.config.js
[LWS-243](https://kbse.atlassian.net/browse/LWS-243)
Add info text + popover when number of facets in a group reaches its limit + more tweaks
* Add limit notification (can be seen for subject or genre/form with a wide search, when clicking 'show more')
~~The limits are set in [the apps file](https://github.com/libris/definitions/blob/develop/source/apps.jsonld) and the current solution has simply copied this to the frontend. Not ideal since sync:ing that will be easily forgotten. Possible other solutions is to a) fetch the file somehow b) Get the limit/limit reached with the api response?~~
* 'No search result' text displayed when searching in filters. This was sort of implemented but not working.
To improve readability in filter panel (open for discussion on these 😄 )
* Facet items …
=> LWS-243: Facet limit info

vue-client/yarn.lock
[LXL-4544](https://kbse.atlassian.net/browse/LXL-4544)
Update the peer dependency of the `client-oauth2` package to fix a moderate severity vulnerability.
Decided to go for the easy option (to not replace the package itself) because this one is tried and tested (albeit not maintained) and there's no obvious successor. This has to do with auth flow being a bit dated and [should be rewritten](https://kbse.atlassian.net/browse/LXL-2913), however out of scope for this.
Also updates two more peer deps that caused high/moderate security alerts.
Updated 
- `popsicle` 12.1.0 -> 12.1.2 (dependency of `client-oauth2`, fixes `tough-cookie`)
- `elliptic` 6.5.4 -> 6.5.7 (dependency of `crypto-browserify`)
- `rollup` 4.21.0 -> 4.22.4 (dependency of `vite`/`vitest`)
=> LXL-4544: Upgrade client-oauth2 etc

idkbse/src/plugins/env.js
Terms containing a comma don't work:
* [https://id.kb.se/term/sao/Frihet--teori%2C%20filosofi](https://id.kb.se/term/sao/Frihet--teori,%20filosofi)
* https://id.kb.se/term/sao/Berlinmurens%20fall%2C%20Tyskland%2C%201989
* several hundred more
This is because we doesn't encode the comma when sending it to the backend. Solution: encode the comma. (Perhaps it gets decoded along the way to Nuxt or by something in Nuxt -- anyway, this fixes the problem like we previously fixed similar problems)
[LXL-4047](https://kbse.atlassian.net/browse/LXL-4047)
=> Encode comma in requests to backend

lxl-web/package-lock.json, lxl-web/package.json
[LWS-226](https://kbse.atlassian.net/browse/LWS-226)
Bumps dependencies
- Fix rollup vulnerability
update the following:
```
@axe-core/playwright 4.9.1 -> 4.10.0
@floating-ui/dom 1.6.10 -> 1.6.11
@iconify-json/bi 1.1.24 -> 1.2.0
@playwright/test 1.46.1 -> 1.47.2
@sveltejs/adapter-node 5.2.2 -> 5.2.5
@sveltejs/kit 2.5.24 -> 2.6.1
@sveltejs/vite-plugin-svelte 3.1.1 -> 3.1.2
@types/eslint 9.6.0 -> 9.6.1
cssnano 7.0.5 -> 7.0.6
eslint 9.9.0 -> 9.11.1
eslint-plugin-svelte 2.43.0 -> 2.44.1
husky 9.1.4 -> 9.1.6
lint-staged 15.2.9 -> 15.2.10
prettier-plugin-svelte 3.2.6 -> 3.2.7
prettier-plugin-tailwindcss 0.6.6 -> 0.6.8
svelte-check 3.8.5 -> 4.0.4
tailwindcss 3.4.10 -> 3.4.13
tslib 2.6.3 -> 2.7.0
typescript 5.5.4 -> 5.6.2
typescript-eslint 8.1.0 -> 8.7.0
unplugin-icons 0.19.2 -> 0.19.3
vite 5.4.6 …
```
=> LWS-226: Bump lxl-web dependencies

lxl-web/src/lib/assets/json/display-web.json
[LWS-175](https://kbse.atlassian.net/browse/LWS-175)
See description in ticket. Subject term components that are subterms are not being linked.
`Topic` (Subject) -- `TopicSubdivision` (Subdivision)
Fixing by giving Subdivision the link class. Hope this does not produce oddities in other places in GUI :)
Also this does not solve the first bullet point (subterms not showing up in facets?)
Examples: 
[QA](https://beta.libris-qa.kb.se/g0s59brs1hkp3bc#work-record) [local](http://localhost:5173/g0s59brs1hkp3bc#work-record) [cat](https://libris.kb.se/katalogisering/g0s59brs1hkp3bc)
Add formatter for Subdivision class
=> LWS-175: Link subdivision

lxl-web/src/lib/assets/json/display-web.json
Override the definition in [display.jsonld](https://github.com/libris/definitions/blob/fe537471562816cf3b01c72443f0cd43e45625e3/source/vocab/display.jsonld#L448) so that it is displayed in the same way as Concept.
before
after
=> Move inScheme from chip to card for Subdivision

lxl-web/src/lib/components/find/FacetGroup.svelte, lxl-web/src/lib/constants/facets.ts, lxl-web/src/routes/(app)/[[lang=lang]]/help/en.md, lxl-web/src/routes/(app)/[[lang=lang]]/help/sv.md
[LWS-244](https://kbse.atlassian.net/browse/LWS-244)
After feedback:
* Change default sorting of `bibiography`, `itemHeldBy` to a-z
* Make sure the limit info is visible when searching
* Bigger surface for triggering limit info popover
=> LWS-244: Tweaks to filter sorting

lxl-web/src/lib/assets/json/display-web.json, lxl-web/src/lib/components/DecoratedData.svelte, lxl-web/src/routes/api/holdingstatus/+server.ts
[LWS-144](https://kbse.atlassian.net/browse/LWS-144)
Three 'lil fixes
* Style unlinked genre/form pills more clearly.
Before/after [link](http://localhost:5173/07swlsq4xwsn32j0)
----
* Include 'related' in genre/form formatting to fix weirdness
Before/after [link](http://localhost:5173/42gkpppn0qmwc3g)
----
* Replace ISO-encoded quote in loan status
before/after [link](http://localhost:5173/07wrgx1sx24j25pn?holdings=StillImageInstance)
=> LWS-144: Style unlinked pills etc

lxl-web/src/lib/assets/json/display-web.json, lxl-web/src/lib/utils/xl.ts
[LWS-166](https://kbse.atlassian.net/browse/LWS-166)
`reproductionOf` / `hasReproduction` on resource page show instance cards, which becomes messy.
Don't know if more properties need a similar fix?
before / after [link](http://localhost:5173/6nsmclp44mn98b3w)
/
Displaying `hasReproduction` as block elements
Adding another hardcoded exception to the lens selector. Not super happy about that, maybe this 'sublens' thing is the long term solution?
=> LWS-166: Show reproduction instance chip

lxl-web/src/lib/components/Matomo.svelte, lxl-web/src/lib/contexts/matomo.ts
I've discovered a bug in the Matomo implementation. Sometimes `initMatomo` is called before the matomo.js script has loaded, causing the whole thing to fail silently and nothing is logged (until a page reload - when the script is probably cached). Try it out by opening a fresh incognito tab and visit beta-dev a couple of times.
We need to `setContext` during component initialization, but we can update it with the tracker when the script is ready. Here  using an `on:load` handler. Also doing a `trackPageView` in the init function so we don't miss to track the first page load.
=> Matomo tracker load fix

cataloging/src/components/care/bulk-changes.vue, cataloging/src/components/care/form-builder.vue, cataloging/src/components/inspector/entity-adder.vue, cataloging/src/components/inspector/item-local.vue, cataloging/src/components/inspector/item-type.vue, cataloging/src/components/mixins/form-mixin.vue, cataloging/src/settings.js, lxljs/vocab.js
--** Soft type matching **--
This uses a hard coded dummy "Any" type. Maybe it should be` "@type" : "Unspecified"` instead? Maybe it should be a real type, so that the correct label is presented automatically?
TODO: fix "Any" type label in side panel.
IN THE FUTURE: move 'Add local entity' button from property-adder.vue to field.vue?
=> Use unspecified type as default in bulk change view

lxl-web/package-lock.json, lxl-web/package.json, lxl-web/src/lib/components/CookieConsent.svelte, lxl-web/src/lib/contexts/matomo.ts, lxl-web/src/lib/i18n/locales/cookieConsent.en.js, lxl-web/src/lib/i18n/locales/cookieConsent.sv.js, lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/lib/types/matomo.ts, lxl-web/src/routes/(app)/[[lang=lang]]/SiteFooter.svelte, lxl-web/src/routes/+layout.svelte
[LWS-231](https://kbse.atlassian.net/browse/LWS-231)
Adds cookie consent functionality using [vanilla-cookieconsent](https://cookieconsent.orestbida.com/) package.
Using the same implementation as Tidningar, i.e if user opts out of analytical cookies, we don't track them _at all_.
To test:
* No post requests to matomo.php are being made until user accepts all cookies.
* Post requests to matomo.php are made when user consents to all cookies.
* Requests to matomo.php stops when user redacts their consent (using the settings link in the footer) and matomo cookies (`_pk*`) are cleared.
Add cookie package, cookie component & translation files.
=> LWS-231: Cookie consent

lxl-web/src/lib/components/SuperSearch.svelte, lxl-web/src/lib/utils/codemirror/getEditedParts.ts
Edited `word` getting sliced at nearest blankspace, regardless of being part of a quoted phrase.
Example `person:"Astrid lindgren"` resulted in a search for `contributor:"Astrid` and `lindgren"`
* `fromWordIndex`, `toWordIndex` now postitioning at nearest blankspace but ignoring those within quotes.
* Update `QUALIFIER_REGEX` to allow the value to have blank spaces in quotes.
try console.logging `word` to see how it works.
**Examples of searches and resulting suggestions:**
`person:"Lindgren, Astrid"`
Before: 
`Medverkande: Thelander, Astrid`
After:
`Medverkande: Lindgren, Astrid`
`titel:"på spaning efter den tid som flytt"`
Before:
`Genre/form: Sedesskildringar`
After:
`Verk: På spaning efter den tid som flytt`
`subject:”vintern i konsten”`
Before:
`Ämne: Poeter i konsten`
After:
`Ämne: …
=> Handle quoted qualifier value

lxl-web/src/app.css, lxl-web/src/lib/assets/json/display-web.json, lxl-web/src/lib/utils/xl.ts
Display `uri` in `Identifier` as external link.
Example:
* Add `uri` to `Identifier-chips`
* Use `uriToId()` to make uri a "fake `@id`" for Identifier
* Only show ext-link arrow on a elements
=> feat(lxl-web): clickable Identifier uri, e.g. ISNI

lxl-web/src/lib/components/CodeMirror.svelte, lxl-web/src/lib/components/SuperSearch.svelte, lxl-web/src/lib/utils/codemirror/extensions/preventInsertBeforeQualifier.ts, lxl-web/src/lib/utils/codemirror/extensions/qualifierDecoration.ts, lxl-web/src/lib/utils/codemirror/getEditedParts.test.ts, lxl-web/src/lib/utils/codemirror/getEditedParts.ts
* Decorates a valid qualifier key:value pair.
(I noticed there are now multiple qualifier regex:es around the app, maybe we should look into that...)
* Fixes a small annoyance where the expanded search closes when selecting text and releasing the mouse outside of the box.
* Fixes a bug inserting more and more whitespace before a qualifier.
(you can see it by typing `key:value` and then before it, `df df df df df df d df df` 
* Fix broken unit tests + add one
=> New qualifier decorator

.github/workflows/lxl-web.yml
Bumps Node.js to latest LTS version (v22) in `lxl-web` GitHub workflow file
- Bump node version in github workflow
- Remove redundant usage of yarn (npm ci and npm packages removes the need of yarn)
=> Bump node version in github action for lxl-web

package-lock.json, packages/codemirror-lang-lxlquery/.husky/pre-commit, packages/codemirror-lang-lxlquery/.prettierrc, packages/codemirror-lang-lxlquery/README.md, packages/codemirror-lang-lxlquery/eslint.config.js, packages/codemirror-lang-lxlquery/package.json, packages/codemirror-lang-lxlquery/rollup.config.js, packages/codemirror-lang-lxlquery/src/index.ts, packages/codemirror-lang-lxlquery/src/syntax.grammar.d.ts, packages/codemirror-lang-lxlquery/test/test.js, packages/codemirror-lang-lxlquery/tsconfig.json, packages/codemirror-lang-lxlquery/vitest.config.ts
[LWS-266](https://kbse.atlassian.net/browse/LWS-266)
Adds automatic formatting and linting on commits using [prettier](https://prettier.io/) and [eslint](https://eslint.org/) in conjuction with [husky](https://typicode.github.io/husky/) and [lint-staged](https://github.com/lint-staged/lint-staged).
The code formatting and linting adheres to the normalized code formatting in `lxl-web` and the `supersearch` package.
- Add automatic formatting and linting on commits
- Format and lint all existing files
- Add format and lint scripts to package.json
=> LWS-266: Add automatic formatting and linting to codemirror-lang-lxlquery

cataloging/src/components/care/bulk-changes.vue, cataloging/src/components/care/merge-spec.vue, cataloging/src/components/care/preview.vue, cataloging/src/components/inspector/entity-form.vue, cataloging/src/components/mixins/form-mixin.vue, cataloging/src/resources/json/combinedTemplates.json, cataloging/src/resources/json/i18n.json, cataloging/src/utils/bulk.js
* Add a new bulk spec type `Other`
* Add a template for removing topic subdivisions
For now it reuses the same form as Merge. We probably want to separate them? But there are many place check isMergeSpec etc.
We could pass some more stuff from the template in order to have some description of the change. Or just map some strings to the script name.
=> Add bulk script for removing topic subdivisions

lxl-web/src/lib/components/Search.svelte, packages/supersearch/src/lib/components/CodeMirror.svelte, packages/supersearch/src/lib/components/SuperSearch.svelte, packages/supersearch/src/routes/+page.svelte
Add placeholder compartment/prop for [partial dynamic configuration](https://codemirror.net/examples/config/#dynamic-configuration) of the placeholder extension.
It acts of an example of how to use CodeMirrors [compartments](https://codemirror.net/examples/config/#compartments).
I'm a little bit torn/unsure if we should treat `editorView` as a [bindable](https://svelte.dev/docs/svelte/$bindable) prop, or if we should expose the current editor view using an event handler function (e.g. `onmount` from the `CodeMirror.svelte` component combined with a `handleMountCodeMirror` function inside `SuperSearch.svelte`). 
The bindable approach will result in fewer lines of code but we probably don't want the bindable prop for it's two-way binding abilites, as we should generally be careful to mutate …
=> Add placeholder compartment/prop

lxl-web/src/lib/components/CookieConsent.svelte, lxl-web/src/lib/contexts/matomo.ts
As a dev you might want to comment out `PUBLIC_MATOMO_ID` so your lousy test searches don't end up in analytics. But doing so result in console errors related to the cookie consent component. This allows us to gracefully disable the tracker.
* Add checks before running methods on `$matomoTracker`
=> fix(lxlweb): prevent error when missing matomo-id

README.md, packages/supersearch/README.md
[LWS-256](https://kbse.atlassian.net/browse/LWS-256)
Updates the readme for `supersearch`.
It can act as a starting point for further documentation and can hopefully contribute to a habit of adding documentation in conjuction with the development of new features (e.g. when adding new props) – knowledge that can otherwise be forgotten if written long after.
The PR also includes a small note in the root readme file describing what `codemirror-lang-lxlquery` is.
- Update readme
- Add codemirror-lang-lxlquery to root readme
=> LWS-256: Update documentation

.github/workflows/codemirror-lang-lxlquery.yml, .github/workflows/lxl-web.yml, .github/workflows/supersearch.yml, .husky/install.mjs, .husky/pre-commit, lxl-web/.husky/pre-commit, lxl-web/.lintstagedrc, lxl-web/package.json, package-lock.json, package.json, packages/codemirror-lang-lxlquery/.husky/pre-commit, packages/codemirror-lang-lxlquery/.lintstagedrc, packages/codemirror-lang-lxlquery/package.json, packages/supersearch/.husky/pre-commit, packages/supersearch/.lintstagedrc, packages/supersearch/package.json
Runs [husky](https://typicode.github.io/husky/) and [lint-staged](https://github.com/lint-staged/lint-staged) from the git repo root instead of juggling with different command paths for the different projects. Usage of husky is removed during CI (as it's not needed there).
- Run husky and lint-staged from git repo root
- Prevent usage of husky in CI
=> chore: Run husky and lint-staged from git repo root

cataloging/.env.development.in, cataloging/.env.e2e, cataloging/package.json, cataloging/src/App.vue, cataloging/src/main.js, cataloging/src/settings.js, cataloging/yarn.lock
[LXL-4560](https://kbse.atlassian.net/browse/LXL-4560)
Adds [vue-matomo](https://www.npmjs.com/package/vue-matomo) package. It's a small dependency allowing us to integrate Matomo in a more 'vue-way' instead of injecting the script ourselves. It also tracks page views automatically on navigation using the router, something we'd have to do manually otherwise (and has been missing so far, only first page load is tracked now).
- Add & implemement vue-matomo
- Remove old code
=> LXL-4560: use vue-matomo

packages/supersearch/e2e/supersearch.spec.ts, packages/supersearch/src/lib/components/CodeMirror.svelte, packages/supersearch/src/lib/components/SuperSearch.svelte, packages/supersearch/src/lib/utils/isViewUpdateFromUserInput.ts
[LWS-267](https://kbse.atlassian.net/browse/LWS-267)
Adds a expanded search dialog with synced/mirrored editor state. The dialog opens up if the user clicks or types in the collapsed editor view.
The search dialog is still extremely rudimentary but will get more functionality while working on [LWS-265](https://kbse.atlassian.net/browse/LWS-265).
- Add expanded search dialog
- Add synced/mirrored editor views
- Keep selection when expanding/collapsing dialog
- Add tests
- Allow word-selection by double-clicking on collapsed editor
=> LWS-267: Expanded search dialog with synced/mirrored editor state

cataloging/src/store.js, cataloging/src/utils/data.js
When copying a record, any missing references are fetched and added to quoted. Copying a record with many links was slow (so slow that you get a browser warning). Because each thing added to quoted would be a commit on the store and also clone the whole quoted object. Instead make it possible to pass an array of things to `addToQuoted` to be commited at once.
[LXL-4576](https://kbse.atlassian.net/browse/LXL-4576)
=> fix(cataloging): Some records are slow to copy

cataloging/package.json, cataloging/src/views/Help.vue, cataloging/yarn.lock
The fragment links on the help pages stopped working because `marked` moved heading ID generation to a separate package: https://www.npmjs.com/package/marked-gfm-heading-id
https://kbse.atlassian.net/browse/LXL-4589
=> Fix helpdocs heading ID generation

cataloging/src/router.js
In Firefox if you go to e.g. https://libris-dev.kb.se/katalogisering/help/workflow-work you have to click on "Verkstyp" twice for it to actually scroll there. Not an issue in Chrome. This seems to fix it.
=> fix(cataloging): Fix fragment link scroll issue in Firefox

packages/supersearch/src/lib/extensions/lxlQualifierPlugin/insertQuotes.ts
Quotes are inserted when user has typed a qualifier and the value is still empty. But weirdness happens when user is trying to delete the quotes and we try to add them again. This allows deletion by only adding them on input.
(Maybe in the future we hide the quotes from the user altogether. But for now, this seems less buggy)
=> fix(supersearch): Allow deletion of inserted quotes

cataloging/src/components/care/bulk-changes.vue, cataloging/src/resources/json/i18n.json, cataloging/src/utils/http.js
Bulk preview
* try again on response with totalItems: 0, _complete: false
* try again on connection / HTTP error + show a small error indicator
[LXL-4598](https://kbse.atlassian.net/browse/LXL-4598)
=> fix(cataloging-bulk): retry preview on empty, non-complete or error

packages/codemirror-lang-lxlquery/src/syntax.grammar, packages/codemirror-lang-lxlquery/test/cases.txt
A `BooleanQuery` can contain `Group`, which we did not specify in the grammar.
* Addition to lxlquery grammar
* Add a test
=> fix(lxlquery): Allow groups in boolean query

packages/codemirror-lang-lxlquery/README.md, packages/codemirror-lang-lxlquery/package.json, packages/supersearch/README.md, packages/supersearch/package.json
Running `npm run watch` in /supersearch and /codemirror-lang-lxlquery enables instant updates in lxlweb on changes.
* Add watch script
* Update readme (changed the language readme from boilerplate to something more customized)
=> chore(supersearch, lxlquery): Add watch scripts

lxl-web/src/lib/types/search.ts, lxl-web/src/lib/utils/search.ts
Frontend tests were failing because of API changes added in https://github.com/libris/librisxl/pull/1541
Basically the lack of `@id` for an invalid property caused the 500 error page to show instead of expected 400.
However, when fixing this and using 'old search' the resulting page for an invalid query is now this:
We figured as long as supersearch is not fully implemented, users still want some kind of feedback when using invalid queries. Therefore manually (temporarily) showing the same error page as before. This also makes tests pass.
ping @olovy @kwahlin 
* Add interface for `InvalidProperty`
* Add `@id` check in search.ts
* In `search.ts`, when encountering an `_invalid` property, show error page with same message as before.
=> fix(lxlweb): Continue showing error page for _invalid when not using Supersearch

lxl-web/src/lib/styles/lxlquery.css, packages/codemirror-lang-lxlquery/src/index.ts, packages/codemirror-lang-lxlquery/src/syntax.grammar, packages/codemirror-lang-lxlquery/test/cases.txt
* Support a Wildcard as sole `QualifierValue`. For example 'Endast omslagsbild' filter `image:*`
* Support a Wildcard ending QualifierValue identifier and number. For example `title:kulturarv*`
* Also fixes syntax highlighting of `BooleanOperator` within a `BooleanQuery`.
* Update grammar
* Update/add grammar test
* Update tag highlighter
* Update `lxlquery.css`
=> fix(lxlquery): Support wildcard in qualifierValue

lxl-web/src/lib/components/Search.svelte
* Supersearch labels shown in the currenly selected language.
* Provide lang to supersearch endpoint
=> fix(lxlweb): Provide lang to supersearch endpoint

lxl-web/src/lib/styles/lxlquery.css, lxl-web/src/lib/types/search.ts, lxl-web/src/lib/utils/getLabelsFromMapping.svelte.ts, lxl-web/src/lib/utils/search.ts, packages/supersearch/README.md, packages/supersearch/src/lib/extensions/lxlQualifierPlugin/index.ts
[LWS-287](https://kbse.atlassian.net/browse/LWS-287)
With https://github.com/libris/librisxl/pull/1541, we now have a way to decisively say a property is invalid, and can have the red squiggly line to mean that, not just that no label was found for it.
This can so far only be tested with dev backend.
* Forward `@type: '_Invalid'` as a new key `invalid` to the frontend. Update `DisplayMapping` type accordingly.
* In the `GetLabelFunction`, match `invalid` for a certain key and return an invalid boolean. 
* Add a mark decoration if `invalid`.
* Update css somewhat.
=> fix(supersearch): Implement the _Invalid type (LWS-287)

lxl-web/src/lib/styles/lxlquery.css, lxl-web/src/routes/api/[[lang=lang]]/supersearch/getEditedRanges.ts, packages/codemirror-lang-lxlquery/src/index.ts, packages/codemirror-lang-lxlquery/src/lxlLinter.ts, packages/codemirror-lang-lxlquery/src/syntax.grammar, packages/codemirror-lang-lxlquery/test/cases.txt, packages/supersearch/src/lib/extensions/lxlQualifierPlugin/index.ts, packages/supersearch/src/lib/extensions/lxlQualifierPlugin/insertQuotes.ts
[LWS-292](https://kbse.atlassian.net/browse/LWS-292)
Upon discovering that the frontend language parsing was allowing stuff that the backend don't and vice versa, I tried to fill in the gaps in our grammar, but ended up rewriting the whole thing after inspecting the backend code.
see [source](https://github.com/libris/librisxl/blob/7990106ab2b5e5cfa49eee843c09847869e0d5b3/whelk-core/src/main/groovy/whelk/search2/parse/Parse.java#L7)
The root node now being `orcomb` (not exported), this exports pretty much the same nodes as before, but with more robust logic and less code. For example:
Used to be valid but is invalid:
`key>(sommar AND vinter)`
Used to be invalid but is valid:
`!(sommar AND vinter)`
The query language is clearly not settled (whitespace discussion), but with frontend/backend …
=> feat(lxlquery): Improve grammar + lint

lxl-web/src/hooks.server.ts, lxl-web/src/lib/components/find/EsExplain.svelte, lxl-web/src/lib/components/find/SearchCard.svelte, lxl-web/src/lib/components/find/SearchItemDebug.svelte, lxl-web/src/lib/types/search.ts, lxl-web/src/lib/types/userSettings.ts, lxl-web/src/lib/utils/search.ts, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.server.ts, lxl-web/src/routes/(app)/[[lang=lang]]/find/+page.server.ts
Add debug mode for relevancy scoring.
* For each hit display total and per field score. And a percentage that relates the score to other hits _on the same page_.
* (There is a backend bug that makes some field appear as e.g. "Synonym(hasTitle._str:hor hasTitle._str:")
* Enable (sticky) with query param `?_debug=esScore`, disable with `?_debug=false`
* this is a bit messy and buggy...
* Click the score to show/hide detailed score calculation
[LWS-296](https://kbse.atlassian.net/browse/LWS-296)
=> feat(lxl-web): Add debug mode for relevancy scoring

lxl-web/package.json, lxl-web/src/lib/assets/json/display-web.json, lxl-web/src/lib/components/SuggestionCard.svelte, lxl-web/src/lib/components/SuperSearchWrapper.svelte, lxl-web/src/lib/components/find/SearchCard.svelte, lxl-web/src/lib/utils/getInstanceData.test.ts, lxl-web/src/lib/utils/getInstanceData.ts, lxl-web/src/lib/utils/getTypeIcon.ts, lxl-web/src/lib/utils/search.ts, lxl-web/src/routes/(app)/[[lang=lang]]/SiteHeader.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/find/+page.server.ts, lxl-web/src/routes/api/[[lang=lang]]/supersearch/+server.ts, lxl-web/tailwind.config.js, package-lock.json
[LWS-321](https://kbse.atlassian.net/browse/LWS-321)
Adds decorated data to supersearch suggestions in the form of a `SuggestCard` component, basically a slimmed version of `SearchCard`. Now also fetching results for Work, Agent, Concept & Language types.
As a result of new types showing up, the web-card lenses needed adjustment. I chose a minimal approach, see examples below.
We also need to tweak relevance between types; a search for 'Mikael Yvesand' returns the Person as the last result.
Upgraded Svelte to be able to use the new more flexible class array syntax.
<br><br>
<br><br>
* Add component `SuggestionCard`
* Include more types to search, format data in /supersearch api route
* Tweak cards for Agent Concept, Language in display-web  + additional formatters
* Subsequent minor …
=> feat(lxlweb): Decorated suggestions (LWS-321)

lxl-web/src/routes/api/[[lang=lang]]/supersearch/getEditedRanges.test.ts, lxl-web/src/routes/api/[[lang=lang]]/supersearch/getEditedRanges.ts
Discovered a flaw in `getEditedRanges` that only recognizes editing a qualifier when the `innerNode` is a direct child of `qualifierValue`. This is however not always the case. Consider for example:
`contributor:(astrid lindgren)` that produces the tree `QualifierValue { Group { String String } }`. We're editing the `String` and the parent is `Group`.
This means we fail to narrow down the query to `_q=(astrid+lindgren)+"rdf:type":Agent` in this case.
And since the query in theory could be `contributor:(((((Astrid)))))`, we need to iterate the tree to se if the `innerNode` is located _somewhere_ inside a `qualifierValue`.   
* Iterate parents in `getEditedRanges`
* Add test to cover this use case
=> fix(lxlweb): iterate parents in getEditedRanges

cataloging/package.json, cataloging/src/components/layout/footer.vue, cataloging/src/main.js, cataloging/src/plugins/cookie-consent.js, cataloging/src/resources/json/i18n.json, cataloging/src/settings.js, cataloging/yarn.lock
[LXL-4596](https://kbse.atlassian.net/browse/LXL-4596)
Integrates [KB CookieConsent](https://github.com/Kungbib/cookie-consent) to handle Matomo cookies. AFAIK we don't use any other cookies.
* Change VueMatomo settings to require consent before sending anything
* Add Vue plugin for KB CookieConsent and use it; trigger VueMatomo using onConsent/onChange events
* Add "Manage cookies" link to footer to display cookie settings modal
I was told this only needs to be available in Swedish.
I just guessed that `settings.js` would be an appropriate place for the cookie consent settings, alternatives being having them directly in `app.js`, or `plugins/cookie-consent.js`, or...? :shrug:
=> feat(cataloging): Add KB CookieConsent

lxl-web/src/lib/components/SuperSearchWrapper.svelte, lxl-web/src/lib/types/search.ts, lxl-web/src/lib/utils/getLabelsFromMapping.svelte.ts, lxl-web/src/lib/utils/getLabelsFromMapping.test.ts, lxl-web/src/lib/utils/search.ts, lxl-web/src/routes/api/[[lang=lang]]/supersearch/+server.ts
[LWS-327](https://kbse.atlassian.net/browse/LWS-327)
Frontend implementation of https://github.com/libris/librisxl/pull/1553 that lets us match a qualifier key/value with its corresponding mapping object, label & removelink.
Try for example...
To type any key that the backend understands, for example `ämne:`
To add multiple 'contributor' filters from the facets (no more mixed up labels)
* Implement search.mapping `_key` & `_value`
* Update test
* Fix bug in supersearch input field where many pills pushed away the search button 🙃
=> fix(lxlweb): implement mapping _key _value (LWS-327)

cataloging/src/components/inspector/field-adder.vue, cataloging/src/components/inspector/property-adder.vue
[LXL-4615](https://kbse.atlassian.net/browse/LXL-4615)
The change in https://github.com/libris/lxlviewer/pull/1209 was apparently not enough to hide the autocomplete box in Chrome – hopefully changing the input type to `"search"` (instead of `"text"`) will resolve it.
- Set adder input type to search
=> feat(cataloging): Set adder input type to search (LXL-4615) 

lxl-web/src/lib/components/SuggestionCard.svelte, lxl-web/src/lib/components/SuperSearchWrapper.svelte, lxl-web/src/lib/components/find/SearchResult.svelte, lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/lib/types/search.ts, lxl-web/src/lib/utils/getLabelsFromMapping.svelte.ts, lxl-web/src/lib/utils/search.ts, lxl-web/src/lib/utils/xl.ts, lxl-web/src/routes/api/[[lang=lang]]/supersearch/+server.ts, lxl-web/src/routes/api/[[lang=lang]]/supersearch/getEditedPartEntries.test.ts, lxl-web/src/routes/api/[[lang=lang]]/supersearch/getEditedPartEntries.ts, lxl-web/src/routes/api/[[lang=lang]]/supersearch/itemAsQualifiers.test.ts, lxl-web/src/routes/api/[[lang=lang]]/supersearch/itemAsQualifiers.ts, lxl-web/src/routes/api/[[lang=lang]]/supersearch/qualifierMappings.ts, packages/supersearch/src/lib/types/superSearch.ts
[LWS-324](https://kbse.atlassian.net/browse/LWS-324)
Enables adding qualifiers to the query from the result suggestions. 
This is done by extending the response from the proxy api /supersearch route with a list of possible qualifiers for each item. The qualifiers are decided by the same [mapping](https://github.com/libris/lxlviewer/blob/2fa377333f16ebf351a65b2ba778b519ae701dcf/lxl-web/src/routes/api/%5B%5Blang%3Dlang%5D%5D/supersearch/qualifierMappings.ts#L8) that decides what type to search for when editing a qualifier, but in reverse (maybe this and [the prefix mapping](https://github.com/libris/lxlviewer/blob/2fa377333f16ebf351a65b2ba778b519ae701dcf/lxl-web/src/routes/api/%5B%5Blang%3Dlang%5D%5D/supersearch/itemAsQualifiers.ts#L13) should not be done in the frontend at all. Let's …
=> feat(lxlweb): add suggestion qualifiers to query

lxl-web/src/lib/components/find/SearchResult.svelte, lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js
TODO
Doesn't take the type into account. So it is also displayed when searching for e.g. Person
But that is also the case for sort.publicationDesc/sort.publicationAsc
Depends on https://github.com/libris/librisxl/pull/1560
[LWS-169](https://kbse.atlassian.net/browse/LWS-169)
=> feat(lxl-web): Add option to sort (works) on number of holdings

lxl-web/src/lib/components/SuperSearchWrapper.svelte, packages/supersearch/src/lib/components/CodeMirror.svelte, packages/supersearch/src/lib/components/SuperSearch.svelte, packages/supersearch/src/lib/extensions/lxlQualifierPlugin/insertQuotes.ts
[LWS-324](https://kbse.atlassian.net/browse/LWS-324)
Moves cursor after adding qualifiers. This is done by [dispatching changes](https://github.com/libris/lxlviewer/pull/1229/files#diff-eb1ad9ef8cb971563e0b0fdc86232ded17a2a2c7224467a53d45de62547aaa09R89-R93) instead of relying on the [reset effect](https://github.com/libris/lxlviewer/blob/7540d6a9bb19d64e2585433bf1cf9d4b1c9a7e2b/packages/supersearch/src/lib/components/CodeMirror.svelte#L97-L102) (which was triggered when the value changes from outside = when the URL changes).
There is a short flash of unformatted content when adding a qualifier but this could maybe be mitigated by using the label from the qualifier suggestion instead.
- Add qualifiers using dispatchChange
- Make change param optional (to allow selection-only changes
- Fix …
=> feat(lxl-web): Move cursor after adding qualifiers (LWS-324)

lxl-web/src/lib/components/find/SearchResult.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/SiteHeader.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/find/+page.svelte
[LWS-329](https://kbse.atlassian.net/browse/LWS-329)
Prepares lxl-web for the first QA-release of the supersearch component.
- Fix layout on start page
- Hide mapping on find pages if supersearch is enabled (but keep them on resource pages)
- Allow mappings to be shown if `_x`  search param is set to `mappings`
=> feat(lxl-web): Prepare QA-release of supersearch (LWS-329)

packages/supersearch/e2e/supersearch.spec.ts, packages/supersearch/src/lib/components/SuperSearch.svelte, packages/supersearch/src/lib/extensions/arrowKeyCursorHandling.ts
[LWS-330](https://kbse.atlassian.net/browse/LWS-330)
Adds arrow key cursor handling.
Arrow up and down to jump to the start and end of the string is prevented if the expanded search is open.
Arrow left and right cursor movement is prevented if there are more than one cell/column on the active row.
-  Add arrow key cursor handling
=> feat(supersearch): Add arrow key cursor handling (LWS-330)

lxl-web/src/lib/utils/xl.ts
Some queries cause the app to break, which is becoming more evident with supersearch.
For example a wildcard search for genreForm:
https://beta.libris-qa.kb.se/find?_i=&_q=%22rdf:type%22:GenreForm&_limit=20&_x=advanced&_spell=true
Caused by `lxljsVocab.getTermObject` requiring a `name` string, while arrays exist as `@type` among old MARC terms.
for example
```
[
'marc:SerialsNatureType',
'marc:BooksContentsType',
'marc:SerialsContentsType'
]
```
We could also call the function with `name[0]` in these cases, dunno what's better?
* string check in xl.ts `getDefinition`
=> fix(lxlweb): string check in getDefinition

lxl-web/src/lib/components/find/SearchResult.svelte, lxl-web/src/lib/types/search.ts, lxl-web/src/lib/utils/search.ts, lxl-web/src/routes/api/[[lang=lang]]/supersearch/+server.ts
Frontend implementation of https://github.com/libris/librisxl/pull/1566
* Set `_stats=false` for api/supersearch requests
* omit `facetGroups` and `predicates` from response if stats is missing
* modify `SearchResult` type and component accordingly
=> fix(lxlweb): set _stats to false

cataloging/src/components/inspector/field.vue, cataloging/src/resources/json/i18n.json, cataloging/src/resources/json/protectedProperties.json
Make it more clear that "protected" properties are always locked, and can temporarily be unlocked for editing.
Some users thought that it was necessary to click the lock icon for a property to become locked again, and that this affected other users; hence this possibility is removed. 
Also, these properties are reset to their default locked state on save, cancel or save+done editing, for clarity.
=> feat(cataloging): Make locked properties handling more clear

packages/supersearch/src/lib/components/SuperSearch.svelte
[LWS-278](https://kbse.atlassian.net/browse/LWS-278)
Prevent setting default row on start content
- Prevent setting default row on start content
=> fix(supersearch): Prevent setting default row on start content (LWS-278)

lxl-web/src/lib/components/SuperSearchWrapper.svelte, packages/supersearch/src/lib/extensions/lxlQualifierPlugin/insertSpaceAroundQualifier.ts
Hide the fallback wildcard that appears when removing all filter pills.
It's especially annoying because of all the weird suggestions it brings up...
* Don't dispatch '*' when removing qualifier
* Don't set `q` to '*' when syncing after route change
=> fix(lxlweb): Hide lone wildcard from supersearch input

lxl-web/src/lib/components/supersearch/SuperSearchWrapper.svelte
Minor stuff to improve supersearch user experience
* Reduce `debounceWait` from 300 to 100 ms
* comment out 'loading' snippet
=> fix(lxlweb): Reduce debouceWait, disable loading indicator

lxl-web/src/lib/components/supersearch/Suggestion.svelte, lxl-web/src/lib/components/supersearch/SuperSearchWrapper.svelte
**Bug:** Typing 'a' in the supersearch input does not generate suggestions (but a console error)
**Fix:** `typStr` check
**Bug:** From the start screen, type `språk:svenska` and add Svenska. The following result page shows 200 hits.
**Fix:** make `getFullQualifierLink` function use the groomed `pageParams` value (fixed below)
**Bug:** Type `språk:svenska` and add Svenska. Change the sorting to something else. Click qualifier remove btn. The sorting is now reverted back.
**Fix:** `removeQualifier` relied on the `params` variable which is set on page load and not reactive (to client side navigations like sort changes). Make it derived by search params state. Also rename `params`/`searchParams` since the component contain many (other) variables of the same name.
* `item.typeStr` check
* Make …
=> fix(lxlweb): SuperSearchWrapper bugs

lxl-web/src/routes/api/[[lang=lang]]/supersearch/getEditedPartEntries.test.ts, lxl-web/src/routes/api/[[lang=lang]]/supersearch/getEditedPartEntries.ts
[LWS-346](https://kbse.atlassian.net/browse/LWS-346)
Adds a work-around so results for e.g. `contributor:"Astrid Lindgren"` are shown.
This is done by unquoting the qualifier value so it is treated as _Astrid AND Lindgren_ instead of the exact phrase _"Astrid Lindgren"_ (the latter doesn't give any results as the search index uses _last name + first name_ instead of _first name + last name_).
This should only be seen as a temporary work-around as it's probably better to replace the automatically inserted quotes with (hidden?) parenthesis.
- Unquote qualifier values
=> fix(lxl-web): Unquote qualifier values (LWS-346)

lxl-web/src/routes/api/[[lang=lang]]/supersearch/getEditedPartEntries.test.ts, lxl-web/src/routes/api/[[lang=lang]]/supersearch/getEditedPartEntries.ts
[LWS-335](https://kbse.atlassian.net/browse/LWS-335)
Adds wildcard when searching for qualifiers (solves issue with `contributor:"astrid lindgr"` not giving relevant results).
- Add trailing wildcard asterisk when searching for qualifiers
=> feat(lxl-web): Add wildcard when searching for qualifiers (LWS-335)

idkbse/src/plugins/env.js
Terms with a `'` in their prefLabel 404, for example:
* https://id.kb.se/term/gmgpc/swe/%C3%89preuves%20d'artiste
* https://id.kb.se/term/saogf/Rock'n'roll
Looking with tcpflow, the idkbse app sends a request to the backend for `https://id.kb.se/term/saogf/Rock'n'roll` rather than (the correct) `https://id.kb.se/term/saogf/Rock%27n%27roll`. So, this should fix it.
=> fix(idkbse): encode single quote char in requests to backend

lxl-web/src/lib/components/Error.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.server.ts, lxl-web/tests/error.spec.ts
e2e-test failing now because we expect a 404-page at https://beta.libris-qa.kb.se/aaaaaaaaaaaaaaa, but for some reason getting a [502 html page](https://libris-qa.kb.se/aaaaaaaaaaaaaaa?framed=true) that we fail to parse as json, resulting in a 500 internal error page...
Changing the cursed /aaaaaaaaaaaaaaa route in the test, because any other non-existent fnurgel seems to result in 404 as expected.
* Change 404 route in test
* try/catch the error parsing to be able to display the actual error
* Replace deprecated app/stores `$page` in Error component
=> fix(lxlweb): catch parsing error, fix failing test

packages/supersearch/e2e/supersearch.spec.ts
Temporarily disable test which breaks on CI for some odd reason (but works on localhost)... :(
We need to investigate why... (probably due some missing async await)
- Temporarily disable test which breaks only on CI
=> chore(supersearch): Temporarily disable test which breaks on CI only

lxl-web/src/lib/components/supersearch/SuperSearchWrapper.svelte, packages/supersearch/src/lib/components/CodeMirror.svelte, packages/supersearch/src/lib/components/SuperSearch.svelte, packages/supersearch/src/lib/index.ts, packages/supersearch/src/lib/types/superSearch.ts, packages/supersearch/src/lib/utils/isViewUpdateOfUserEvent.ts
Replaces bindable cursor prop with a selection event handler
- Add select event handler
- Use selection head instead of anchor for cursor
- Replace bindable cursor prop
- Use selection inside handleShouldShowStartContent
- Skip redundant selection sync
- Hide result items when text is selected
- Look both left and right when deciding if editing a part of query
=> feat(supersearch): Add select event handler 

lxl-web/src/lib/styles/lxlquery.css, lxl-web/src/lib/types/search.ts, lxl-web/src/lib/utils/getLabelsFromMapping.svelte.ts, lxl-web/src/lib/utils/search.ts, packages/codemirror-lang-lxlquery/src/syntax.grammar, packages/codemirror-lang-lxlquery/test/cases.txt, packages/supersearch/README.md, packages/supersearch/src/lib/extensions/lxlQualifierPlugin/QualifierComponent.svelte, packages/supersearch/src/lib/extensions/lxlQualifierPlugin/index.ts, packages/supersearch/src/lib/extensions/lxlQualifierPlugin/insertSpaceAroundQualifier.ts
[LWS-347](https://kbse.atlassian.net/browse/LWS-347), [LWS-313](https://kbse.atlassian.net/browse/LWS-313)
Handle filter aliases in supersearch like so:
When myLibs is available as a filter alias, we should be able to just add it to the grammar file.
* `Search.ts`: return `displayStr` and `_value` properties for `mapping.object`s
* `syntax.grammar`: define `filterAlias` as a type of `QualifierValue`. Update tests.
* `getLabelsFromMappings`:  can now return only a value label.
*  `lxlQualifierPlugin`: now creates an atomic decoration from just the value label.
* `QualifierComponent`: Enable rendering a value label only.
=> feat(lxlweb, supersearch, lxlquery): Handle filter alias in supersearch

lxl-web/src/lib/components/find/Filters.svelte, lxl-web/src/lib/components/find/MyLibrariesFilter.svelte, lxl-web/src/lib/components/find/SearchMapping.svelte, lxl-web/src/lib/constants/facets.ts, lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/lib/types/search.ts, lxl-web/src/lib/utils/search.ts, lxl-web/src/routes/(app)/[[lang=lang]]/find/+page.server.ts, packages/codemirror-lang-lxlquery/src/syntax.grammar
[LWS-313](https://kbse.atlassian.net/browse/LWS-313)
Frontend implementation of filter alias API feature (https://github.com/libris/librisxl/pull/1581), also a continuation of https://github.com/libris/lxlviewer/pull/1273.
1. If `alias-myLibraries` is present in `_q`, append myLibraries cookie values to secret param before fetch to search api: `_alias-myLibraries=(itemHeldBy:"sigel:X" OR itemHeldBy:"sigel:Y")`.
2. The response then includes the alias in search mapping, but has no label since it is a custom filter that's not hardcoded into the backend. Allow `displayStr` to look for the value label in the frontend translation files.
3. Add `alias-myLibraries` as a reserved qualifier term in lxlquery grammar. It will then pick up the label from search mapping:
4. Modify `MyLibrariesFilter` …
=> feat(lxlweb, lxlquery): Implement alias-myLibraries in frontend (LWS-313)

lxl-web/src/lib/utils/search.ts, packages/codemirror-lang-lxlquery/src/syntax.grammar
[LWS-242](https://kbse.atlassian.net/browse/LWS-242)
Frontend support for free e-resource filter defined in https://github.com/libris/definitions/pull/525. Other suggestions for a descriptive name of the filter are welcome.  
* Add `freeDigital` filter to grammar
=> Support new filter for free digital material

lxl-web/src/app.css, lxl-web/src/lib/components/Modal.svelte, lxl-web/src/lib/components/MyLibsHoldingIndicator.svelte, lxl-web/src/lib/components/ResourceImage.svelte, lxl-web/src/lib/components/find/MyLibrariesFilter.svelte, lxl-web/src/lib/components/find/SearchRelated.svelte, lxl-web/src/lib/components/find/SearchResult.svelte, lxl-web/src/lib/components/my-pages/Libraries.svelte, lxl-web/src/lib/components/supersearch/Suggestion.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/HeaderMenu.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/SiteFooter.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/SiteHeader.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/InstancesList.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/InstancesListContent.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/my-pages/+page.svelte
Follow-up PR to https://github.com/libris/lxlviewer/pull/1285.
Adjusts custom breakpoints so they are more inline with the Tailwind defaults.
- Custom `--breakpoint-md` has been removed in favour of default `lg` which had the same value (64rem / 1024px)
- Custom `--breakpoint-lg` has become `--breakpoint-2xl` so we can keep the default lg value.
- Custom `--breakpoint-xl` has become newly added `--breakpoint-3xl` so we can keep the default xl value.
So the available breakpoint prefixes are now:
| Breakpoint prefix | Minimum width |
| ------------- | ------------- |
| `sm`| `40 rem (640px)`|
| `md`| `48rem (768px)`|
| `lg`| `64rem (1024px)`|
| `xl`| `80rem (1280px)`|
| `2xl`| `90rem (1440px)` – overriding the default 1536px|
| `3xl`| `110rem (1760px)`|
=> feat(lxlweb): Redesign theme - adjust breakpoints

lxl-web/package.json, packages/supersearch/package.json
Removes redundant vite override as it seems to work as intended without it?
The esbuild dependency in vite was bumped in february (see: https://github.com/vitejs/vite/pull/19389).
- Remove redundant vite override
=> chore(lxl-web, supersearch): Remove redundant vite override

lxl-web/src/app.css, lxl-web/src/lib/components/Modal.svelte, lxl-web/src/lib/components/supersearch/SuperSearchWrapper.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/SiteHeader.svelte, packages/supersearch/src/lib/components/SuperSearch.svelte
[LWS-366](https://kbse.atlassian.net/browse/LWS-366), [LWS-367](https://kbse.atlassian.net/browse/LWS-367)
Hides the regular input < sm, adds an icon button that opens expanded search instead.
Remove page padding for supersearch dialog < sm, using the whole width.
The `SiteHeader` component including the old theme layout styles (`.header-layout`) is really a confusing patchwork of old styles to keep supersearch-dialog in place. It should soon be completely rewritten based on the new design.
With input now hidden < sm, expanded search must remain open after selecting from the start menu. This does however display search results from a wildcard search on the chosen type. 
Maybe nice in his case
Weird in this case 🤔 
* Add id `{id}` to the outer (non-dialog) supersearch element. Use it to …
=> fix(lxlweb): Show search icon, remove dialog margin (LWS-366, LWS-367)

lxl-web/src/app.css, lxl-web/src/lib/components/Modal.svelte, lxl-web/src/lib/components/find/SearchCard.svelte, lxl-web/src/lib/components/find/SearchMapping.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.svelte
[LWS-368(https://kbse.atlassian.net/browse/LWS-368), [LWS-371](https://kbse.atlassian.net/browse/LWS-71)
* Remove left and right padding on search cards for small screens
* Prevent modal from scrolling horizontally
* Truncate mapping pills if overflowing (in filter panel on mobile)
* Allow long ext-links to break [bad mobile example](https://beta.libris.kb.se/l3z7f4j1jbz1hxbv#work-record)
* Allow contributors to wrap in overview [bad mobile example](https://beta.libris-qa.kb.se/6pzc3mjl4gzdxqrt)
=> fix(lxlweb): Adjust padding & overflow (LWS-368, 371)

packages/supersearch/src/lib/components/SuperSearch.svelte
[LWS-370](https://kbse.atlassian.net/browse/LWS-370)
Swapping inputmode for [enterkeyhint](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes/enterkeyhint) seems to be the only way to get a 'search' btn for a contenteditable div in IOS at least 🤷‍♂️
=> fix(supersearch): Get virtual search keyboard (LWS-370)

lxl-web/src/lib/actions/popover/Popover.svelte
[LWS-376](https://kbse.atlassian.net/browse/LWS-376)
Hide link popovers for touch devices since they're of no use anyway.
(We also use popovers for buttons (focus-triggered), but they work on mobile since they don't trigger navigations)
Add a class if popover is attached to a link. Hide those popovers for devices where hover is unsupported.
=> fix(lxlweb): Hide link popovers for touch devices (LWS-376)

lxl-web/src/lib/components/Spinner.svelte, lxl-web/src/lib/components/supersearch/SuperSearchWrapper.svelte, packages/supersearch/src/lib/utils/useSearchRequest.svelte.ts
[LWS-362](https://kbse.atlassian.net/browse/LWS-362)
Implement a loading spinner for suggestions in Supersearch.
* Create new pure CSS `Spinner` component
* Add `isLoading` state and bind to supersearch component
* Create `debouncedLoading` state to avoid spinner flickering, use it to render spinner
* Some modifications to `useSearchRequest`*
* Add `top:0` for expanded supersearch on mobile
\* an aborted request was sometimes setting `isLoading` to false, even though a newer request was out pending. Added a sort of counter to make sure the request is the latest one before setting loading to false.
=> feat(lxlweb, supersearch): Supersearch loading spinner

lxl-web/src/app.css, lxl-web/src/lib/assets/json/display-web.json, lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/lib/types/holdings.ts, lxl-web/src/lib/types/xl.ts, lxl-web/src/lib/utils/holdersCache.svelte.ts, lxl-web/src/lib/utils/holdings.test.ts, lxl-web/src/lib/utils/holdings.ts, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.server.ts, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/HoldingAvailability.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/HoldingInfo.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/HoldingStatus.svelte
[LWS-249](https://kbse.atlassian.net/browse/LWS-249)
The goal is to provide access to items in the local library catalog as well as additional library info such as address, opening hours etc. This is currently presented in the holding panel:
* Construct a mapping for library code (sigel) to the links/info on fnurgel page load 
* Tried to keep close to the Figma sketches for the frontend part
* Add a basic server side caching mechanism for full holder/library data. There is plenty of information about caching in the browser in a SvelteKit context but not so much about caching on the server. The approach used in this PR comes from https://www.loopwerk.io/articles/2025/svelte-5-stores/, which should be fine since the data we are caching is not tied to a specific user/session/browser. I think …
=> Display links to things in local systems

lxl-web/src/lib/components/DecoratedDataLite.svelte, lxl-web/src/lib/components/find/FacetGroup.svelte, lxl-web/src/lib/types/xl.ts, lxl-web/src/lib/utils/search.ts, lxl-web/src/lib/utils/xl.ts
Add an experimental light-weight format for decorated data. Use it for facet values. This shaves ~300kb off of the response when doing a *-query.
data is either
* plain string
* string + array of style names
Nested data is just converted to strings for now.
example
```
[
"Uppsala universitetsbibliotek",
", Ekonomikums bibliotek",
[" (Ue)", ["sigel"]]
]
```
For facet values there is already a parameter "discriminator" that is ued for `inScheme`. Another option would be to use that for sigel as well.
=> feat(lxl-web): Use light-weight decorated data for facet values

cataloging/src/resources/json/combinedTemplates.json
Suggest template for printed poster (tryckt affisch)
Copy StillImage template and removed unnecessary steps described in https://metadatabyran.kb.se/arbetsfloden/affischer
(Current normalization efforts has not been taken into account)
=> Suggest template for printed poster

lxl-web/src/lib/components/supersearch/SuperSearchWrapper.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/SiteHeader.svelte
/find page looks different on mobile with language set to english 🤔 
Because the flawed `isFindRoute` does not match route /en/find...
I guess `route.id` is a more reliable thing to check.
* Check `isFindPage` using route id instead of url pathname
=> fix(lxlweb): Fix isFindPage route check

packages/supersearch/src/lib/components/SuperSearch.svelte, packages/supersearch/src/lib/utils/useSearchRequest.svelte.ts
[LWS-379](https://kbse.atlassian.net/browse/LWS-379)
Fixes flashes of wildcard results which could appear while searching (e.g. when the user types after having added a qualifier).
- Call `shouldShowStartContentFn` only once
- Fix flash of wildcard results when searching
=> fix(lxl-web): Wildcard flash when searching (LWS-379)

lxl-web/src/lib/components/find/FacetGroup.svelte, lxl-web/src/lib/components/find/FacetValue.svelte, lxl-web/src/lib/components/find/Filters.svelte, lxl-web/src/lib/components/find/MyLibrariesFilter.svelte, lxl-web/src/lib/constants/facets.ts, lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/lib/types/search.ts, lxl-web/src/lib/types/userSettings.ts, lxl-web/src/lib/utils/search.ts, lxl-web/src/lib/utils/userSettings.svelte.ts, lxl-web/tests/find.spec.ts
- Save facet expanded state in userSettings. Default to 4 first open
- Fix bug where facets were not expanded during "find facet" filtering.
- Place 'free online' inside a new "Access" facet
- Until we have a more detailed design
- Add new FacetValue component (still TODO to rename FacetGroup -> Facet)
- this refactoring was because of the abandoned idea to place "free online" inside the myLibraries box. Could be reverted.
=> feat(lxlweb/facets): Save facet expanded state. Move free online to top.

lxl-web/src/lib/components/supersearch/SuperSearchWrapper.svelte, lxl-web/tests/supersearch-lxlweb.spec.ts, packages/supersearch/e2e/supersearch.spec.ts, packages/supersearch/src/lib/components/SuperSearch.svelte, packages/supersearch/src/routes/+page.svelte
Improves the keyboard navigation in the supersearch component (adhering to more cases from the [Combobox Pattern in the ARIA Authoring Practices Guide](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/)).
The user can now jump from the first row to the last using `arrow up`, and vice versa jump from the last row to the first by pressing `arrow down`.
~~The `control key` (or `meta key` if on mac) combined with either `arrow up` or `arrow down` can be used to quickly jump the first or last row.~~
And finally, `Alt` + `arrow up` or `arrow down` can toggle the expanded search without moving the cursor.
- Add support for wrapping arrow key navigation
- Clearer focused styling of input row
- ~~Add support for jumping to start/end using control/meta + arrow keys~~
- Alt + arrow keys toggles …
=> feat(supersearch, lxl-web): Improved search keyboard navigation

cataloging/src/components/shared/id-pill.vue, cataloging/src/utils/record.js
Some id.kb.se terms were displayed weirdly because they contained exactly 15 or 16 characters and were treated as fnurgels. Fix that + also decode URIs while we're at it (or?). 
https://kbse.atlassian.net/browse/LXL-3786
=> fix(cataloging): don't treat certain terms as fnurgels

lxl-web/src/lib/components/Toolbar.svelte
Simplifies the toolbar component.
- Unnecessarily rendered empty list elements are removed (they were previously rendered if any of the snippet props were undefined).
- The list elements are reworked into normal div elements as it isn't certain that the contents of the toolbar makes sense in the context of a list. However, feel free to add lists _inside_ the leadingActions/trailingActions snippets e.g. lists of toolbar buttons).
- The `centerActions` snippet prop is removed in favour of normal children props.
=> feat(lxl-web): Simplified toolbar component

lxl-web/src/app.css, lxl-web/src/lib/components/Resource.svelte, lxl-web/src/lib/components/SearchResultList.svelte
[LWS-402](https://kbse.atlassian.net/browse/LWS-402)
Adds scroll buttons on horizontal lists indicating that the lists are scrollable.
The scroll buttons are only shown when the user has at least one accurate input pointing device (such as a mouse) and hovers over the lists.
The scroll buttons are therefor hidden on mobile devices where users are more accustomed to horizontally scrollable sections.
The new [::scroll-button](https://developer.mozilla.org/en-US/docs/Web/CSS/::scroll-button) CSS psuedo element could have been used to remove the need for JavaScript but sadly the support is still quite lacking ([64.34% at the time of writing according to caniuse.com](https://caniuse.com/mdn-css_selectors_scroll-button)).
For now, the scroll-buttons are instead hidden if Javascript is disabled. …
=> feat(lxl-web): Scroll buttons on horizontal lists (LWS-402)

lxl-web/src/routes/(app)/[[lang=lang]]/AppBar.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/HeaderMenu.svelte
[LWS-374](https://kbse.atlassian.net/browse/LWS-374)
Fixes page becoming unresponsive when toggling the modal menu from hamburger icon and then widening the window so that it disappears.
Easiest solution is to move the modal element outside of the `div` that becomes visually hidden on large screens. Once toggled, it will then remain visible regardless of screen width and can be closed.
Also tweaked the header menu styling, now depending on if it's inside of a `dialog`, rather than the page width.
* Move Modal component
* Modify css
=> bugfix(lxlweb): Header menu causing unresponsive page (LWS-374)

lxl-web/package.json, lxl-web/src/app.css, lxl-web/src/app.d.ts, lxl-web/src/lib/components/Resource.svelte, lxl-web/src/lib/components/TableOfContents.svelte, lxl-web/src/lib/components/find/SearchCard.svelte, lxl-web/src/lib/components/resource/AdjecentResults.svelte, lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/lib/remotes/adjecentSearchResult.remote.ts, lxl-web/src/lib/types/search.ts, lxl-web/src/lib/utils/adjecentSearchResult.ts, lxl-web/src/lib/utils/search.ts, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.svelte, lxl-web/svelte.config.js, lxl-web/tests/navigation-between-results.spec.ts, package-lock.json
[LWS-221](https://kbse.atlassian.net/browse/LWS-221)
Adds navigation between search result items on the resource page.
It works by passing along the search results data (with only the data which is needed) when clicking on a search result link on the `/find` page. This data is then used to calculate the previous/next result fnurgel and index of total results.
Subsequent searches are done if the user navigates to results which aren't part of the original search results. SvelteKit's newly added [remote functions](https://svelte.dev/docs/kit/remote-functions) are used here for the sake of simplicity; the feature is however still experimental but hopefully won't change too much in upcoming SvelteKit versions. 🤞 
- Pass along search result when navigating to resource page (using `page.state`) …
=> feat(lxl-web): Navigation between results (LWS-221)

lxl-web/README.md, lxl-web/package.json
Skip prebuilding local dependencies (e.g. `packages/supersearch` and `packages/codemirror-lang-lxlquery`) when running `npm run dev` due to popular demand (as it takes a couple of extra seconds and waiting is no fun...)
Prebuilding is however still done on `npm run build` so everything in https://github.com/libris/lxlviewer/pull/1349 is not reverted.
- Skip prebuilding local dependencies when running `npm run dev`
- Update readme (add step regarding prebuilding)
=> chore(lxl-web): Skip prebuilding local dependencies on dev

.github/workflows/lxl-web.yml, lxl-web/tests/find.spec.ts
Upload artifacts in the form of playwright traces after CI run.
To use it:
1. Goto a run [summary](https://github.com/libris/lxlviewer/actions/runs/17763324204)
2. Scroll down to the artifacts section and download playwright-traces.zip
3. Unpack it and drag a trace.zip into https://trace.playwright.dev/ (can also be run locally)
=> chore(lxl-web): Try fixing uploading playwright traces

cataloging/src/views/Inspector.vue
[LXL-4689](https://kbse.atlassian.net/browse/LXL-4689)
When navigating to a holding directly from the search hitlist, then removing it, the user is navigated back to the hitlist. In the search card of the record for which the holding was `itemOf`, the button for creating a new holding was not available (instead this button stated, incorrectly, that the user still had a holding for this record).
Add 1000ms timeout.
=> Wait 1 second before loading search hitlist after removing a record

lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.svelte
Should fix the following bug:
1. Go to /btmbf3tn24ln737#work-record
2. Navigate to "Upp & ner"
3. Modal still shows one holding even though there are 9.
(Sometimes the library info is missing when hitting a resource page directly. Proposed fix for that is [here](https://github.com/libris/lxlviewer/pull/1380) )
* Make holdings variable a `$derived` of the page data
=> bugfix(lxlweb): Update holdings data after navigating between resources
