libris/lxlviewer

viewer/v2client/src/components/Inspector.vue, viewer/v2client/src/components/inspector/entity-adder.vue, viewer/v2client/src/components/inspector/field-adder.vue, viewer/v2client/src/components/inspector/item-value.vue, viewer/v2client/src/components/inspector/search-window.vue, viewer/v2client/src/components/inspector/summary-action.vue, viewer/v2client/src/components/shared/entity-summary.vue, viewer/v2client/src/store/store.js
This feature also contains an unsavedChanges status.
=> Linking entities now works

viewer/v2client/src/components/LandingPage.vue, viewer/v2client/src/components/inspector/item-value.vue, viewer/v2client/src/components/search/link-card.vue
=> Make repeatable fields a little better looking

viewer/helpdocs/terminology-phrasebook-short.md, viewer/v2client/src/components/Help.vue
Tables now render prettier :) and the menu has bigger text. I also created SUIT classes on elements.
=> Styling for content in help

viewer/v2client/src/components/inspector/field.vue, viewer/v2client/src/components/inspector/item-entity.vue, viewer/v2client/src/components/inspector/item-vocab.vue, viewer/v2client/src/components/mixins/item-mixin.vue
- Added state class name prefix according to SUIT
- Removed unused silly method
- Added unsaved changes status push for item vocab change
- Added unsaved changes status push for removal of item entities
=> Add unsaved changes status on entity removal and vocab change

viewer/v2client/src/components/layout/footer.vue
Removed jquery code and added some other code to make strings in footer translatable again.
=> Translate strings in footer

viewer/v2client/src/components/inspector/entity-adder.vue, viewer/v2client/src/components/inspector/entity-form.vue, viewer/v2client/src/store/store.js, viewer/v2client/src/utils/vocab.js
* Use curie in search
* Cache mechanism for subClassChains (improves performance A LOT).
=> Vocab fixes

viewer/v2client/src/components/LandingPage.vue, viewer/v2client/src/components/layout/footer.vue, viewer/v2client/src/components/layout/navbar.vue, viewer/v2client/src/components/search/link-card.vue, viewer/v2client/src/components/search/search-form.vue
More responsive seacrhfom, navbar and footer
=> Make footer and searchform responsive

viewer/v2client/src/components/inspector/field-adder.vue, viewer/v2client/src/components/inspector/field.vue, viewer/v2client/src/components/inspector/item-boolean.vue, viewer/v2client/src/resources/json/i18n.json
* Adds support for boolean items
* When adding a new boolean field, default is `true`.
=> Add support for boolean items

viewer/v2client/src/components/inspector/item-vocab.vue, viewer/v2client/src/utils/vocab.js
* Now uses curie instead of expanded uri for term lookup.
=> Fix item-vocab not finding values

viewer/v2client/src/utils/vocab.js
* Remove some unused functions in vocab util
* Repair restrictions handling (now uses either allValuesFrom or original range + someValuesFrom)
* Switched out some old custom operations for term ids to now use getCompactUri
=> someValuesFrom fix + vocab fixes

viewer/v2client/src/components/inspector/entity-form.vue, viewer/v2client/src/components/inspector/item-local.vue, viewer/v2client/src/components/inspector/toolbar.vue, viewer/v2client/src/components/mixins/form-mixin.vue
* Moved the code to 1 place instead of 3
=> Move allowedProperties into FormMixin

viewer/v2client/src/components/inspector/item-local.vue
* Fixed LXL-1437
* Also removed the old method
=> Use item prop as formObj instead of getting from the old getForm method

viewer/v2client/src/components/Inspector.vue
* This created a problem when navigating away from new post (as we are redirecting).
=> Do not run warning dialog when inspector is Saving

viewer/v2client/src/components/inspector/item-vocab.vue, viewer/v2client/src/store/store.js, viewer/v2client/src/utils/string.js, viewer/v2client/src/utils/vocab.js
* Fixes item-vocab's (aka dropdowns) where the list was empty.
=> Use expanded uri in getTermByType

viewer/v2client/src/resources/json/combinedTemplates.json
Change CurrentPublicationPeriod to just PrimaryPublication and startDate/endDate to startYear/endYear.
=> Update record template for printed periodical

viewer/v2client/src/components/inspector/field.vue, viewer/v2client/src/components/inspector/item-entity.vue
Jira issue [LXL-1527](https://jira.kb.se/browse/LXL-1527)
=> blue bgcolor stays longer on last added field/entity

viewer/v2client/src/store/store.js
* Removed `technicalNote` from `lockedProperties` list.
=> Unlock `technicalNote` property

viewer/v2client/src/components/shared/card-component.vue
* Add explicit left value on card position
=> Fix IE11 card position bug

viewer/v2client/src/components/Inspector.vue, viewer/v2client/src/components/inspector/field-adder.vue, viewer/v2client/src/components/inspector/field.vue, viewer/v2client/src/components/inspector/item-boolean.vue, viewer/v2client/src/components/inspector/item-value.vue, viewer/v2client/src/components/inspector/item-vocab.vue, viewer/v2client/src/components/mixins/item-mixin.vue, viewer/v2client/src/store/store.js
* Compare for changes instead of setting status value on change
=> Fix unsaved changes bug

viewer/v2client/src/components/inspector/field-adder.vue, viewer/v2client/src/components/inspector/toolbar.vue, viewer/v2client/src/components/shared/tooltip-component.vue, viewer/v2client/src/utils/layout.js
* Add function for getting keyBindings by event name
* Add shortcut text to some buttons and menu items
=> Add keybinding info to tooltips and menu items

viewer/v2client/src/components/inspector/summary-action.vue, viewer/v2client/src/components/search/result-list-item.vue, viewer/v2client/src/components/shared/entity-summary.vue, viewer/v2client/src/utils/string.js
=> Fix libris resource links

viewer/v2client/src/components/inspector/reverse-relations.vue
OBS att detta är en pull request på min egen ändring, kom på en bättre lösning när jag hade pushat.
=> Changed condition for holding zero

viewer/v2client/src/components/inspector/summary-action.vue
(add entity btn in modal for example)
=> Enter also triggers summary-action's action

viewer/v2client/package.json, viewer/v2client/src/App.vue, viewer/v2client/src/components/Inspector.vue, viewer/v2client/src/components/inspector/entity-adder.vue, viewer/v2client/src/components/inspector/field-adder.vue, viewer/v2client/src/components/inspector/search-window.vue, viewer/v2client/src/components/search/remote-databases.vue, viewer/v2client/src/main.js, viewer/v2client/src/utils/display.js
By using `portal-vue` package we can get rid of a lot of z-index bugs.
=> Panels in portals

viewer/v2client/src/resources/json/copy.json
[LXL-1174](https://jira.kb.se/browse/LXL-1174)
=> Change landingpage link text

viewer/v2client/src/components/inspector/field-adder.vue, viewer/v2client/src/components/inspector/summary-action.vue, viewer/v2client/src/components/search/entity-search-item.vue, viewer/v2client/src/components/shared/panel-component.vue, viewer/v2client/src/less/_variables.less, viewer/v2client/src/less/icon.less
[LXL-1872](https://jira.kb.se/browse/LXL-1872)
=> Tweaks for is-added panel items

viewer/v2client/src/store/store.js
Also: Sort properties alphabetical in code
=> Remove record.identifiedBy instead of mainEntity.identifiedBy

viewer/v2client/src/components/Inspector.vue, viewer/v2client/src/components/inspector/breadcrumb.vue, viewer/v2client/src/components/inspector/create-item-button.vue, viewer/v2client/src/components/inspector/entity-adder.vue, viewer/v2client/src/components/inspector/entity-changelog.vue, viewer/v2client/src/components/inspector/entity-header.vue, viewer/v2client/src/components/inspector/field-adder.vue, viewer/v2client/src/components/inspector/field.vue, viewer/v2client/src/components/inspector/item-entity.vue, viewer/v2client/src/components/inspector/item-local.vue, viewer/v2client/src/components/inspector/item-sibling.vue, viewer/v2client/src/components/inspector/item-value.vue, viewer/v2client/src/components/inspector/modal-pagination.vue, viewer/v2client/src/components/inspector/reverse-relations.vue, viewer/v2client/src/components/inspector/search-window.vue, viewer/v2client/src/components/search/entity-search-item.vue, viewer/v2client/src/components/search/result-controls.vue, viewer/v2client/src/components/search/result-list-item.vue, viewer/v2client/src/components/search/search-form.vue, viewer/v2client/src/components/shared/card-component.vue, viewer/v2client/src/components/shared/entity-summary.vue, viewer/v2client/src/components/shared/filter-select.vue, viewer/v2client/src/components/shared/panel-component.vue, viewer/v2client/src/less/_variables.less, viewer/v2client/src/less/button-links-chip.less, viewer/v2client/src/less/type.less
[LXL-1846](https://jira.kb.se/browse/LXL-1846) + other stuff, consistency fixes & better placement of icons in form etc.
=> Misc design tweaks

viewer/v2client/src/utils/data.js
Heavily improved ``removeNullValues``, see below for results.
Commits:
* Remove objects only containing @type and set empty strings to null
----
| Status        | Size           | % reduc.  |
| ------------- |:-------------|:-----|
| Untrimmed      | 2.92 KB | - |
| Trimmed (before)      | 2.37 KB      |   19% |
| Trimmed (after) | 629 B      |    79% |
----
This is what the "book"-template looks like with all it's values intact.
```json
{
"@id": "https://id.kb.se/TEMPID#it",
"@type": "Instance",
"carrierType": [
{
"@id": "https://id.kb.se/term/rda/Volume"
}
],
"copyright": [
{
"@type": "Copyright",
"date": ""
}
],
"editionStatement": "",
"extent": [
{
"@type": "Extent",
"label": ""
}
],
"hasDimensions": {
"@type": "Dimensions",
"label": ""
},
"hasNote": [
{
"@type": "Note",
"label": ""
} …
```
=> Improve removeNullValues

viewer/v2client/src/components/Help.vue, viewer/v2client/src/components/inspector/field-adder.vue, viewer/v2client/src/components/inspector/field.vue, viewer/v2client/src/components/inspector/item-error.vue, viewer/v2client/src/components/layout/global-msg.vue, viewer/v2client/src/components/shared/panel-component.vue, viewer/v2client/src/less/_variables.less
- Undo move field action icons to right hand side
- Fixed some weird looking IE stuff
- Black color a bit darker
=> Move back icons

viewer/v2client/src/components/inspector/entity-adder.vue, viewer/v2client/src/components/inspector/field-adder.vue, viewer/v2client/src/components/inspector/item-local.vue, viewer/v2client/src/components/inspector/item-sibling.vue, viewer/v2client/src/components/inspector/marc-preview.vue, viewer/v2client/src/components/inspector/relations-list.vue, viewer/v2client/src/components/inspector/search-window.vue, viewer/v2client/src/resources/json/keybindings.json
Add "close-modals" to overview binding state and disable exiting of overview state
=> Fix keybindings not working when panel is open

viewer/v2client/src/components/inspector/field.vue
=> Missing help icons

viewer/v2client/src/main.js
Fixes [LXL-1579](https://jira.kb.se/browse/LXL-1579)
=> Add '/login/authorized'-path to lastPath exceptions

viewer/v2client/src/components/inspector/item-vocab.vue, viewer/v2client/src/store/store.js, viewer/v2client/src/utils/vocab.js
Filter out unwanted classes/props (added setting filteredCategories).
Fixes [LXL-1923](https://jira.kb.se/browse/LXL-1923)
=> Add support for "category: pending". Rewrite of filtered categories.

viewer/client/static/less/shared/main.less, viewer/templates/libris.html, viewer/templates/website.html
=> Fix libris redirect page after idkbse static site repair

viewer/v2client/src/components/Find.vue, viewer/v2client/src/components/inspector/create-item-button.vue, viewer/v2client/src/components/inspector/reverse-relations.vue, viewer/v2client/src/components/shared/round-button.vue, viewer/v2client/src/components/shared/tooltip-component.vue, viewer/v2client/src/resources/json/i18n.json
Also: Reworked "round-button" component a bit.
=> Add "add holding" button to search results

viewer/v2client/src/resources/json/structuredValueTemplates.json
New snippets for types on instance, holdings, agents, and subject among others.
=> Add alot of snippets

viewer/v2client/src/components/inspector/item-sibling.vue
Just added some missing classes to ItemSibling
=> Fix ItemSibling header behaving differently than ItemLocal

viewer/v2client/src/components/inspector/toolbar.vue
Added link in tools menu to download compiled from a holding post, **when the holding is my own**.
=> Add compiled marc21 link from own holding

viewer/v2client/src/components/inspector/entity-adder.vue, viewer/v2client/src/components/inspector/field-adder.vue, viewer/v2client/src/components/inspector/field.vue, viewer/v2client/src/components/inspector/item-local.vue, viewer/v2client/src/less/main.less, viewer/v2client/src/utils/layout.js
Both
Field-adder buttons
Entity-adder buttons
will now be auto focused when there isn't a snippet present.
=> Auto focus adders (if empty)

viewer/v2client/src/resources/json/structuredValueTemplates.json
Remove prefLabel from ComplexSubject and add prefLabel for all Topics and Subdivisions
=> Update snippet for ComplexSubject

viewer/v2client/src/utils/layout.js
Issue [LXL-1916](https://jira.kb.se/browse/LXL-1916)
=> Edge & older Chrome scroll bug fix

viewer/v2client/src/components/inspector/modal-pagination.vue, viewer/v2client/src/components/shared/filter-select.vue, viewer/v2client/src/components/shared/panel-component.vue
* Fixes panel search status overflow in IE
* Some tweaks to filter-select for IE [(LXL-1943)](https://jira.kb.se/browse/LXL-1943)
* modal pagination underline fix for Firefox, IE etc ([LXL-2003](https://jira.kb.se/browse/LXL-2003))
=> IE panel fixes

viewer/v2client/src/main.js, viewer/v2client/src/resources/json/i18n.json
* Split auth flow in several methods
* Add try from localStorage on `authenticating`-route if no param in URL.
=> Adjust authentication flow

viewer/v2client/src/components/inspector/reverse-relations.vue
Fixes [LXL-1965](https://jira.kb.se/browse/LXL-1965)
Added a delay for `1100ms` before the relations-info is loaded so that the index has time to update when the values have recently changed.
=> Add delay to relationsinfo

viewer/v2client/src/components/shared/tooltip-component.vue
Issue [LXL-2001](https://jira.kb.se/browse/LXL-2001)
=> Keybinding text in tooltips

viewer/v2client/src/components/inspector/entity-adder.vue, viewer/v2client/src/components/inspector/relations-list.vue, viewer/v2client/src/components/shared/panel-component.vue
[LXL-2057](https://jira.kb.se/browse/LXL-2057)
=> Holding pagination fix

viewer/v2client/src/components/inspector/item-local.vue, viewer/v2client/src/components/inspector/item-sibling.vue
[LXL-2015](https://jira.kb.se/browse/LXL-2015)
=> Expand items on new document

viewer/v2client/src/components/inspector/item-entity.vue, viewer/v2client/src/components/inspector/item-local.vue, viewer/v2client/src/components/inspector/item-sibling.vue
[LXL-1885](https://jira.kb.se/browse/LXL-1885) - highlights a newly added replaced/linked entity (when using the chain-icon)
=> Highlight replaced/linked entities

viewer/v2client/src/components/Inspector.vue
[LXL-2008](https://jira.kb.se/browse/LXL-2008)
=> Close marc preview when loading a new record

viewer/v2client/src/resources/json/combinedTemplates.json
According to corrected mapping of musicMedium in marcframe
=> Update musicMedium in printedNotatedMusic template

viewer/v2client/src/components/inspector/item-local.vue, viewer/v2client/src/components/inspector/item-sibling.vue
[LXL-2101](https://jira.kb.se/browse/LXL-2101)
=> Prevent linking of empty entites

viewer/v2client/src/components/inspector/field.vue, viewer/v2client/src/store/store.js
When a paste is made, we clear the clipboard.
=> Purge clipboard after paste

viewer/v2client/src/components/inspector/field.vue, viewer/v2client/src/components/inspector/item-entity.vue, viewer/v2client/src/components/inspector/item-error.vue, viewer/v2client/src/components/inspector/item-local.vue, viewer/v2client/src/components/inspector/item-sibling.vue, viewer/v2client/src/components/inspector/item-value.vue, viewer/v2client/src/components/inspector/item-vocab.vue, viewer/v2client/src/components/inspector/validation-summary.vue, viewer/v2client/src/components/mixins/item-mixin.vue, viewer/v2client/src/resources/json/i18n.json, viewer/v2client/src/utils/vocab.js
Expanding on validation functionality.
=> Add validation for unhandled and erroneous entities

viewer/v2client/src/components/layout/navbar.vue, viewer/v2client/src/components/shared/user-avatar.vue, viewer/v2client/src/components/usersettings/user-settings.vue
This is mostly a code cleanup.
=> Refactor avatar into own component and show user initials if no gravatar

viewer/v2client/src/components/Inspector.vue
Needed for [LXL-2178](https://jira.kb.se/browse/LXL-2178) to work.
=> Get ETag from response header instead of data

viewer/vue-client/src/utils/vocab.js, viewer/vue-client/src/views/Inspector.vue
Fixes [LXL-2200](https://jira.kb.se/browse/LXL-2200)
=> Make validTemplates softer (check both up and down in hierarchy)

viewer/vue-client/src/components/search/facet-group.vue
Facet scroll mode: we decided to replace the transparent gradient with a simple bottom border.
=> Facet redesign fix

viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/store.js
Added 'relevance' to `Item` sort options.
=> Sort holding fix

viewer/vue-client/src/components/create/file-adder.vue, viewer/vue-client/src/components/inspector/item-sibling.vue, viewer/vue-client/src/resources/json/i18n.json
- Fixes file drop parsing
- Added error notification if sibling id has missing reference
=> Fix file drop

viewer/vue-client/src/components/inspector/toolbar.vue
Feature should be disabled as it is not finished yet.
=> Disable 'embellish from file' option

viewer/vue-client/src/views/Inspector.vue
* Outputs json with spacing instead of one line when downloading unsaved post
=> Use prettier json output

viewer/vue-client/src/components/inspector/entity-form.vue, viewer/vue-client/src/components/inspector/field.vue
Fix [LXL-2347](https://jira.kb.se/browse/LXL-2347)
+
* Remove some unused code
=> LXL-2347 Form errors

viewer/vue-client/src/components/search/result-list-item.vue, viewer/vue-client/src/components/shared/entity-summary.vue
Commented out code that adds :visited color so that we can easily add it back in when working in IE11.
=> LXL-2265 - Deactivate

viewer/vue-client/src/main.js, viewer/vue-client/src/store.js
Also:
* change setting name (in FE) to matomoId, config name still is PIWIK_ID
=> Update matomo paths with "matomo" instead of "piwik"

viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/router.js, viewer/vue-client/src/store.js, viewer/vue-client/src/views/DirectoryCare.vue
* add object in store with getter/setter
* add router path with param 'tool'
Note: added "merge posts" menu option just for us to test. we can disable this later.
=> Add DirectoryCare view

viewer/vue-client/src/utils/record.js, viewer/vue-client/src/views/DirectoryCare.vue
* Added utility promise `RecordUtil.moveHolding(holdingId, destinationId, user)`
* Added example of this in DirectoryCare.vue (to be used as reference when building next step).
=> Lxl 2375 Move holding utility promise

viewer/vue-client/src/components/care/holding-mover.vue, viewer/vue-client/src/components/care/post-picker.vue, viewer/vue-client/src/components/shared/entity-summary.vue, viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/store.js, viewer/vue-client/src/views/DirectoryCare.vue
1. Fetches the posts of all ids:s in `userCare` 
2. extracts mainEntity & renders selectable `entity-summary` for each 
3. selected uri:s are stored in vuex `directoryCare` like:
```
{ "sender":"http://kblocalhost.kb.se:5000/dxqrc28q4pj1l4w#it",
"reciever":"http://kblocalhost.kb.se:5000/s931kvz421hfkdm#it" }
```
=> Holding-mover component etc

viewer/vue-client/src/App.vue, viewer/vue-client/src/components/care/holding-list.vue, viewer/vue-client/src/components/care/holding-mover.vue, viewer/vue-client/src/components/care/post-picker.vue, viewer/vue-client/src/components/shared/entity-summary.vue, viewer/vue-client/src/styles/_variables.less, viewer/vue-client/src/views/DirectoryCare.vue
* Switch selected instances button
* Can't select same instance on both sides
* change name `fetchedItems` -> `flaggedInstances`
* Some refactoring, new less variables etc.
=> Postpicker switch

viewer/vue-client/src/components/care/holding-list.vue, viewer/vue-client/src/components/care/holding-mover.vue, viewer/vue-client/src/components/care/post-picker.vue, viewer/vue-client/src/components/shared/entity-summary.vue, viewer/vue-client/src/styles/_variables.less
* User can search/filter the list of flagged instances
* Match is highlighted (`entity-summary` now accepts new prop `highlightStr`)
* Focus filter input on expand
* Minor changes in border-color, background-color etc for consistency.
=> Filter flagged instances

viewer/vue-client/src/components/search/search-form.vue, viewer/vue-client/src/resources/json/i18n.json
* Only show on toggle, not hover
* Adjusted size and position
* Added tooltip on icon
(If trying on local, do remember that the text will not load, the interaction and position should be good though).
=> Adjust search help

viewer/vue-client/src/views/Create.vue
=> Remove header from 'Create new' view

viewer/vue-client/src/components/care/holding-mover.vue, viewer/vue-client/src/components/care/post-picker.vue
* Added `max-height` + scroll to postpicker items
* Remove certain info when item selected
* Remove entity-summary title color
* Move separator btn + remove item wrapper flex-grow
=> Postpicker tweaks

viewer/dataaccess.py, viewer/vue-client/src/store.js
The backend takes care of this for us.
=> Don't use `.keyword` suffix in facets

viewer/vue-client/src/App.vue, viewer/vue-client/src/main.js, viewer/vue-client/src/models/user.js, viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/router.js, viewer/vue-client/src/store.js, viewer/vue-client/src/views/Login.vue
Had an idea to block directory-care route for un-authed users, but it turns out no routes that really require login are actually guarded (ie `/new`, `/create`, `/user`)
Waddabout this solution 🤔
=> Guard route

viewer/vue-client/src/components/care/holding-list.vue, viewer/vue-client/src/components/care/holding-mover.vue, viewer/vue-client/src/components/care/post-picker.vue, viewer/vue-client/src/resources/json/i18n.json
* Fix keyboard nav for entire user flow
* Axe-validation
* Add custom checkbox
=> Care keyboard nav

viewer/vue-client/src/components/layout/global-msg.vue, viewer/vue-client/src/components/layout/navbar.vue, viewer/vue-client/src/main.js, viewer/vue-client/src/store.js
=> Reflect environment label changes from libris/devops#29

viewer/vue-client/src/components/care/holding-mover.vue, viewer/vue-client/src/components/care/post-picker.vue, viewer/vue-client/src/components/shared/tag-switch.vue, viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/store.js, viewer/vue-client/src/utils/record.js, viewer/vue-client/src/views/DirectoryCare.vue
* fetch status 410 removes the id from the list and displays a modal with that info
* fetch status 404 (and other) displays a notification that (ids) could not be retrieved
* complete fetch fail displays a general notification
plus:
* Moved `mark` & `unmark` functions to store
* Empty flag list better look
=> Error notifications (new)

viewer/vue-client/src/components/layout/navbar.vue
Was incorrectly removed in #383
=> Add missing version number in environment label

viewer/vue-client/src/components/care/holding-list.vue, viewer/vue-client/src/views/DirectoryCare.vue
* Add `entity-summary` for holding items
* Add max-height and scroll for the holding list
also:
removed grey `<hr>` for consistency
=> Cardify holding list

viewer/vue-client/src/components/care/holding-list.vue, viewer/vue-client/src/components/care/holding-mover.vue, viewer/vue-client/src/components/shared/modal-component.vue, viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/utils/http.js, viewer/vue-client/src/views/DirectoryCare.vue, viewer/vue-client/src/views/Inspector.vue
+ wrote a httpUtil function for getting resources in a better way. This could be used in more places later.
=> Option to unmark post if all went well

viewer/vue-client/src/App.vue, viewer/vue-client/src/components/search/search-form.vue, viewer/vue-client/src/components/shared/panel-component.vue, viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/resources/json/propertymappings.json
[LXL-2404](https://jira.kb.se/browse/LXL-2404)
Change 'Title' to 'Main title' in main search select menu.
Also took a minute to go through the `search-form` css:
* Checked Safari, Firefox, IE, Edge & Chrome on Windows
* Restored borders, border-radius, shadows etc in libris/remote according to design
* Responsive fix, make sure input row doesn't overflow small screens
* Fixed clear-btn position
* Removed extra clear cross from IE
=> Title to Main title

viewer/vue-client/src/components/care/holding-list.vue, viewer/vue-client/src/resources/json/i18n.json
=> Add tooltip on disabled input for when no reciever has been chosen

viewer/vue-client/src/components/layout/navbar.vue, viewer/vue-client/src/components/shared/tab-menu.vue, viewer/vue-client/src/components/shared/tag-switch.vue, viewer/vue-client/src/styles/_globals.less, viewer/vue-client/src/styles/_variables.less
* Add badge
* Added optional 'html' option to tab-menu tablist items
* Added some badge-color classes
* Added `brand-accent` less variable ( #D56381 )
* Added color to active flag tag
=> Add badge in navbar for when user has directoryCare items

viewer/vue-client/src/components/care/holding-list.vue, viewer/vue-client/src/components/care/holding-mover.vue
* Move holding index into item body
* Move allsuccessdialog higher up (visually)
=> Move dialog and item index

viewer/vue-client/src/components/inspector/entity-adder.vue, viewer/vue-client/src/components/inspector/field-adder.vue, viewer/vue-client/src/components/inspector/field.vue, viewer/vue-client/src/components/inspector/item-local.vue, viewer/vue-client/src/components/inspector/item-vocab.vue, viewer/vue-client/src/components/inspector/relations-list.vue, viewer/vue-client/src/components/search/result-controls.vue, viewer/vue-client/src/components/search/search-form.vue, viewer/vue-client/src/main.js, viewer/vue-client/src/utils/display.js, viewer/vue-client/src/utils/string.js, viewer/vue-client/src/views/Inspector.vue
* Omit "type" in identifiers label if prop has "same" name (ie ShelfMark === shelfMark)
* Rewrite getLabelByLang to return original string if no translation, used to return null
=> Omit type in identifiers if prop has "same" name + change in getLabelByLang

viewer/vue-client/src/App.vue, viewer/vue-client/src/components/shared/tooltip-component.vue
Set fonts to @font-family-base, which will include the fallback font.
@mxtthias approve when you are OK with this being fixed.
=> Restore fallback font

viewer/vue-client/src/components/care/holding-mover.vue, viewer/vue-client/src/components/shared/tag-switch.vue, viewer/vue-client/src/resources/json/i18n.json
* Changing the help text according to suggestion from Elisabet.
* Tag-switch btn white
=> Proofread helptext

viewer/dataaccess.py, viewer/vue-client/src/components/search/facet-controls.vue, viewer/vue-client/src/components/search/facet.vue, viewer/vue-client/src/store.js
Also...
+ Increase number of expanded facet groups 3 -> 4
+ Change facet group order
+ type facets: sort by value instead of key
+ Minor css changes
=> Add facet for encodingLevel

viewer/vue-client/src/components/care/post-picker.vue
=> Fix holding-move IE width bug

viewer/vue-client/src/components/inspector/toolbar.vue
[LXL-2105](https://jira.kb.se/browse/LXL-2105)
Test (while in inspector)
Logged in:
⌘+Shift+C - copies post
Not logged in
⌘+Shift+C - Nothing happens
=> Copy login check

viewer/vue-client/src/components/inspector/modal-pagination.vue
[LXL-2350](https://jira.kb.se/browse/LXL-2350)
`Math.ceil(this.totalItems / this.maxPerPage)`
I.e:
```
Math.ceil(40/20) // 2 pages
Math.ceil(5/20) // 1 page
```
=> Fix pagination extra page bug

viewer/vue-client/src/resources/json/combinedTemplates.json
Add capture to work entity in Music CD template.
=> Add capture to Music-CD template

viewer/vue-client/src/components/layout/navbar.vue, viewer/vue-client/src/store.js
Also:
* use `settings.title` in navbar
=> [LXL-2372] Lowercase K in "Libris katalogisering"

viewer/vue-client/src/store.js
https://jira.kb.se/browse/LXL-2439
=> [LXL-2439] Add 'descriptionLastModifier' to 'lockedProperties'

viewer/vue-client/src/components/mixins/form-mixin.vue, viewer/vue-client/src/main.js, viewer/vue-client/src/resources/json/display.json, viewer/vue-client/src/utils/display.js, viewer/vue-client/src/utils/string.js, viewer/vue-client/src/utils/vocab.js
When this is merged, we can go ahead and merge
libris/definitions#100
=> [1.8.0] Tokens in display

viewer/vue-client/src/App.vue, viewer/vue-client/src/components/care/holding-list.vue, viewer/vue-client/src/components/care/holding-mover.vue, viewer/vue-client/src/components/care/post-picker.vue, viewer/vue-client/src/components/inspector/create-item-button.vue, viewer/vue-client/src/components/inspector/entity-header.vue, viewer/vue-client/src/components/inspector/relations-list.vue, viewer/vue-client/src/components/inspector/reverse-relations.vue, viewer/vue-client/src/components/mixins/lens-mixin.vue, viewer/vue-client/src/components/search/panel-search-item.vue, viewer/vue-client/src/components/search/panel-search-list.vue, viewer/vue-client/src/components/search/result-list-item.vue, viewer/vue-client/src/components/shared/entity-summary.vue, viewer/vue-client/src/components/shared/panel-component.vue, viewer/vue-client/src/components/shared/round-button.vue, viewer/vue-client/src/components/shared/rounded-button.vue, viewer/vue-client/src/components/shared/tag-switch.vue, viewer/vue-client/src/resources/json/displayGroups.json, viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/styles/_variables.less, viewer/vue-client/src/utils/display.js, viewer/vue-client/src/views/Inspector.vue
**Don't merge!**
This is a branch to work on the new cards
- Check it out to check it out
- Commit if u like
Some of the todos
* Make identifiers look like the other key/value pairs (since they are not separated like that)
* "Show more/less"-logic
=> LXL-2424 - New summary card

viewer/vue-client/src/components/inspector/toolbar.vue, viewer/vue-client/src/components/mixins/result-mixin.vue, viewer/vue-client/src/components/search/result-list.vue, viewer/vue-client/src/store.js, viewer/vue-client/src/utils/record.js, viewer/vue-client/src/views/Create.vue, viewer/vue-client/src/views/Inspector.vue
https://jira.kb.se/browse/LXL-2475
=> [LXL-2475] Use 2 separate lists for which keys to clear before import/duplication

viewer/vue-client/src/components/inspector/create-item-button.vue, viewer/vue-client/src/resources/json/keybindings.json
[LXL-2139](https://jira.kb.se/browse/LXL-2139)
Adds keybinding + tooltip for `create-item-button` (non-compact version)
=> LXL-2139 Add holding keybinding

viewer/vue-client/src/components/shared/notification.vue, viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/store.js, viewer/vue-client/src/views/Inspector.vue
[LXL-2455](https://jira.kb.se/browse/LXL-2455)
Calls a `warnOnSave` method on each save, which checks a setting (with same name) for presence of a certain value in a specific key. If found, it displays a warning notification.
=> LXL-2455 Encodinglevel notification

viewer/vue-client/src/views/Create.vue
(branch name refers to wrong ticket, oops)
-> [LXL-2510](https://jira.kb.se/browse/LXL-2510)
=> LXL-2510 - Remove Agent base card

viewer/vue-client/src/resources/json/combinedTemplates.json, viewer/vue-client/src/resources/json/structuredValueTemplates.json
Align properties for Meeting snippet, and hasVariant in template (including repetition).
=> Align and fix repetition in snippets and template for meeting

viewer/vue-client/src/components/inspector/entity-adder.vue, viewer/vue-client/src/components/inspector/field-adder.vue, viewer/vue-client/src/components/inspector/field.vue, viewer/vue-client/src/components/inspector/item-local.vue, viewer/vue-client/src/components/inspector/item-sibling.vue, viewer/vue-client/src/components/inspector/toolbar.vue, viewer/vue-client/src/components/search/panel-search-item.vue, viewer/vue-client/src/store.js, viewer/vue-client/src/styles/_variables.less, viewer/vue-client/src/views/Inspector.vue
This highlights all added fields after embellish. Highlight arr is cleared on next add, on save, before destroy.
**No need to merge this (right away at least).** Can also be just a reference if we want to use logic in [LXL-2392](https://jira.kb.se/browse/LXL-2392).
=> LXL-2102 Highlight embellished

viewer/vue-client/src/resources/json/combinedTemplates.json
* Remove redundant property personalName
* Remove redundant code z in descriptionConventions.
* Add missing headingmain
=> Update adminMetada for agents

viewer/vue-client/src/components/shared/entity-summary.vue, viewer/vue-client/src/resources/json/displayGroups.json
* Moved mediaType and carrierType to top of summary
* Adds title attribute to categorization slot
=> Add mediaType and carrierType properties to categorization slots

viewer/vue-client/src/components/inspector/item-local.vue, viewer/vue-client/src/components/inspector/item-sibling.vue
[LXL-2087](https://jira.kb.se/browse/LXL-2087)
=> Expand item label click area

viewer/vue-client/src/components/search/remote-databases.vue
[LXL-2555](https://jira.kb.se/browse/LXL-2555)
=> LXL-2555 Enable BNF, KNYGOS, YALE

viewer/vue-client/src/components/care/post-picker.vue, viewer/vue-client/src/components/inspector/entity-header.vue, viewer/vue-client/src/components/search/facet-controls.vue, viewer/vue-client/src/components/search/facet-group.vue, viewer/vue-client/src/components/search/facet.vue, viewer/vue-client/src/components/search/panel-search-item.vue, viewer/vue-client/src/components/search/result-list-item.vue, viewer/vue-client/src/components/shared/encoding-level-icon.vue, viewer/vue-client/src/components/shared/entity-summary.vue, viewer/vue-client/src/store.js, viewer/vue-client/src/views/DirectoryCare.vue
[LXL-2451](https://jira.kb.se/browse/LXL-2451)
Displays icon for encodingLevel in: 
* Main search result list
* Facet list
* Entity header
* Panel search list
* Directory care
Also...
Changes order & num of expanded facets
=> LXL-2451 encoding level icon

viewer/vue-client/src/components/shared/encoding-level-icon.vue, viewer/vue-client/src/styles/_variables.less
To match new swedish labels for encoding levels
=> Modify encodinglevel icon labels

viewer/vue-client/src/components/shared/encoding-level-icon.vue, viewer/vue-client/src/components/shared/entity-summary.vue
Remove mapping for holding encodingLevels + remove icons for items in entity-summary.
=> Remove icons for Items

viewer/vue-client/src/App.vue, viewer/vue-client/src/components/inspector/reverse-relations.vue, viewer/vue-client/src/components/search/facet-controls.vue, viewer/vue-client/src/components/search/facet.vue, viewer/vue-client/src/components/search/remote-databases.vue, viewer/vue-client/src/components/search/result-controls.vue, viewer/vue-client/src/components/search/search-result.vue, viewer/vue-client/src/components/usersettings/user-settings.vue, viewer/vue-client/src/views/Find.vue, viewer/vue-client/src/views/Inspector.vue
* Moves libris search filters to a leftmost column
* Moves remote database selection to same column instead of side-panel
=> LXL-2500 - Move facets and db handler to the left

viewer/vue-client/src/App.vue, viewer/vue-client/src/components/create/creation-card.vue, viewer/vue-client/src/components/inspector/entity-adder.vue, viewer/vue-client/src/components/inspector/field-adder.vue, viewer/vue-client/src/components/inspector/reverse-relations.vue, viewer/vue-client/src/components/inspector/search-window.vue, viewer/vue-client/src/components/layout/navbar.vue, viewer/vue-client/src/components/search/search-form.vue, viewer/vue-client/src/components/search/sort.vue, viewer/vue-client/src/components/usersettings/user-settings.vue, viewer/vue-client/src/resources/json/i18n.json, viewer/vue-client/src/views/Inspector.vue
A branch to collab & test this feature...
=> LXL-1836 - Change sigel

viewer/__init__.py, viewer/vue-client/src/store.js
Related to:
libris/librisxl/pull/253
=> Remove forcedSetTerms getters, setters and flask route

viewer/vue-client/src/resources/json/structuredValueTemplates.json
* Add structuredValue snippet for AcquisitionSource Class.
=> Add acquisitionSource snippet

viewer/__init__.py, viewer/dataaccess.py, viewer/templates/marcframeview.html, viewer/templates/thing.html, viewer/vocabview.py
This has only been rudimentarily tested, but is a fairly straightforward change to run under both Python 2 and 3. It would be good to have it run for a while on dev2 before merging, especially if we can set up mod_wsgi for Python 3 there (reasonably by using a flag in the devops env setting).
=> Adapt code to work on Python 3

viewer/vue-client/src/resources/json/structuredValueTemplates.json, viewer/vue-client/src/utils/record.js
Add public note in Mediaobject to item template and snippet as per user request in LXL-2562.
=> Add public note in Mediaobject to item template and snippet

viewer/vue-client/src/components/layout/global-msg.vue
Make global message closeable (will then show smaller banner instead)
=> Make global message (aka dev/stg-banner) closeable

viewer/vue-client/src/components/care/post-picker.vue, viewer/vue-client/src/components/create/creation-card.vue, viewer/vue-client/src/components/inspector/entity-adder.vue, viewer/vue-client/src/components/inspector/entity-header.vue, viewer/vue-client/src/components/inspector/field-adder.vue, viewer/vue-client/src/components/inspector/field.vue, viewer/vue-client/src/components/inspector/item-local.vue, viewer/vue-client/src/components/inspector/item-sibling.vue, viewer/vue-client/src/components/inspector/item-vocab.vue, viewer/vue-client/src/components/inspector/relations-list.vue, viewer/vue-client/src/components/inspector/search-window.vue, viewer/vue-client/src/components/inspector/toolbar.vue, viewer/vue-client/src/components/mixins/result-mixin.vue, viewer/vue-client/src/components/search/result-controls.vue, viewer/vue-client/src/components/search/result-list-item.vue, viewer/vue-client/src/components/search/search-form.vue, viewer/vue-client/src/components/shared/entity-summary.vue, viewer/vue-client/src/components/shared/filter-select.vue, viewer/vue-client/src/components/shared/tooltip-component.vue, viewer/vue-client/src/components/usersettings/user-settings.vue, viewer/vue-client/src/utils/string.js, viewer/vue-client/src/views/Find.vue, viewer/vue-client/src/views/Inspector.vue
Fixes local entities type label not translating to the users language.
=> Fix user's selected language not being respected (standard lang being used instead)

viewer/vue-client/src/components/create/creation-card.vue, viewer/vue-client/src/components/shared/filter-select.vue
Since app settings lang now are synced with users language, just use app language.
=> User app settings language instead of user settings language

viewer/vue-client/src/views/Inspector.vue
... instead of just setting it based on active sigel
Needs to be released before or at the same time as libris/librisxl/pull/375
=> Fix missing heldBy by copying from hasComponent

viewer/vue-client/src/resources/json/combinedTemplates.json
* Remove encodingLevel and marc:level from auth templates because of default values in conversion.
* Update Concept templates.
=> Update auth templates

viewer/vue-client/src/components/search/result-controls.vue
https://jira.kb.se/browse/LXL-2712
=> [LXL-2712] Fix filter tags without data breaking UI rendering

viewer/__init__.py
Forward query parameters used by back-end
=> [LXL-2608] Implement parameterized resource views

viewer/vue-client/src/resources/json/combinedTemplates.json
Change ProjectedImage to MovingImage in Movie template. 
Dependent on https://github.com/libris/librisxl/pull/416, https://github.com/libris/definitions/pull/147
=> Change ProjectedImage to MovingImage type in template

viewer/vue-client/src/components/create/creation-card.vue, viewer/vue-client/src/components/inspector/item-type.vue
Show whole class tree, disable classes which are abstract
=> LXL-2735 - Show class tree in item-type and show abstract

viewer/vue-client/src/resources/json/displayGroups.json
=> Remove "code" property from header slot

viewer/vue-client/src/components/inspector/item-entity.vue, viewer/vue-client/src/components/inspector/item-value.vue, viewer/vue-client/src/components/inspector/toolbar.vue, viewer/vue-client/src/components/search/link-card.vue, viewer/vue-client/src/components/search/result-list-item.vue, viewer/vue-client/src/components/shared/entity-summary.vue, viewer/vue-client/src/components/shared/preview-card.vue, viewer/vue-client/src/components/shared/summary-node.vue, viewer/vue-client/src/main.js, viewer/vue-client/src/utils/http.js, viewer/vue-client/src/views/DirectoryCare.vue
Since we already have a idPath-variable being set in every environment, we just try convert them on:
* External links in templates (external as in "should not open in application")
* When fetching external resources
=> Convert id-links using idPath-variable (set per env)

viewer/vue-client/package.json, viewer/vue-client/src/App.vue, viewer/vue-client/src/components/inspector/field.vue, viewer/vue-client/src/components/inspector/item-boolean.vue, viewer/vue-client/src/components/inspector/item-entity.vue, viewer/vue-client/src/components/inspector/item-type.vue, viewer/vue-client/src/components/inspector/item-vocab.vue, viewer/vue-client/src/components/inspector/reverse-relations.vue, viewer/vue-client/src/components/inspector/toolbar.vue, viewer/vue-client/src/components/layout/navbar.vue, viewer/vue-client/src/components/layout/search-bar.vue, viewer/vue-client/src/components/mixins/form-mixin.vue, viewer/vue-client/src/components/search/facet.vue, viewer/vue-client/src/components/search/remote-databases.vue, viewer/vue-client/src/components/search/result-controls.vue, viewer/vue-client/src/components/search/search-form.vue, viewer/vue-client/src/components/shared/entity-summary.vue, viewer/vue-client/src/components/shared/preview-card.vue, viewer/vue-client/src/components/shared/summary-node.vue, viewer/vue-client/src/components/usersettings/select-sigel.vue, viewer/vue-client/src/main.js, viewer/vue-client/src/utils/display.js, viewer/vue-client/src/utils/http.js, viewer/vue-client/src/utils/vocab.js, viewer/vue-client/src/views/Create.vue, viewer/vue-client/src/views/Find.vue, viewer/vue-client/src/views/Inspector.vue
**Cleanup up a lot. Should be no lint errors after this.**
* Disabled rule `no param reassign` since we actually depend on this pattern in some cases (it may be a problem that we do that, but that is out-of-scope for this PR 🤷‍♂).
* Some errors are not syntax errors but rather imports that are never used.
This PR is mostly a preparation so that we can run this automatically on PRs in the future. Should keep it pretty clean ✌️
=> Massive lint

viewer/vue-client/src/components/shared/preview-card.vue
Fixes preview-cards not showing the data if it fetches more.
=> Fix preview-card not reaching into the result

viewer/vue-client/src/components/mixins/item-mixin.vue, viewer/vue-client/src/components/shared/entity-summary.vue, viewer/vue-client/src/components/shared/preview-card.vue, viewer/vue-client/src/components/shared/summary-node.vue, viewer/vue-client/src/main.js, viewer/vue-client/src/store.js, viewer/vue-client/src/utils/record.js, viewer/vue-client/src/utils/string.js
[LXL-2864](https://jira.kb.se/browse/LXL-2864)
Solves the problem with some links not being considered Libris links (ie links navigating inside app).
Reworked isLibrisResource utility and some baseUri converters.
=> Rework isLibrisResource check

viewer/vue-client/src/components/inspector/entity-adder.vue, viewer/vue-client/src/components/inspector/field.vue, viewer/vue-client/src/components/shared/filter-select.vue
=> Default entity-adder search to Range, if no allValuesFrom

viewer/vue-client/src/components/search/result-list-item.vue
[LXL-2869](https://jira.kb.se/browse/LXL-2869)
Compact view in remote search was not displaying any items.
Added same logic as in pull/561 for result-list.item
=> Fix accessing id correctly in remote search list item

viewer/vue-client/src/components/inspector/item-entity.vue
[LXL-2864](https://jira.kb.se/browse/LXL-2864)
=> Provide recordId for PreviewCard where missing

viewer/vue-client/.yarnrc
Adds `.yarnrc` file to config `ignore-engines true`.
=> Add ignore-engines true as yarn config

viewer/vue-client/src/utils/vocab.js
vocabUtil.spec.js contains some obsolete tests for VocabUtil. Not updated, nor run.
"{Namnlös}" --> "Facktermer"
https://libris-qa.kb.se/katalogisering/skx2b8dwv1c7b2c1
containerMap['@language']
Before:
```
containerMap:
@language:
prefLabelByLang: "prefLabelByLang"
altLabelByLang: "altLabelByLang"
commentByLang: "commentByLang"
labelByLang: "labelByLang"
definition: "definitionByLang"
scopeNoteByLang: "scopeNoteByLang"
descriptionByLang: "descriptionByLang"
prefLabel: "prefLabelByLang"
titleByLang: "titleByLang"
label: "labelByLang"
comment: "commentByLang"
scopeNote: "scopeNoteByLang"
note: "noteByLang"
altLabel: "altLabelByLang"
definitionByLang: "definitionByLang"
noteByLang: "noteByLang"
```
After:
```
prefLabelByLang: "prefLabelByLang"
altLabelByLang: "altLabelByLang"
commentByLang: …
```
=> Fix @container @language mapping

viewer/vue-client/src/views/Inspector.vue
Adds ability to run `applyChangeList` to a path instead of just a property on the baseData.
This PR also adds usage of this when applying `work`-parts of templates. It will check if the work data of the original object has it's `work`-data in the `#work`-path or in `mainEntity.instanceOf` and then use the implementation described above to target the insertion accordingly.
The reason that we want to use `applyChangeList` specifically on some keys/paths is that the template-mechanism will only check the keys on the base level, and will not dive deep into the objects.
[LXL-2928](https://jira.kb.se/browse/LXL-2928)
`work`-parts of templates not being applied correctly.
* Adds ability to run `applyChangeList` with a path rather than just a key.
* Adds usage of `applyChangeList` when the path …
=> Add optional parameter targetPath for applyChangeList, and usage of it

viewer/vue-client/src/resources/json/structuredValueTemplates.json
Linted in editor.
Add snippet (including mainTitle) for FormerTitle.
=> Add snippet for FormerTitle

viewer/vue-client/src/resources/json/combinedTemplates.json
Linted locally
[LXL-2934](https://jira.kb.se/browse/LXL-2934), [LXL-2934](https://jira.kb.se/browse/LXL-2934)
Testing Print instead of Instance as Type in certain templates.
Instance -> Print in following templates:
* Bok
* Noterad Musik
* Tryckt Seriell Resurs
* Äldretryck
=> Add Print Instances for certain templates

viewer/templates/maintenance.html
Update text and link in "ongoing maintenance" page
=> Fix link in maintenance page

viewer/vue-client/src/store.js
Hide @reverse until we have worked out naming and ux for it
[LXL-2968](https://jira.kb.se/browse/LXL-2968)
=> hide @reverse property

viewer/vue-client/src/components/care/detailed-enrichment.vue, viewer/vue-client/src/components/inspector/item-type.vue
[LXL-3037](https://jira.kb.se/browse/LXL-3037), [LXL-3038](https://jira.kb.se/browse/LXL-3038)
Broken layout in modal dialog in IE11
CSS adjustments to cover for IE11
=> ie11 fixes

viewer/vue-client/src/resources/json/structuredValueTemplates.json
* Add snippet for Affiliation
* Fix snippet for BiographicalNote
=> Add snippets for Affiliation and fix BiographicalNote

viewer/vue-client/src/components/care/detailed-enrichment.vue
Same as #600 
Did not merge properly.
=> Convert to array if not array on target obj property

viewer/vue-client/src/resources/json/structuredValueTemplates.json
Add snippets for FieldOfActivity, Occupation, marc:OtherAttributes
=> Snippets for Occupation, FoA, OtherAttributes

viewer/vue-client/src/components/shared/encoding-level-icon.vue
Update colors to conform with required contrast levels
[LXL-3052](https://jira.kb.se/browse/LXL-3052)
a11y requirements
Simply updated color codes
=> updated colors for encoding levels

viewer/vue-client/src/components/layout/footer.vue, viewer/vue-client/src/styles/_variables.less
[LXL-3082](https://jira.kb.se/browse/LXL-3082), [LXL-3053](https://jira.kb.se/browse/LXL-3053)
New footer style
changed colors
adjusted spacing
=> changing footer style to white background

viewer/vue-client/src/resources/json/combinedTemplates.json
Add first draft of a digi-template.
[LXL-3029](https://jira.kb.se/browse/LXL-3029)
=> Add first draw of digitemplate

viewer/vue-client/src/resources/json/combinedTemplates.json
Add description to Agent templates
[LXL-3062](https://jira.kb.se/browse/LXL-3062)
=> Add description for Agents

viewer/vue-client/src/App.vue, viewer/vue-client/src/components/layout/footer.vue, viewer/vue-client/src/components/search/search-result.vue, viewer/vue-client/src/views/Create.vue, viewer/vue-client/src/views/Help.vue, viewer/vue-client/src/views/Inspector.vue, viewer/vue-client/src/views/LandingPage.vue
Fine tuning spacing, mostly towards footer
[LXL-3082](https://jira.kb.se/browse/LXL-3082)
Minor layout issues
Adjusted paddings
=> adjusting spacing

viewer/vue-client/src/components/layout/footer.vue, viewer/vue-client/src/resources/json/i18n.json
Link to the accessibility report
[LXL-3023](https://jira.kb.se/browse/LXL-3023)
=> added a link to accessibility statement

viewer/vue-client/src/resources/json/structuredValueTemplates.json
Add missing identifier snippets
=> Update idenfier snippets

viewer/vue-client/src/resources/json/combinedTemplates.json
Adds subtitle to hasTitle / Title
Removes technicalNote from Record
Update template names
[LXL-3061](https://jira.kb.se/browse/LXL-3061)
=> Update templates for componentParts

viewer/vue-client/src/resources/json/combinedTemplates.json
Add draft of ComplextSubject template for testing.
[LXL-3118](https://jira.kb.se/browse/LXL-3118)
=> Add draft of ComplexSubject template

viewer/vue-client/src/resources/json/combinedTemplates.json
Add explanatoryTerm to ClassificationDdc entitites in Subject templates.
=> Add explanatoryTerm to classificationDDC in topics

viewer/vue-client/src/resources/json/combinedTemplates.json
See See libris/librisxl#648 for details
=> Update templates with physicalDetailsNote

viewer/vue-client/src/resources/json/combinedTemplates.json
Add ComplexSubject for geographic terms.
[LXL-3118](https://jira.kb.se/browse/LXL-3118)
=> Add complexSubject geographic template

viewer/vue-client/src/utils/record.js
=> DigiFlow: Copy PrimaryPublication if there is one

viewer/vue-client/src/resources/json/combinedTemplates.json
Add template draft for integrating resource.
[LXL-3237](https://jira.kb.se/browse/LXL-3237)
=> Add draft for integrating template

viewer/vue-client/src/store.js
Enables extraction of local agents.
[LXL-3238](https://jira.kb.se/browse/LXL-3238)
* Uncommented the `Agent`-type in `extractableTypes`-list.
=> Enable extraction of local agents

viewer/vue-client/src/components/inspector/toolbar.vue
[LXL-3282](https://jira.kb.se/browse/LXL-3282)
Visual bug, causing a menu with few items being higher than necessary
Decreased min-height value
=> lower min-height on toolbar menu list

viewer/vue-client/src/components/inspector/entity-form.vue, viewer/vue-client/src/components/mixins/form-mixin.vue
This reverts commit d712227812ef5d07e3759f213702270600fa8e85.
Re-enable reverse
=> Revert "Disable reverse functionality"

viewer/client/package-lock.json, viewer/client/package.json, viewer/client/readme.md, viewer/client/static/js/marcframeview.js, viewer/client/static/less/main_id.less, viewer/client/static/less/shared/kungbib.less, viewer/client/static/less/shared/main.less, viewer/templates/base.html, viewer/templates/marcframeview.html, viewer/templates/vocab.html
Some basic cleanup of the static client, i.e updating and removing unused/unneeded packages, as a groundwork before doing a11y work on the site.
none
Not found icons, not found files, reduces bundle size.
* Remove d3.js and graph.js imports and references to missing .js files
* Remove jQuery and Bootstrap-js dependencies, get rid of vendor-file altogether
* Add some vanilla js to get tab menu working
* Remove KB-styles package (replace with a temp .less-file with needed classes/variables)
* Add Font awesome and Open sans
* Bump Less and Uglify versions, fix npm audit warnings
* Update readme
=> id.kb.se - cleanup

viewer/vue-client/src/resources/json/combinedTemplates.json
Add draft for electronic periodical template
[LXL-3312](https://jira.kb.se/browse/LXL-3312)
=> Add electronic periodical draft

viewer/vue-client/src/resources/json/combinedTemplates.json
Add draft for Text work template.
[LXL-2764](https://jira.kb.se/browse/LXL-2764)
=> Add draft Text work template

viewer/vue-client/src/components/search/result-list-item.vue, viewer/vue-client/src/components/search/result-list.vue, viewer/vue-client/src/components/shared/entity-summary.vue, viewer/vue-client/src/resources/json/i18n.json
New compact view in search results.
[LXL-3225](https://jira.kb.se/browse/LXL-3225)
refactoring of result-list-item
added translations
=> LXL-3225 - Redesign compact view in search results

viewer/client/static/js/marcframeview.js, viewer/client/static/less/main_id.less, viewer/client/static/less/shared/items.less, viewer/client/static/less/shared/main.less, viewer/client/static/less/shared/marcframe.less, viewer/client/static/less/shared/search.less, viewer/client/static/less/shared/thing.less, viewer/templates/base.html, viewer/templates/marcframeview.html, viewer/templates/pagedcollection.html, viewer/templates/search.html, viewer/templates/thing.html, viewer/templates/vocab.html, viewer/templates/website.html
Misc accessibility fixes
[LXL-3245](https://jira.kb.se/browse/LXL-3245)
* Add skip-link to benefit tab navigation
* Add aria-attributes for screen readers
* Check heading & landbark structure
* Check correct use of semantic elements, replace `<i>`, `<u>` etc.
* Validate all HTML
* Add lang attr for english content
* Minor color adjustments
* Minor responsive fixes
=> LXL-3245 - idkbse a11y

viewer/vue-client/src/views/Create.vue
[LXL-3335](https://jira.kb.se/browse/LXL-3335)
excludeBase when creating instance
=> excludeBase for instance

viewer/client/static/less/main_id.less, viewer/client/static/less/shared/items.less, viewer/client/static/less/shared/main.less, viewer/client/static/less/shared/vocab.less, viewer/templates/vocab.html
Misc fixes/added features requested after first iteration of this ticket
[LXL-3325](https://jira.kb.se/browse/LXL-3325)
* Render definition notes in vocab view
* Replace '...' with info text when no-label
* Styling of nolabel and note classes
=> LXL-3325: idkbse - vocab view fixes

viewer/client/static/less/shared/main.less, viewer/client/static/less/shared/search.less, viewer/client/static/less/shared/thing.less, viewer/templates/search.html, viewer/templates/thing.html, viewer/templates/website.html
Misc fixes/added features requested after first iteration of this ticket
[LXL-3299](https://jira.kb.se/browse/LXL-3299)
* Sort support in search
* Dropdown lets you control sorting of search results
* 'Category' link from front page leads to alphabetically sorted page
* Search result items now display their scheme in addition to their type
* 'Thing'-view more compact:
* linked item's type are now hidden, and multiple linked items are placed inline
* Layout and padding tweaks
=> LXL-3299: idkbse - search & term view fixes

viewer/client/static/less/shared/marcframe.less, viewer/client/static/less/shared/utils.less, viewer/templates/marcframeview.html
Misc fixes/added features requested after first iteration of this ticket
[LXL-3313](https://jira.kb.se/browse/LXL-3313)
* Unlink stuff that always result in broken anchorlinks anyway
* New layout for nested tables on small screens
* Prevent text from overflowing into sibling cells
* etc
=> LXL-3313: idkbse - marcview fixes

viewer/dataaccess.py
Make backend generate search facet links for contribution.agent.
=> Add search facet for contribution.agent

viewer/client/static/less/shared/vocab.less, viewer/templates/vocab.html
add skos.definition for vocab classes
=> Idkbse: add skos.definition for vocab classes

viewer/client/static/js/vocab.js, viewer/client/static/less/main_id.less, viewer/client/static/less/shared/items.less, viewer/client/static/less/shared/marcframe.less, viewer/client/static/less/shared/vocab.less, viewer/templates/marcframeview.html, viewer/templates/vocab.html
[LXL-3299](https://jira.kb.se/browse/LXL-3299), [LXL-3313](https://jira.kb.se/browse/LXL-3313), [LXL-3325](https://jira.kb.se/browse/LXL-3325)
* Checkbox option to hide MARC-terms on vocab page
* Add links to documentation in marcframe header
* Fix IE11 layout issue in marcframe view
*  .chip-marc class tweak
=> Idkbse: Misc marc fixes

viewer/vue-client/src/components/inspector/item-local.vue, viewer/vue-client/src/components/inspector/item-sibling.vue
[LXL-3378](https://jira.kb.se/browse/LXL-3378)
Summary disappearing when extracting work from instance.
=> Fix summary disappers when extracting work

viewer/vue-client/src/resources/json/structuredValueTemplates.json
Update the ComplexSubject as a full description with Topic and TopicSubdivision in termlist and linked to inScheme sao.
[LXL-3425](https://jira.kb.se/browse/LXL-3425)
=> Update ComplexSubject snippet

viewer/__init__.py, viewer/dataaccess.py
See https://github.com/libris/librisxl/pull/874
=> Set _boost in /find API call for id.kb.se

viewer/dataaccess.py, viewer/vue-client/src/components/search/facet-controls.vue, viewer/vue-client/src/components/search/facet-group.vue, viewer/vue-client/src/store.js
=> Add facet for holdings (@reverse.itemOf.heldBy)

viewer/vue-client/src/components/care/detailed-enrichment.vue
Fix label for `@type` in detailed enrichment.
Done in the same way as Inspector except always show "Type" (not e.g. "Instance type")
[LXL-3235](https://jira.kb.se/browse/LXL-3235)
=> Fix @type label in detailed enrichment

vue-client/src/resources/json/propertymappings.json
And marc:issnL and marc:canceledIssnL
[LXL-3732](https://jira.kb.se/browse/LXL-3732)
=> Also find marc:canceledIssn and marc:incorrectIssn in ISSN search

vue-client/src/resources/json/combinedTemplates.json
Add template for Instance type Manuscript.
=> Add draft for manuscript template

vue-client/src/settings.js
Removes bibliography on record duplication.
[[LXL-3865](https://jira.kb.se/browse/LXL-3865)]
=> Add bibliography to keysToClear on duplication

vue-client/src/components/search/panel-search-item.vue, vue-client/src/components/shared/entity-summary.vue
- Display labels in uppercase and above values
- Let values take up to three rows of space
[LXL-3311](https://jira.kb.se/browse/LXL-3311)
=> New layout for cards in side panel

vue-client/src/components/layout/footer.vue, vue-client/src/resources/json/i18n.json
[LXL-3899](https://jira.kb.se/browse/LXL-3899)
=> Minor footer changes

lxljs/display.js
[LXL-3400](https://jira.kb.se/browse/LXL-3400)
=> Add support for subPropertyOf+range in alternateProperties

vue-client/src/components/inspector/version-history-changesets.vue, vue-client/src/components/inspector/version-history.vue, vue-client/src/components/shared/fullscreen-panel.vue, vue-client/src/resources/json/i18n.json
* Improve flex behavior
* Make version list go fullscreen on smaller window sizes
=> Closeable fullscreen version list view on window shrink

nuxt-app/pages/index.vue
Fixes crash on startup if the backing id.kb.se summary document is missing.
=> Handle missing summary document

vue-client/src/router.js
Fixes recursion error in router middleware
=> Dont slice fullPath if on root level (/)

vue-client/src/components/inspector/item-bylang.vue
See description in [LXL-4050](https://jira.kb.se/browse/LXL-4050).
=> Sorting for language-tagged properties

vue-client/src/resources/json/combinedTemplates.json
Update `version` --> `marc:arrangementStatementForMusic`in NotatedMusic template
=> Update version in templates

vue-client/src/components/inspector/item-local.vue, vue-client/src/styles/_variables.less
Start on styling for local entities.
=> Example styling for marking local entities

vue-client/src/settings.js
Add labels for subject and intendedAudience.
I don't think we need a particular separation of "på verk" since we should rather do a global change to move up both subjects and intendedAudience things to the work.
=> Update facet settings

vue-client/package.json, vue-client/src/components/inspector/field.vue, vue-client/src/components/inspector/version-history.vue, vue-client/src/components/search/facet-group.vue, vue-client/src/components/search/result-list-item.vue, vue-client/src/components/search/result-list.vue, vue-client/src/components/shared/entity-summary.vue, vue-client/src/components/shared/preview-card.vue, vue-client/src/main.js, vue-client/src/store.js, vue-client/yarn.lock
Fixes eslint import/order errors
Disables import/no-extraneous-dependencies eslint rule
=> Fix eslint errors/warnings

vue-client/src/App.vue
=> Enforce text-transform rule on uppercaseHeading class

vue-client/src/components/inspector/reverse-relations.vue, vue-client/src/main.js
Fixes button alignment issues in reverse relations component
[LXL-4216](https://jira.kb.se/browse/LXL-4216)
=> Set button size on ReverseRelations component

nuxt-app/.env.in, test-resources/vocab.js, vue-client/.env.e2e, vue-client/vue.config.js
See https://github.com/libris/librisxl/pull/1284
=> Use .localhost instead of .kblocalhost.kb.se

vue-client/src/components/shared/entity-summary.vue
[LXL-4215](https://jira.kb.se/browse/LXL-4215)
Fixes id label font-size
See screenshot:
- Update id font-size
=> Update id font-size

vue-client/src/resources/json/combinedTemplates.json
New work templates for SVSK in Swedish and translated into Swedish.
=> Add work templates

vue-client/src/resources/json/combinedTemplates.json
Add template for streaming audiobook.
=> Add audiobook streaming template

vue-client/README.md
Även [Frontend i lokal miljö](https://github.com/libris/devops/wiki/Frontend-i-lokal-milj%C3%B6) har uppdaterats.
[LXL-4306](https://jira.kb.se/browse/LXL-4306)
=> Update readme after vue 3 migration

vue-client/src/components/care/create-message.vue, vue-client/src/components/inspector/toolbar.vue, vue-client/src/resources/json/combinedTemplates.json, vue-client/src/resources/json/i18n.json, vue-client/src/views/DirectoryCare.vue
[LXL-4321](https://jira.kb.se/browse/LXL-4321), [LXL-4322](https://jira.kb.se/browse/LXL-4322)
* New directory care section for creating "messages"
* "Inquirys" and "Change notices"
* Flagged records are added to the message
* Toolbar shortcut for creating a message concerning a specific record
Content of the message templates is not finalized.
=> Add directory care section for creating inquirys and change notices

vue-client/src/components/inspector/item-local.vue, vue-client/src/resources/json/i18n.json, vue-client/src/store.js
Add undoable extract actions and add label clarifying **what** is going to be extracted and **when** (on save).
- Add undoable extract actions
- Add label clarifying what is going to be extracted and when (on save).
=> Add undoable extract actions

vue-client/src/components/inspector/field.vue
Place the (?)-tooltip on top in the entity form.
[LXL-4408](https://jira.kb.se/browse/LXL-4408)
Minor css tweak
=> LXL-4408: Hidden tooltip fix

lxl-web/src/lib/actions/resourcePopover/ResourcePopover.svelte, lxl-web/src/lib/actions/resourcePopover/index.ts
[LXL-4447](https://jira.kb.se/browse/LXL-4447)
Close popover immediately on navigation
- Close popover immediately on navigation
=> Close popover immediately on navigation

lxl-web/src/lib/actions/resourcePopover/ResourcePopover.svelte, lxl-web/src/lib/actions/resourcePopover/index.ts
[LWS-52](https://jira.kb.se/browse/LWS-52)
Ensure popovers doesn't appear after navigating
- Ensure popovers doesn't appear after navigating
=> Ensure popovers doesn't appear after navigating

lxl-web/src/lib/components/DecoratedData.svelte, lxl-web/src/lib/utils/resourceData.ts, lxl-web/src/routes/(app)/[[lang=lang]]/find/SearchCard.svelte
[LWS-12](https://jira.kb.se/browse/LWS-12)
Fix missing decorated data properties
- Fix missing decorated data properties
- Simplify function names
=> Fix missing decorated data properties

lxl-web/src/lib/actions/resourcePopover/ResourcePopover.svelte, lxl-web/src/lib/components/DecoratedData.svelte, lxl-web/src/lib/types/DecoratedData.ts, lxl-web/src/lib/utils/resourceData.ts, lxl-web/src/lib/utils/xl.ts, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.server.ts, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.svelte
[LWS-12](https://jira.kb.se/browse/LWS-12)
Adds support for picking properties from decorated data
- Add support for picking properties from decorated data
- Add support for showing property labels
- Control label visibility using nolabel and showLabels override
- Add block prop to DecoratedData component
=> Add support for picking properties from decorated data

lxl-web/src/colors.css, lxl-web/src/routes/(app)/[[lang=lang]]/SiteHeader.svelte, lxl-web/tailwind.config.js
Minor changes to color palette after sync with Guldvarg.
=> Palette tweaks

lxl-web/playwright.config.ts, lxl-web/src/lib/components/Search.svelte, lxl-web/src/lib/utils/addDefaultSearchParams.ts, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.server.ts, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/Pagination.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/search.ts, lxl-web/tests/find.spec.ts
[LWS-64](https://jira.kb.se/browse/LWS-64)
* Fix links (filter view, up & pagination) so that they point to same path instead of /find
* Fix lang param bugs
* Hide zero results from resource page
* Fix streaming of search results to resource page
* Refactor load function of (find)/layout.server
* Fix failing test
=> LWS-64: relations improvements

lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.server.ts
See https://github.com/libris/librisxl/pull/1410
=> Get all links to resource from _o param

vue-client/src/resources/json/combinedTemplates.json
add requested details asked for by MTB
[LXL-NNNN](https://jira.kb.se/browse/[LXL-4246](https://jira.kb.se/browse/LXL-4246),
Description of what this solves
=> Update  "music-cd"

lxl-web/src/routes/(app)/[[lang=lang]]/(find)/[fnurgel=fnurgel]/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/[fnurgel=fnurgel]/InstancesList.svelte
[LWS-63](https://jira.kb.se/browse/LWS-63)
Fix issue with missing with missing holdings data
- Fix issue with missing holdings data
- Prevent flickering when navigating due to missing holdings data
=> LWS-63: Fix missing holdings data

lxl-web/src/app.css, lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/Pagination.svelte, lxl-web/tailwind.config.js
[LXL-NNNN](https://jira.kb.se/browse/LXL-NNNN), [LXL-NNNN](https://jira.kb.se/browse/LXL-NNNN)
Pagination is now styled
added global css for buttons, and then the style of the buttons was applied on pagination
=> added style for pagination

lxl-web/src/app.css, lxl-web/src/colors.css, lxl-web/src/lib/components/Search.svelte, lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/FacetRange.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/Pagination.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/SearchMapping.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/SiteHeader.svelte, lxl-web/tailwind.config.js
[LWS-126](https://kbse.atlassian.net/browse/LWS-126)
* Add a button for the search input
* Use new button classes on existing buttons
* Extend button classes with disabled/active state, negative variant etc.
* Tailwind-ify the CSS a bit
* Add focus outline for the search input
=> LWS-126: Add search button etc

lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.server.ts, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/SearchCard.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/search.ts
[LWS-163](https://kbse.atlassian.net/browse/LWS-163)
Show work type in search cards.
=> Display type in hit list

lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/FacetGroup.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/Filters.svelte
[LWS-120](https://kbse.atlassian.net/browse/LWS-120)
Went through all the components/pages in search of untranslated strings. Found only these, so I guess we're up to speed.
=> LWS-120: Add translations

lxl-web/src/routes/(app)/[[lang=lang]]/(find)/SearchMapping.svelte
[LWS-176](https://kbse.atlassian.net/browse/LWS-176)
Fixeds mapping layout issue on mobile screens when multiple filters are selected.
- Fix mobile mapping layout
=> LWS-176: Fix mobile mapping layout

lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/routes/(app)/[[lang=lang]]/(find)/+layout.svelte
As designed:
Example:
[LWS-179](https://jira.kb.se/browse/LWS-179)
=> Display pagination range. e.g. '11-20 of 42 hits'

lxl-web/src/routes/(app)/[[lang=lang]]/help/en.md, lxl-web/src/routes/(app)/[[lang=lang]]/help/sv.md
Updates changelog translation
- Update changelog translation
- Change date
=> Update english translation

lxl-web/src/lib/components/ResourceImage.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.svelte
[LWS-228](https://jira.kb.se/browse/LWS-228)
Fix image sizes and placement
- Fix image sizes and placement
=> LWS-228: Fix image sizes and placement

cataloging/src/components/care/bulk-changes.vue, cataloging/src/components/care/create-bulk-change.vue, cataloging/src/resources/json/combinedTemplates.json, cataloging/src/resources/json/i18n.json, cataloging/src/router.js, cataloging/src/store.js, cataloging/src/views/DirectoryCare.vue
Copied most of it from create-message.vue.
=> feat(cataloging-bulk-change): Add basic templates

lxl-web/src/lib/components/Matomo.svelte, lxl-web/src/lib/contexts/matomo.ts
[LXL-NNNN](https://kbse.atlassian.net/browse/LXL-NNNN), [LXL-NNNN](https://kbse.atlassian.net/browse/LXL-NNNN)
Description of what this solves
=> Move writable to setMatomoTracker

cataloging/src/components/inspector/field.vue, cataloging/src/settings.js
Unlock itemOf and heldBy when editing bulkchanges
=> Unlock itemOf and heldBy when editing bulkchanges

lxl-web/src/lib/components/SuperSearch.svelte, lxl-web/src/lib/utils/codemirror/extensions/findOnEnter.ts, lxl-web/src/lib/utils/supersearch/getFullSearchLink.ts
Display a link in the suggest box to the full search (same as hitting enter).
Visible when there's a value in the input and we don't display "no hits". But that's up for discussion.
=> Supersearch: all results link

cataloging/src/components/care/bulk-changes.vue, cataloging/src/components/care/form-builder.vue, cataloging/src/components/inspector/entity-adder.vue, cataloging/src/components/inspector/field.vue, cataloging/src/components/inspector/item-local.vue, cataloging/src/components/inspector/item-type.vue, cataloging/src/components/mixins/form-mixin.vue, cataloging/src/components/mixins/sidesearch-mixin.vue, cataloging/src/resources/json/combinedTemplates.json, cataloging/src/settings.js, cataloging/src/utils/bulk.js, cataloging/src/utils/data.js
See https://github.com/libris/librisxl/pull/1505
=> refactor(cataloging-bulkchanges): use new bulk terms

lxl-web/src/lib/assets/json/validQualifierTypes.json, lxl-web/src/lib/components/QualifierWidget.svelte, lxl-web/src/lib/components/Search.svelte, lxl-web/src/lib/components/SuperSearch.svelte, lxl-web/src/lib/utils/codemirror/extensions/qualifierWidgets.ts, lxl-web/src/lib/utils/supersearch/qualifiers.ts, lxl-web/src/routes/(app)/(find)/find/+page.server.ts, lxl-web/src/routes/(app)/(find)/find/+page.svelte, lxl-web/src/routes/api/[[lang=lang]]/qualifier-mapping/+server.ts, lxl-web/src/routes/api/[[lang=lang]]/qualifier-type/+server.ts, lxl-web/src/routes/styles.css
Adds qualifier improvements for demo purposes
- Add endpoint for valid qualifier types
- Fix qualifiers for year and title
- Add no results text
- Fix overflow ellipsis on values
- Update styling again
=> Add qualifier improvements for demo

cataloging/src/components/care/bulk-changes.vue, cataloging/src/components/care/preview.vue
* Auto refresh preview if not complete
* Show diff regardless of spec type
Depends on https://github.com/libris/librisxl/pull/1512
=> feat(cataloging//bukl-changes): Adjustments for generalized previews

cataloging/src/components/care/bulk-changes.vue, cataloging/src/components/inspector/entity-form.vue, cataloging/src/utils/bulk.js
Depends on 
https://github.com/libris/librisxl/pull/1517
https://github.com/libris/definitions/pull/504
=> Display bulk executions / reports

.github/workflows/codemirror-lang-lxlquery.yml, .github/workflows/lxl-web.yml, .github/workflows/supersearch.yml
[LWS-256](https://kbse.atlassian.net/browse/LWS-256)
Adds GitHub workflow files for `supersearch` and `codemirror-lang-lxlquery`. 
- Add GitHub workflow file for `supersearch`
- Add GitHub workflow file for `codemirror-lang-lxlquery`
- Specify paths to run `lxl-web` GitHub workflow on
=> LWS-256: Add GitHub workflows for supersearch and codemirror-lang-lxlquery

packages/supersearch/src/lib/components/SuperSearch.svelte
[LWS-276](https://kbse.atlassian.net/browse/LWS-276)
Closes expanded search dialog on click outside.
- Close dialog on click outside
=> LWS-276: Close dialog on click outside

cataloging/src/components/mixins/form-mixin.vue, cataloging/src/settings.js
* Hide image property for users other than SEK
* Clear image property when copying records
[LXL-4609](https://kbse.atlassian.net/browse/LXL-4609)
=> Hide image property for users other than SEK

cataloging/src/components/inspector/field-adder.vue, cataloging/src/components/inspector/property-adder.vue
[LXL-4615](https://kbse.atlassian.net/browse/LXL-4615)
Turns off autocomplete on adder inputs
- Turn off autocomplete on adder inputs
=> feat(cataloging): Turn off autocomplete on adder inputs (LXL-4615)

lxl-web/src/lib/assets/json/display-web.json, lxl-web/tests/resource.spec.ts
[LWS-270](https://kbse.atlassian.net/browse/LWS-270)
Should we do it??
* swap `familyName` `givenName` place, remove comma before properties, add 'no separator'.
=> fix(lxlweb): familyName givenName swap (LWS-270)

cataloging/src/resources/json/baseTemplates.json, cataloging/src/resources/json/combinedTemplates.json, lxl-web/src/lib/assets/json/test-data/main-entity.json, lxl-web/src/lib/assets/json/test-data/record.json
Depends on https://github.com/libris/definitions/pull/514
[LXL-3651](https://kbse.atlassian.net/browse/LXL-3651)
=> feat(cataloging): Update templates to use link for RDA cataloging rules

packages/supersearch/src/lib/extensions/lxlQualifierPlugin/insertSpaceAroundQualifier.ts
As a result of https://github.com/libris/lxlviewer/pull/1253 , selection now updates when user moves the cursor around. This means `insertSpaceAroudQualifier` util can rely on the `tr.startState` selection.
Refactored this util a bit to:
* Use `tr.startState` (`tr.state` should be avoided for performance reasons since it forces recalculation of new state that may be thrown away)
* Slightly more understandable code
=> fix(supersearch): insertSpaceAroundQualifier refactor

lxl-web/src/lib/utils/userSettings.svelte.ts, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/HoldingStatus.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/[fnurgel=fnurgel]/InstancesList.svelte
[LWS-303](https://kbse.atlassian.net/browse/LWS-303)
Show my libraries as a special section in the holdings modal.
* create derived `myLibsHolders` and show `HoldingStatus` for these separately
* Migrate components to v5 syntax: fnurgel/+page.svelte, HoldingStatus.svelte, InstancesList.svelte
=> feat(lxlweb): Show my libraries in holdings modal (LWS-303)

packages/supersearch/src/lib/extensions/lxlQualifierPlugin/insertSpaceAroundQualifier.ts
Refactor in https://github.com/libris/lxlviewer/pull/1281 seems to have introduced some bugs, like:
* Add a filter alias like `includeEplikt`, type something after it, and try to remove the pill. You can't.
* Paste query `ÅR:1997 contributor:"libris:qn247n18248vs58#it"` and change the 7 into an 8. It is inserted at the end 🤔 
Reverting to the old implementation, BUT keep usage of `tr.startState` instead of `tr.state`. So we at least gain something.
* revert `insertSpaceAroundQualifier` plugin
=> fix(lxlweb): revert insertSpaceAroundQualifier

lxl-web/src/lib/components/supersearch/SuperSearchWrapper.svelte, lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/routes/(app)/[[lang=lang]]/+page.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/SiteHeader.svelte
[LWS-360](https://kbse.atlassian.net/browse/LWS-360)
Adds a beta banner with a link for adding feedback
- Add beta banner with feedback link
- Fix positioning of search dialog when banner exists
=> feat(lxl-web): Add beta banner (LWS-360)

lxl-web/src/lib/i18n/locales/en.js, lxl-web/src/lib/i18n/locales/sv.js, lxl-web/src/routes/(app)/[[lang=lang]]/SiteFooter.svelte, lxl-web/src/routes/(app)/[[lang=lang]]/SiteHeader.svelte
[LWS-360](https://kbse.atlassian.net/browse/LWS-360)
Add banner link to old Libris
- Add banner link to old libris
- Adjust footer padding so it harmonizes with the header
=> feat(lxl-web): Add banner link to old libris
